#ifndef ABILITIES_H
#define ABILITIES_H

#include <array>
#include <bitset>
#include <unordered_map>
#include <debug/vector>

#include "Pokemon.h"

/*
 * Ignored:
 *    AngerPoint
 *    Anticipation
 *    ArenaTrap
 *    BadDreams
 *    BattleArmor
 *    Compoundeyes
 *    CuteCharm
 *    EarlyBird
 *    Forewarn
 *    Frisk
 *    HoneyGather
 *    Illuminate
 *    InnerFocus
 *    KeenEye
 *    LightningRod
 *    MagnetPull
 *    Minus
 *    NaturalCure
 *    Pickup
 *    Plus
 *    Pressure
 *    RunAway
 *    SereneGrace
 *    ShadowTag
 *    ShellArmor
 *    Sniper
 *    SnowCloak
 *    Static
 *    Steadfast
 *    Stench
 *    StormDrain
 *    Sturdy
 *    SuctionCups
 *    SuperLuck
 *    TangledFeet
 */

enum class Ability {
    Adaptability,
    Aftermath,
    AirLock,
    AngerPoint,
    Anticipation,
    ArenaTrap,
    BadDreams,
    BattleArmor,
    Blaze,
    Chlorophyll,
    ClearBody,
    CloudNine,
    ColorChange,
    Compoundeyes,
    CuteCharm,
    Damp,
    Download,
    Drizzle,
    Drought,
    DrySkin,
    EarlyBird,
    EffectSpore, // Only poisons player currently
    Filter,
    FlameBody, // Only burns player currently
    FlashFire,
    FlowerGift,
    Forecast,
    Forewarn,
    Frisk,
    Gluttony,
    Guts,
    Heatproof,
    HoneyGather,
    HugePower,
    Hustle,
    Hydration,
    HyperCutter,
    IceBody,
    Illuminate,
    Immunity,
    InnerFocus,
    Insomnia,
    Intimidate,
    IronFist,
    KeenEye,
    Klutz,
    LeafGuard,
    Levitate,
    LightningRod,
    Limber, // TODO skill swap and such will cure paralysis
    LiquidOoze,
    MagicGuard,
    MagmaArmor,
    MagnetPull,
    MarvelScale,
    Minus,
    MoldBreaker,
    MotorDrive,
    Multitype,
    NaturalCure,
    NoGuard,
    Normalize,
    Oblivious,
    Overgrow,
    OwnTempo,
    Pickup,
    Plus,
    PoisonHeal,
    PoisonPoint,
    Pressure,
    PurePower,
    QuickFeet,
    RainDish,
    Reckless,
    Rivalry,
    RockHead,
    RoughSkin,
    RunAway,
    SandStream,
    SandVeil,
    Scrappy,
    SereneGrace,
    ShadowTag,
    ShedSkin,
    ShellArmor,
    ShieldDust,
    Simple,
    SkillLink, // TODO
    SlowStart,
    Sniper,
    SnowCloak,
    SnowWarning,
    SolarPower,
    SolidRock,
    Soundproof,
    SpeedBoost,
    Stall,
    Static,
    Steadfast,
    Stench,
    StickyHold, // TODO Covet, Thief, Knock Off, Trick, Switcheroo
    StormDrain,
    Sturdy,
    SuctionCups,
    SuperLuck,
    Swarm,
    SwiftSwim,
    Synchronize,
    TangledFeet,
    Technician,
    ThickFat,
    TintedLens,
    Torrent,
    Trace,
    Truant, // Cannot be overwritten by Worry Seed,
            // but it can be overwritten by Skill Swap, Role Play,
            // or disabled with Gastro Acid.
    Unaware,
    Unburden,
    VitalSpirit,
    VoltAbsorb,
    WaterAbsorb,
    WaterVeil,
    WhiteSmoke,
    WonderGuard,
    Disabled
};

static constexpr std::array<bool, static_cast<size_t>(Ability::Disabled) + 1> IGNORABLE_ABILITIES = [] {
    std::array<bool, static_cast<size_t>(Ability::Disabled) + 1> flags{};
    flags.fill(false);
    flags[static_cast<int>(Ability::BattleArmor)] = true;
    flags[static_cast<int>(Ability::ClearBody)] = true;
    flags[static_cast<int>(Ability::Damp)] = true;
    flags[static_cast<int>(Ability::DrySkin)] = true;
    flags[static_cast<int>(Ability::Filter)] = true;
    flags[static_cast<int>(Ability::FlashFire)] = true;
    flags[static_cast<int>(Ability::FlowerGift)] = true;
    flags[static_cast<int>(Ability::Heatproof)] = true;
    flags[static_cast<int>(Ability::HyperCutter)] = true;
    flags[static_cast<int>(Ability::Immunity)] = true;
    flags[static_cast<int>(Ability::InnerFocus)] = true;
    flags[static_cast<int>(Ability::Insomnia)] = true;
    flags[static_cast<int>(Ability::KeenEye)] = true;
    flags[static_cast<int>(Ability::LeafGuard)] = true;
    flags[static_cast<int>(Ability::Levitate)] = true;
    flags[static_cast<int>(Ability::LightningRod)] = true;
    flags[static_cast<int>(Ability::Limber)] = true;
    flags[static_cast<int>(Ability::MagmaArmor)] = true;
    flags[static_cast<int>(Ability::MarvelScale)] = true;
    flags[static_cast<int>(Ability::MotorDrive)] = true;
    flags[static_cast<int>(Ability::Oblivious)] = true;
    flags[static_cast<int>(Ability::OwnTempo)] = true;
    flags[static_cast<int>(Ability::SandVeil)] = true;
    flags[static_cast<int>(Ability::ShellArmor)] = true;
    flags[static_cast<int>(Ability::ShieldDust)] = true;
    flags[static_cast<int>(Ability::Simple)] = true;
    flags[static_cast<int>(Ability::SnowCloak)] = true;
    flags[static_cast<int>(Ability::SolidRock)] = true;
    flags[static_cast<int>(Ability::Soundproof)] = true;
    flags[static_cast<int>(Ability::StickyHold)] = true;
    flags[static_cast<int>(Ability::StormDrain)] = true;
    flags[static_cast<int>(Ability::Sturdy)] = true;
    flags[static_cast<int>(Ability::SuctionCups)] = true;
    flags[static_cast<int>(Ability::TangledFeet)] = true;
    flags[static_cast<int>(Ability::ThickFat)] = true;
    flags[static_cast<int>(Ability::Unaware)] = true;
    flags[static_cast<int>(Ability::VitalSpirit)] = true;
    flags[static_cast<int>(Ability::VoltAbsorb)] = true;
    flags[static_cast<int>(Ability::WaterAbsorb)] = true;
    flags[static_cast<int>(Ability::WaterVeil)] = true;
    flags[static_cast<int>(Ability::WhiteSmoke)] = true;
    flags[static_cast<int>(Ability::WonderGuard)] = true;
    return flags;
}();

static bool ability_is_ignorable(Ability ability) {
    return IGNORABLE_ABILITIES.at(static_cast<int>(ability));
}

static constexpr std::array<bool, static_cast<size_t>(Ability::Disabled) + 1> NON_COPYABLE_ABILITIES = [] {
    std::array<bool, static_cast<size_t>(Ability::Disabled) + 1> flags{};
    flags.fill(false);
    flags[static_cast<int>(Ability::Forecast)] = true;
    flags[static_cast<int>(Ability::Multitype)] = true;
    flags[static_cast<int>(Ability::Trace)] = true;
    return flags;
}();

static bool ability_is_copyable(Ability ability) {
    return !NON_COPYABLE_ABILITIES.at(static_cast<int>(ability));
}

static const std::unordered_map<Ability, std::string> ABILITY_TO_STRING = {
    {Ability::Adaptability, "Adaptability"},
    {Ability::Aftermath, "Aftermath"},
    {Ability::AirLock, "Air Lock"},
    {Ability::AngerPoint, "Anger Point"},
    {Ability::Anticipation, "Anticipation"},
    {Ability::ArenaTrap, "Arena Trap"},
    {Ability::BadDreams, "Bad Dreams"},
    {Ability::BattleArmor, "Battle Armor"},
    {Ability::Blaze, "Blaze"},
    {Ability::Chlorophyll, "Chlorophyll"},
    {Ability::ClearBody, "Clear Body"},
    {Ability::CloudNine, "Cloud Nine"},
    {Ability::ColorChange, "Color Change"},
    {Ability::Compoundeyes, "Compound Eyes"},
    {Ability::CuteCharm, "Cute Charm"},
    {Ability::Damp, "Damp"},
    {Ability::Download, "Download"},
    {Ability::Drizzle, "Drizzle"},
    {Ability::Drought, "Drought"},
    {Ability::DrySkin, "Dry Skin"},
    {Ability::EarlyBird, "Early Bird"},
    {Ability::EffectSpore, "Effect Spore"},
    {Ability::Filter, "Filter"},
    {Ability::FlameBody, "Flame Body"},
    {Ability::FlashFire, "Flash Fire"},
    {Ability::FlowerGift, "Flower Gift"},
    {Ability::Forecast, "Forecast"},
    {Ability::Forewarn, "Forewarn"},
    {Ability::Frisk, "Frisk"},
    {Ability::Gluttony, "Gluttony"},
    {Ability::Guts, "Guts"},
    {Ability::Heatproof, "Heatproof"},
    {Ability::HoneyGather, "Honey Gather"},
    {Ability::HugePower, "Huge Power"},
    {Ability::Hustle, "Hustle"},
    {Ability::Hydration, "Hydration"},
    {Ability::HyperCutter, "Hyper Cutter"},
    {Ability::IceBody, "Ice Body"},
    {Ability::Illuminate, "Illuminate"},
    {Ability::Immunity, "Immunity"},
    {Ability::InnerFocus, "Inner Focus"},
    {Ability::Insomnia, "Insomnia"},
    {Ability::Intimidate, "Intimidate"},
    {Ability::IronFist, "Iron Fist"},
    {Ability::KeenEye, "Keen Eye"},
    {Ability::Klutz, "Klutz"},
    {Ability::LeafGuard, "Leaf Guard"},
    {Ability::Levitate, "Levitate"},
    {Ability::LightningRod, "Lightning Rod"},
    {Ability::Limber, "Limber"},
    {Ability::LiquidOoze, "Liquid Ooze"},
    {Ability::MagicGuard, "Magic Guard"},
    {Ability::MagmaArmor, "Magma Armor"},
    {Ability::MagnetPull, "Magnet Pull"},
    {Ability::MarvelScale, "Marvel Scale"},
    {Ability::Minus, "Minus"},
    {Ability::MoldBreaker, "Mold Breaker"},
    {Ability::MotorDrive, "Motor Drive"},
    {Ability::Multitype, "Multitype"},
    {Ability::NaturalCure, "Natural Cure"},
    {Ability::NoGuard, "No Guard"},
    {Ability::Normalize, "Normalize"},
    {Ability::Oblivious, "Oblivious"},
    {Ability::Overgrow, "Overgrow"},
    {Ability::OwnTempo, "Own Tempo"},
    {Ability::Pickup, "Pickup"},
    {Ability::Plus, "Plus"},
    {Ability::PoisonHeal, "Poison Heal"},
    {Ability::PoisonPoint, "Poison Point"},
    {Ability::Pressure, "Pressure"},
    {Ability::PurePower, "Pure Power"},
    {Ability::QuickFeet, "Quick Feet"},
    {Ability::RainDish, "Rain Dish"},
    {Ability::Reckless, "Reckless"},
    {Ability::Rivalry, "Rivalry"},
    {Ability::RockHead, "Rock Head"},
    {Ability::RoughSkin, "Rough Skin"},
    {Ability::RunAway, "Run Away"},
    {Ability::SandStream, "Sand Stream"},
    {Ability::SandVeil, "Sand Veil"},
    {Ability::Scrappy, "Scrappy"},
    {Ability::SereneGrace, "Serene Grace"},
    {Ability::ShadowTag, "Shadow Tag"},
    {Ability::ShedSkin, "Shed Skin"},
    {Ability::ShellArmor, "Shell Armor"},
    {Ability::ShieldDust, "Shield Dust"},
    {Ability::Simple, "Simple"},
    {Ability::SkillLink, "Skill Link"},
    {Ability::SlowStart, "Slow Start"},
    {Ability::Sniper, "Sniper"},
    {Ability::SnowCloak, "Snow Cloak"},
    {Ability::SnowWarning, "Snow Warning"},
    {Ability::SolarPower, "Solar Power"},
    {Ability::SolidRock, "Solid Rock"},
    {Ability::Soundproof, "Soundproof"},
    {Ability::SpeedBoost, "Speed Boost"},
    {Ability::Stall, "Stall"},
    {Ability::Static, "Static"},
    {Ability::Steadfast, "Steadfast"},
    {Ability::Stench, "Stench"},
    {Ability::StickyHold, "Sticky Hold"},
    {Ability::StormDrain, "Storm Drain"},
    {Ability::Sturdy, "Sturdy"},
    {Ability::SuctionCups, "Suction Cups"},
    {Ability::SuperLuck, "Super Luck"},
    {Ability::Swarm, "Swarm"},
    {Ability::SwiftSwim, "Swift Swim"},
    {Ability::Synchronize, "Synchronize"},
    {Ability::TangledFeet, "Tangled Feet"},
    {Ability::Technician, "Technician"},
    {Ability::ThickFat, "Thick Fat"},
    {Ability::TintedLens, "Tinted Lens"},
    {Ability::Torrent, "Torrent"},
    {Ability::Trace, "Trace"},
    {Ability::Truant, "Truant"},
    {Ability::Unaware, "Unaware"},
    {Ability::Unburden, "Unburden"},
    {Ability::VitalSpirit, "Vital Spirit"},
    {Ability::VoltAbsorb, "Volt Absorb"},
    {Ability::WaterAbsorb, "Water Absorb"},
    {Ability::WaterVeil, "Water Veil"},
    {Ability::WhiteSmoke, "White Smoke"},
    {Ability::WonderGuard, "Wonder Guard"}
};

static const std::unordered_map<Pokemon, std::vector<Ability>> ABILITY_MAP = {
    {Pokemon::Abomasnow, {Ability::SnowWarning}},
    {Pokemon::Abra, {Ability::InnerFocus, Ability::Synchronize}},
    {Pokemon::Absol, {Ability::Pressure, Ability::SuperLuck}},
    {Pokemon::Aerodactyl, {Ability::Pressure, Ability::RockHead}},
    {Pokemon::Aggron, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Aipom, {Ability::Pickup, Ability::RunAway}},
    {Pokemon::Alakazam, {Ability::InnerFocus, Ability::Synchronize}},
    {Pokemon::Altaria, {Ability::NaturalCure}},
    {Pokemon::Ambipom, {Ability::Pickup, Ability::Technician}},
    {Pokemon::Ampharos, {Ability::Static}},
    {Pokemon::Anorith, {Ability::BattleArmor}},
    {Pokemon::Arbok, {Ability::Intimidate, Ability::ShedSkin}},
    {Pokemon::Arcanine, {Ability::FlashFire, Ability::Intimidate}},
    {Pokemon::Arceus, {Ability::Multitype}},
    {Pokemon::Ariados, {Ability::Insomnia, Ability::Swarm}},
    {Pokemon::Armaldo, {Ability::BattleArmor}},
    {Pokemon::Aron, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Articuno, {Ability::Pressure}},
    {Pokemon::Azelf, {Ability::Levitate}},
    {Pokemon::Azumarill, {Ability::HugePower, Ability::ThickFat}},
    {Pokemon::Azurill, {Ability::HugePower, Ability::ThickFat}},
    {Pokemon::Bagon, {Ability::RockHead}},
    {Pokemon::Baltoy, {Ability::Levitate}},
    {Pokemon::Banette, {Ability::Frisk, Ability::Insomnia}},
    {Pokemon::Barboach, {Ability::Anticipation, Ability::Oblivious}},
    {Pokemon::Bastiodon, {Ability::Sturdy}},
    {Pokemon::Bayleef, {Ability::Overgrow}},
    {Pokemon::Beautifly, {Ability::Swarm}},
    {Pokemon::Beedrill, {Ability::Swarm}},
    {Pokemon::Beldum, {Ability::ClearBody}},
    {Pokemon::Bellossom, {Ability::Chlorophyll}},
    {Pokemon::Bellsprout, {Ability::Chlorophyll}},
    {Pokemon::Bibarel, {Ability::Simple, Ability::Unaware}},
    {Pokemon::Bidoof, {Ability::Simple, Ability::Unaware}},
    {Pokemon::Blastoise, {Ability::Torrent}},
    {Pokemon::Blaziken, {Ability::Blaze}},
    {Pokemon::Blissey, {Ability::NaturalCure, Ability::SereneGrace}},
    {Pokemon::Bonsly, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Breloom, {Ability::EffectSpore, Ability::PoisonHeal}},
    {Pokemon::Bronzong, {Ability::Heatproof, Ability::Levitate}},
    {Pokemon::Bronzor, {Ability::Heatproof, Ability::Levitate}},
    {Pokemon::Budew, {Ability::NaturalCure, Ability::PoisonPoint}},
    {Pokemon::Buizel, {Ability::SwiftSwim}},
    {Pokemon::Bulbasaur, {Ability::Overgrow}},
    {Pokemon::Buneary, {Ability::Klutz, Ability::RunAway}},
    {Pokemon::Burmy, {Ability::ShedSkin}},
    {Pokemon::Butterfree, {Ability::Compoundeyes}},
    {Pokemon::Cacnea, {Ability::SandVeil}},
    {Pokemon::Cacturne, {Ability::SandVeil}},
    {Pokemon::Camerupt, {Ability::MagmaArmor, Ability::SolidRock}},
    {Pokemon::Carnivine, {Ability::Levitate}},
    {Pokemon::Carvanha, {Ability::RoughSkin}},
    {Pokemon::Cascoon, {Ability::ShedSkin}},
    {Pokemon::Castform, {Ability::Forecast}},
    {Pokemon::Caterpie, {Ability::ShieldDust}},
    {Pokemon::Celebi, {Ability::NaturalCure}},
    {Pokemon::Chansey, {Ability::NaturalCure, Ability::SereneGrace}},
    {Pokemon::Charizard, {Ability::Blaze}},
    {Pokemon::Charmander, {Ability::Blaze}},
    {Pokemon::Charmeleon, {Ability::Blaze}},
    {Pokemon::Chatot, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Cherrim, {Ability::FlowerGift}},
    {Pokemon::Cherubi, {Ability::Chlorophyll}},
    {Pokemon::Chikorita, {Ability::Overgrow}},
    {Pokemon::Chimchar, {Ability::Blaze}},
    {Pokemon::Chimecho, {Ability::Levitate}},
    {Pokemon::Chinchou, {Ability::Illuminate, Ability::VoltAbsorb}},
    {Pokemon::Chingling, {Ability::Levitate}},
    {Pokemon::Clamperl, {Ability::ShellArmor}},
    {Pokemon::Claydol, {Ability::Levitate}},
    {Pokemon::Clefable, {Ability::CuteCharm, Ability::MagicGuard}},
    {Pokemon::Clefairy, {Ability::CuteCharm, Ability::MagicGuard}},
    {Pokemon::Cleffa, {Ability::CuteCharm, Ability::MagicGuard}},
    {Pokemon::Cloyster, {Ability::ShellArmor, Ability::SkillLink}},
    {Pokemon::Combee, {Ability::HoneyGather}},
    {Pokemon::Combusken, {Ability::Blaze}},
    {Pokemon::Corphish, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Corsola, {Ability::Hustle, Ability::NaturalCure}},
    {Pokemon::Cradily, {Ability::SuctionCups}},
    {Pokemon::Cranidos, {Ability::MoldBreaker}},
    {Pokemon::Crawdaunt, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Cresselia, {Ability::Levitate}},
    {Pokemon::Croagunk, {Ability::Anticipation, Ability::DrySkin}},
    {Pokemon::Crobat, {Ability::InnerFocus}},
    {Pokemon::Croconaw, {Ability::Torrent}},
    {Pokemon::Cubone, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Cyndaquil, {Ability::Blaze}},
    {Pokemon::Darkrai, {Ability::BadDreams}},
    {Pokemon::Delcatty, {Ability::CuteCharm, Ability::Normalize}},
    {Pokemon::Delibird, {Ability::Hustle, Ability::VitalSpirit}},
    {Pokemon::NormalDeoxys, {Ability::Pressure}},
    {Pokemon::AttackDeoxys, {Ability::Pressure}},
    {Pokemon::DefenseDeoxys, {Ability::Pressure}},
    {Pokemon::SpeedDeoxys, {Ability::Pressure}},
    {Pokemon::Dewgong, {Ability::Hydration, Ability::ThickFat}},
    {Pokemon::Dialga, {Ability::Pressure}},
    {Pokemon::Diglett, {Ability::ArenaTrap, Ability::SandVeil}},
    {Pokemon::Ditto, {Ability::Limber}},
    {Pokemon::Dodrio, {Ability::EarlyBird, Ability::RunAway}},
    {Pokemon::Doduo, {Ability::EarlyBird, Ability::RunAway}},
    {Pokemon::Donphan, {Ability::Sturdy}},
    {Pokemon::Dragonair, {Ability::ShedSkin}},
    {Pokemon::Dragonite, {Ability::InnerFocus}},
    {Pokemon::Drapion, {Ability::BattleArmor, Ability::Sniper}},
    {Pokemon::Dratini, {Ability::ShedSkin}},
    {Pokemon::Drifblim, {Ability::Aftermath, Ability::Unburden}},
    {Pokemon::Drifloon, {Ability::Aftermath, Ability::Unburden}},
    {Pokemon::Drowzee, {Ability::Forewarn, Ability::Insomnia}},
    {Pokemon::Dugtrio, {Ability::ArenaTrap, Ability::SandVeil}},
    {Pokemon::Dunsparce, {Ability::RunAway, Ability::SereneGrace}},
    {Pokemon::Dusclops, {Ability::Pressure}},
    {Pokemon::Dusknoir, {Ability::Pressure}},
    {Pokemon::Duskull, {Ability::Levitate}},
    {Pokemon::Dustox, {Ability::ShieldDust}},
    {Pokemon::Eevee, {Ability::Adaptability, Ability::RunAway}},
    {Pokemon::Ekans, {Ability::Intimidate, Ability::ShedSkin}},
    {Pokemon::Electabuzz, {Ability::Static}},
    {Pokemon::Electivire, {Ability::MotorDrive}},
    {Pokemon::Electrike, {Ability::LightningRod, Ability::Static}},
    {Pokemon::Electrode, {Ability::Soundproof, Ability::Static}},
    {Pokemon::Elekid, {Ability::Static}},
    {Pokemon::Empoleon, {Ability::Torrent}},
    {Pokemon::Entei, {Ability::Pressure}},
    {Pokemon::Espeon, {Ability::Synchronize}},
    {Pokemon::Exeggcute, {Ability::Chlorophyll}},
    {Pokemon::Exeggutor, {Ability::Chlorophyll}},
    {Pokemon::Exploud, {Ability::Soundproof}},
    {Pokemon::Farfetchd, {Ability::InnerFocus, Ability::KeenEye}},
    {Pokemon::Fearow, {Ability::KeenEye}},
    {Pokemon::Feebas, {Ability::SwiftSwim}},
    {Pokemon::Feraligatr, {Ability::Torrent}},
    {Pokemon::Finneon, {Ability::StormDrain, Ability::SwiftSwim}},
    {Pokemon::Flaaffy, {Ability::Static}},
    {Pokemon::Flareon, {Ability::FlashFire}},
    {Pokemon::Floatzel, {Ability::SwiftSwim}},
    {Pokemon::Flygon, {Ability::Levitate}},
    {Pokemon::Forretress, {Ability::Sturdy}},
    {Pokemon::Froslass, {Ability::SnowCloak}},
    {Pokemon::Furret, {Ability::KeenEye, Ability::RunAway}},
    {Pokemon::Gabite, {Ability::SandVeil}},
    {Pokemon::Gallade, {Ability::Steadfast}},
    {Pokemon::Garchomp, {Ability::SandVeil}},
    {Pokemon::Gardevoir, {Ability::Synchronize, Ability::Trace}},
    {Pokemon::Gastly, {Ability::Levitate}},
    {Pokemon::Gastrodon, {Ability::StickyHold, Ability::StormDrain}},
    {Pokemon::Gengar, {Ability::Levitate}},
    {Pokemon::Geodude, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Gible, {Ability::SandVeil}},
    {Pokemon::Girafarig, {Ability::EarlyBird, Ability::InnerFocus}},
    {Pokemon::AlteredGiratina, {Ability::Pressure}},
    {Pokemon::OriginGiratina, {Ability::Levitate}},
    {Pokemon::Glaceon, {Ability::SnowCloak}},
    {Pokemon::Glalie, {Ability::IceBody, Ability::InnerFocus}},
    {Pokemon::Glameow, {Ability::Limber, Ability::OwnTempo}},
    {Pokemon::Gligar, {Ability::HyperCutter, Ability::SandVeil}},
    {Pokemon::Gliscor, {Ability::HyperCutter, Ability::SandVeil}},
    {Pokemon::Gloom, {Ability::Chlorophyll}},
    {Pokemon::Golbat, {Ability::InnerFocus}},
    {Pokemon::Goldeen, {Ability::SwiftSwim, Ability::WaterVeil}},
    {Pokemon::Golduck, {Ability::CloudNine, Ability::Damp}},
    {Pokemon::Golem, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Gorebyss, {Ability::SwiftSwim}},
    {Pokemon::Granbull, {Ability::Intimidate, Ability::QuickFeet}},
    {Pokemon::Graveler, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Grimer, {Ability::Stench, Ability::StickyHold}},
    {Pokemon::Grotle, {Ability::Overgrow}},
    {Pokemon::Groudon, {Ability::Drought}},
    {Pokemon::Grovyle, {Ability::Overgrow}},
    {Pokemon::Growlithe, {Ability::FlashFire, Ability::Intimidate}},
    {Pokemon::Grumpig, {Ability::OwnTempo, Ability::ThickFat}},
    {Pokemon::Gulpin, {Ability::LiquidOoze, Ability::StickyHold}},
    {Pokemon::Gyarados, {Ability::Intimidate}},
    {Pokemon::Happiny, {Ability::NaturalCure, Ability::SereneGrace}},
    {Pokemon::Hariyama, {Ability::Guts, Ability::ThickFat}},
    {Pokemon::Haunter, {Ability::Levitate}},
    {Pokemon::Heatran, {Ability::FlashFire}},
    {Pokemon::Heracross, {Ability::Guts, Ability::Swarm}},
    {Pokemon::Hippopotas, {Ability::SandStream}},
    {Pokemon::Hippowdon, {Ability::SandStream}},
    {Pokemon::Hitmonchan, {Ability::IronFist, Ability::KeenEye}},
    {Pokemon::Hitmonlee, {Ability::Limber, Ability::Reckless}},
    {Pokemon::Hitmontop, {Ability::Intimidate, Ability::Technician}},
    {Pokemon::HoOh, {Ability::Pressure}},
    {Pokemon::Honchkrow, {Ability::Insomnia, Ability::SuperLuck}},
    {Pokemon::Hoothoot, {Ability::Insomnia, Ability::KeenEye}},
    {Pokemon::Hoppip, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Horsea, {Ability::Sniper, Ability::SwiftSwim}},
    {Pokemon::Houndoom, {Ability::EarlyBird, Ability::FlashFire}},
    {Pokemon::Houndour, {Ability::EarlyBird, Ability::FlashFire}},
    {Pokemon::Huntail, {Ability::SwiftSwim}},
    {Pokemon::Hypno, {Ability::Forewarn, Ability::Insomnia}},
    {Pokemon::Igglybuff, {Ability::CuteCharm}},
    {Pokemon::Illumise, {Ability::Oblivious, Ability::TintedLens}},
    {Pokemon::Infernape, {Ability::Blaze}},
    {Pokemon::Ivysaur, {Ability::Overgrow}},
    {Pokemon::Jigglypuff, {Ability::CuteCharm}},
    {Pokemon::Jirachi, {Ability::SereneGrace}},
    {Pokemon::Jolteon, {Ability::VoltAbsorb}},
    {Pokemon::Jumpluff, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Jynx, {Ability::Forewarn, Ability::Oblivious}},
    {Pokemon::Kabuto, {Ability::BattleArmor, Ability::SwiftSwim}},
    {Pokemon::Kabutops, {Ability::BattleArmor, Ability::SwiftSwim}},
    {Pokemon::Kadabra, {Ability::InnerFocus, Ability::Synchronize}},
    {Pokemon::Kakuna, {Ability::ShedSkin}},
    {Pokemon::Kangaskhan, {Ability::EarlyBird, Ability::Scrappy}},
    {Pokemon::Kecleon, {Ability::ColorChange}},
    {Pokemon::Kingdra, {Ability::Sniper, Ability::SwiftSwim}},
    {Pokemon::Kingler, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Kirlia, {Ability::Synchronize, Ability::Trace}},
    {Pokemon::Koffing, {Ability::Levitate}},
    {Pokemon::Krabby, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Kricketot, {Ability::ShedSkin}},
    {Pokemon::Kricketune, {Ability::Swarm}},
    {Pokemon::Kyogre, {Ability::Drizzle}},
    {Pokemon::Lairon, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Lanturn, {Ability::Illuminate, Ability::VoltAbsorb}},
    {Pokemon::Lapras, {Ability::ShellArmor, Ability::WaterAbsorb}},
    {Pokemon::Larvitar, {Ability::Guts}},
    {Pokemon::Latias, {Ability::Levitate}},
    {Pokemon::Latios, {Ability::Levitate}},
    {Pokemon::Leafeon, {Ability::LeafGuard}},
    {Pokemon::Ledian, {Ability::EarlyBird, Ability::Swarm}},
    {Pokemon::Ledyba, {Ability::EarlyBird, Ability::Swarm}},
    {Pokemon::Lickilicky, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Lickitung, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Lileep, {Ability::SuctionCups}},
    {Pokemon::Linoone, {Ability::Gluttony, Ability::Pickup}},
    {Pokemon::Lombre, {Ability::RainDish, Ability::SwiftSwim}},
    {Pokemon::Lopunny, {Ability::CuteCharm, Ability::Klutz}},
    {Pokemon::Lotad, {Ability::RainDish, Ability::SwiftSwim}},
    {Pokemon::Loudred, {Ability::Soundproof}},
    {Pokemon::Lucario, {Ability::InnerFocus, Ability::Steadfast}},
    {Pokemon::Ludicolo, {Ability::RainDish, Ability::SwiftSwim}},
    {Pokemon::Lugia, {Ability::Pressure}},
    {Pokemon::Lumineon, {Ability::StormDrain, Ability::SwiftSwim}},
    {Pokemon::Lunatone, {Ability::Levitate}},
    {Pokemon::Luvdisc, {Ability::SwiftSwim}},
    {Pokemon::Luxio, {Ability::Intimidate, Ability::Rivalry}},
    {Pokemon::Luxray, {Ability::Intimidate, Ability::Rivalry}},
    {Pokemon::Machamp, {Ability::Guts, Ability::NoGuard}},
    {Pokemon::Machoke, {Ability::Guts, Ability::NoGuard}},
    {Pokemon::Machop, {Ability::Guts, Ability::NoGuard}},
    {Pokemon::Magby, {Ability::FlameBody}},
    {Pokemon::Magcargo, {Ability::FlameBody, Ability::MagmaArmor}},
    {Pokemon::Magikarp, {Ability::SwiftSwim}},
    {Pokemon::Magmar, {Ability::FlameBody}},
    {Pokemon::Magmortar, {Ability::FlameBody}},
    {Pokemon::Magnemite, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Magneton, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Magnezone, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Makuhita, {Ability::Guts, Ability::ThickFat}},
    {Pokemon::Mamoswine, {Ability::Oblivious, Ability::SnowCloak}},
    {Pokemon::Manaphy, {Ability::Hydration}},
    {Pokemon::Manectric, {Ability::LightningRod, Ability::Static}},
    {Pokemon::Mankey, {Ability::AngerPoint, Ability::VitalSpirit}},
    {Pokemon::Mantine, {Ability::SwiftSwim, Ability::WaterAbsorb}},
    {Pokemon::Mantyke, {Ability::SwiftSwim, Ability::WaterAbsorb}},
    {Pokemon::Mareep, {Ability::Static}},
    {Pokemon::Marill, {Ability::HugePower, Ability::ThickFat}},
    {Pokemon::Marowak, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Marshtomp, {Ability::Torrent}},
    {Pokemon::Masquerain, {Ability::Intimidate}},
    {Pokemon::Mawile, {Ability::HyperCutter, Ability::Intimidate}},
    {Pokemon::Medicham, {Ability::PurePower}},
    {Pokemon::Meditite, {Ability::PurePower}},
    {Pokemon::Meganium, {Ability::Overgrow}},
    {Pokemon::Meowth, {Ability::Pickup, Ability::Technician}},
    {Pokemon::Mesprit, {Ability::Levitate}},
    {Pokemon::Metagross, {Ability::ClearBody}},
    {Pokemon::Metang, {Ability::ClearBody}},
    {Pokemon::Metapod, {Ability::ShedSkin}},
    {Pokemon::Mew, {Ability::Synchronize}},
    {Pokemon::Mewtwo, {Ability::Pressure}},
    {Pokemon::Mightyena, {Ability::Intimidate, Ability::QuickFeet}},
    {Pokemon::Milotic, {Ability::MarvelScale}},
    {Pokemon::Miltank, {Ability::Scrappy, Ability::ThickFat}},
    {Pokemon::MimeJr, {Ability::Filter, Ability::Soundproof}},
    {Pokemon::Minun, {Ability::Minus}},
    {Pokemon::Misdreavus, {Ability::Levitate}},
    {Pokemon::Mismagius, {Ability::Levitate}},
    {Pokemon::Moltres, {Ability::Pressure}},
    {Pokemon::Monferno, {Ability::Blaze}},
    {Pokemon::Mothim, {Ability::Swarm}},
    {Pokemon::MrMime, {Ability::Filter, Ability::Soundproof}},
    {Pokemon::Mudkip, {Ability::Torrent}},
    {Pokemon::Muk, {Ability::Stench, Ability::StickyHold}},
    {Pokemon::Munchlax, {Ability::Pickup, Ability::ThickFat}},
    {Pokemon::Murkrow, {Ability::Insomnia, Ability::SuperLuck}},
    {Pokemon::Natu, {Ability::EarlyBird, Ability::Synchronize}},
    {Pokemon::Nidoking, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nidoqueen, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::NidoranF, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::NidoranM, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nidorina, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nidorino, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nincada, {Ability::Compoundeyes}},
    {Pokemon::Ninetales, {Ability::FlashFire}},
    {Pokemon::Ninjask, {Ability::SpeedBoost}},
    {Pokemon::Noctowl, {Ability::Insomnia, Ability::KeenEye}},
    {Pokemon::Nosepass, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Numel, {Ability::Oblivious, Ability::Simple}},
    {Pokemon::Nuzleaf, {Ability::Chlorophyll, Ability::EarlyBird}},
    {Pokemon::Octillery, {Ability::Sniper, Ability::SuctionCups}},
    {Pokemon::Oddish, {Ability::Chlorophyll}},
    {Pokemon::Omanyte, {Ability::ShellArmor, Ability::SwiftSwim}},
    {Pokemon::Omastar, {Ability::ShellArmor, Ability::SwiftSwim}},
    {Pokemon::Onix, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Pachirisu, {Ability::Pickup, Ability::RunAway}},
    {Pokemon::Palkia, {Ability::Pressure}},
    {Pokemon::Paras, {Ability::DrySkin, Ability::EffectSpore}},
    {Pokemon::Parasect, {Ability::DrySkin, Ability::EffectSpore}},
    {Pokemon::Pelipper, {Ability::KeenEye}},
    {Pokemon::Persian, {Ability::Limber, Ability::Technician}},
    {Pokemon::Phanpy, {Ability::Pickup}},
    {Pokemon::Phione, {Ability::Hydration}},
    {Pokemon::Pichu, {Ability::Static}},
    {Pokemon::Pidgeot, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Pidgeotto, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Pidgey, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Pikachu, {Ability::Static}},
    {Pokemon::Piloswine, {Ability::Oblivious, Ability::SnowCloak}},
    {Pokemon::Pineco, {Ability::Sturdy}},
    {Pokemon::Pinsir, {Ability::HyperCutter, Ability::MoldBreaker}},
    {Pokemon::Piplup, {Ability::Torrent}},
    {Pokemon::Plusle, {Ability::Plus}},
    {Pokemon::Politoed, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Poliwag, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Poliwhirl, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Poliwrath, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Ponyta, {Ability::FlashFire, Ability::RunAway}},
    {Pokemon::Poochyena, {Ability::QuickFeet, Ability::RunAway}},
    {Pokemon::Porygon, {Ability::Download, Ability::Trace}},
    {Pokemon::PorygonZ, {Ability::Adaptability, Ability::Download}},
    {Pokemon::Porygon2, {Ability::Download, Ability::Trace}},
    {Pokemon::Primeape, {Ability::AngerPoint, Ability::VitalSpirit}},
    {Pokemon::Prinplup, {Ability::Torrent}},
    {Pokemon::Probopass, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Psyduck, {Ability::CloudNine, Ability::Damp}},
    {Pokemon::Pupitar, {Ability::ShedSkin}},
    {Pokemon::Purugly, {Ability::OwnTempo, Ability::ThickFat}},
    {Pokemon::Quagsire, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Quilava, {Ability::Blaze}},
    {Pokemon::Qwilfish, {Ability::PoisonPoint, Ability::SwiftSwim}},
    {Pokemon::Raichu, {Ability::Static}},
    {Pokemon::Raikou, {Ability::Pressure}},
    {Pokemon::Ralts, {Ability::Synchronize, Ability::Trace}},
    {Pokemon::Rampardos, {Ability::MoldBreaker}},
    {Pokemon::Rapidash, {Ability::FlashFire, Ability::RunAway}},
    {Pokemon::Raticate, {Ability::Guts, Ability::RunAway}},
    {Pokemon::Rattata, {Ability::Guts, Ability::RunAway}},
    {Pokemon::Rayquaza, {Ability::AirLock}},
    {Pokemon::Regice, {Ability::ClearBody}},
    {Pokemon::Regigigas, {Ability::SlowStart}},
    {Pokemon::Regirock, {Ability::ClearBody}},
    {Pokemon::Registeel, {Ability::ClearBody}},
    {Pokemon::Relicanth, {Ability::RockHead, Ability::SwiftSwim}},
    {Pokemon::Remoraid, {Ability::Hustle, Ability::Sniper}},
    {Pokemon::Rhydon, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Rhyhorn, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Rhyperior, {Ability::LightningRod, Ability::SolidRock}},
    {Pokemon::Riolu, {Ability::InnerFocus, Ability::Steadfast}},
    {Pokemon::Roselia, {Ability::NaturalCure, Ability::PoisonPoint}},
    {Pokemon::Roserade, {Ability::NaturalCure, Ability::PoisonPoint}},
    {Pokemon::Rotom, {Ability::Levitate}},
    {Pokemon::Sableye, {Ability::KeenEye, Ability::Stall}},
    {Pokemon::Salamence, {Ability::Intimidate}},
    {Pokemon::Sandshrew, {Ability::SandVeil}},
    {Pokemon::Sandslash, {Ability::SandVeil}},
    {Pokemon::Sceptile, {Ability::Overgrow}},
    {Pokemon::Scizor, {Ability::Swarm, Ability::Technician}},
    {Pokemon::Scyther, {Ability::Swarm, Ability::Technician}},
    {Pokemon::Seadra, {Ability::PoisonPoint, Ability::Sniper}},
    {Pokemon::Seaking, {Ability::SwiftSwim, Ability::WaterVeil}},
    {Pokemon::Sealeo, {Ability::IceBody, Ability::ThickFat}},
    {Pokemon::Seedot, {Ability::Chlorophyll, Ability::EarlyBird}},
    {Pokemon::Seel, {Ability::Hydration, Ability::ThickFat}},
    {Pokemon::Sentret, {Ability::KeenEye, Ability::RunAway}},
    {Pokemon::Seviper, {Ability::ShedSkin}},
    {Pokemon::Sharpedo, {Ability::RoughSkin}},
    {Pokemon::LandShaymin, {Ability::NaturalCure}},
    {Pokemon::SkyShaymin, {Ability::SereneGrace}},
    {Pokemon::Shedinja, {Ability::WonderGuard}},
    {Pokemon::Shelgon, {Ability::RockHead}},
    {Pokemon::Shellder, {Ability::ShellArmor, Ability::SkillLink}},
    {Pokemon::Shellos, {Ability::StickyHold, Ability::StormDrain}},
    {Pokemon::Shieldon, {Ability::Sturdy}},
    {Pokemon::Shiftry, {Ability::Chlorophyll, Ability::EarlyBird}},
    {Pokemon::Shinx, {Ability::Intimidate, Ability::Rivalry}},
    {Pokemon::Shroomish, {Ability::EffectSpore, Ability::PoisonHeal}},
    {Pokemon::Shuckle, {Ability::Gluttony, Ability::Sturdy}},
    {Pokemon::Shuppet, {Ability::Frisk, Ability::Insomnia}},
    {Pokemon::Silcoon, {Ability::ShedSkin}},
    {Pokemon::Skarmory, {Ability::KeenEye, Ability::Sturdy}},
    {Pokemon::Skiploom, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Skitty, {Ability::CuteCharm, Ability::Normalize}},
    {Pokemon::Skorupi, {Ability::BattleArmor, Ability::Sniper}},
    {Pokemon::Skuntank, {Ability::Aftermath, Ability::Stench}},
    {Pokemon::Slaking, {Ability::Truant}},
    {Pokemon::Slakoth, {Ability::Truant}},
    {Pokemon::Slowbro, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Slowking, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Slowpoke, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Slugma, {Ability::FlameBody, Ability::MagmaArmor}},
    {Pokemon::Smeargle, {Ability::OwnTempo, Ability::Technician}},
    {Pokemon::Smoochum, {Ability::Forewarn, Ability::Oblivious}},
    {Pokemon::Sneasel, {Ability::InnerFocus, Ability::KeenEye}},
    {Pokemon::Snorlax, {Ability::Immunity, Ability::ThickFat}},
    {Pokemon::Snorunt, {Ability::IceBody, Ability::InnerFocus}},
    {Pokemon::Snover, {Ability::SnowWarning}},
    {Pokemon::Snubbull, {Ability::Intimidate, Ability::RunAway}},
    {Pokemon::Solrock, {Ability::Levitate}},
    {Pokemon::Spearow, {Ability::KeenEye}},
    {Pokemon::Spheal, {Ability::IceBody, Ability::ThickFat}},
    {Pokemon::Spinarak, {Ability::Insomnia, Ability::Swarm}},
    {Pokemon::Spinda, {Ability::OwnTempo, Ability::TangledFeet}},
    {Pokemon::Spiritomb, {Ability::Pressure}},
    {Pokemon::Spoink, {Ability::OwnTempo, Ability::ThickFat}},
    {Pokemon::Squirtle, {Ability::Torrent}},
    {Pokemon::Stantler, {Ability::Frisk, Ability::Intimidate}},
    {Pokemon::Staraptor, {Ability::Intimidate}},
    {Pokemon::Staravia, {Ability::Intimidate}},
    {Pokemon::Starly, {Ability::KeenEye}},
    {Pokemon::Starmie, {Ability::Illuminate, Ability::NaturalCure}},
    {Pokemon::Staryu, {Ability::Illuminate, Ability::NaturalCure}},
    {Pokemon::Steelix, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Stunky, {Ability::Aftermath, Ability::Stench}},
    {Pokemon::Sudowoodo, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Suicune, {Ability::Pressure}},
    {Pokemon::Sunflora, {Ability::Chlorophyll, Ability::SolarPower}},
    {Pokemon::Sunkern, {Ability::Chlorophyll, Ability::SolarPower}},
    {Pokemon::Surskit, {Ability::SwiftSwim}},
    {Pokemon::Swablu, {Ability::NaturalCure}},
    {Pokemon::Swalot, {Ability::LiquidOoze, Ability::StickyHold}},
    {Pokemon::Swampert, {Ability::Torrent}},
    {Pokemon::Swellow, {Ability::Guts}},
    {Pokemon::Swinub, {Ability::Oblivious, Ability::SnowCloak}},
    {Pokemon::Taillow, {Ability::Guts}},
    {Pokemon::Tangela, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Tangrowth, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Tauros, {Ability::AngerPoint, Ability::Intimidate}},
    {Pokemon::Teddiursa, {Ability::Pickup, Ability::QuickFeet}},
    {Pokemon::Tentacool, {Ability::ClearBody, Ability::LiquidOoze}},
    {Pokemon::Tentacruel, {Ability::ClearBody, Ability::LiquidOoze}},
    {Pokemon::Togekiss, {Ability::Hustle, Ability::SereneGrace}},
    {Pokemon::Togepi, {Ability::Hustle, Ability::SereneGrace}},
    {Pokemon::Togetic, {Ability::Hustle, Ability::SereneGrace}},
    {Pokemon::Torchic, {Ability::Blaze}},
    {Pokemon::Torkoal, {Ability::WhiteSmoke}},
    {Pokemon::Torterra, {Ability::Overgrow}},
    {Pokemon::Totodile, {Ability::Torrent}},
    {Pokemon::Toxicroak, {Ability::Anticipation, Ability::DrySkin}},
    {Pokemon::Trapinch, {Ability::ArenaTrap, Ability::HyperCutter}},
    {Pokemon::Treecko, {Ability::Overgrow}},
    {Pokemon::Tropius, {Ability::Chlorophyll, Ability::SolarPower}},
    {Pokemon::Turtwig, {Ability::Overgrow}},
    {Pokemon::Typhlosion, {Ability::Blaze}},
    {Pokemon::Tyranitar, {Ability::SandStream}},
    {Pokemon::Tyrogue, {Ability::Guts, Ability::Steadfast}},
    {Pokemon::Umbreon, {Ability::Synchronize}},
    {Pokemon::Unown, {Ability::Levitate}},
    {Pokemon::Ursaring, {Ability::Guts, Ability::QuickFeet}},
    {Pokemon::Uxie, {Ability::Levitate}},
    {Pokemon::Vaporeon, {Ability::WaterAbsorb}},
    {Pokemon::Venomoth, {Ability::ShieldDust, Ability::TintedLens}},
    {Pokemon::Venonat, {Ability::Compoundeyes, Ability::TintedLens}},
    {Pokemon::Venusaur, {Ability::Overgrow}},
    {Pokemon::Vespiquen, {Ability::Pressure}},
    {Pokemon::Vibrava, {Ability::Levitate}},
    {Pokemon::Victreebel, {Ability::Chlorophyll}},
    {Pokemon::Vigoroth, {Ability::VitalSpirit}},
    {Pokemon::Vileplume, {Ability::Chlorophyll}},
    {Pokemon::Volbeat, {Ability::Illuminate, Ability::Swarm}},
    {Pokemon::Voltorb, {Ability::Soundproof, Ability::Static}},
    {Pokemon::Vulpix, {Ability::FlashFire}},
    {Pokemon::Wailmer, {Ability::Oblivious, Ability::WaterVeil}},
    {Pokemon::Wailord, {Ability::Oblivious, Ability::WaterVeil}},
    {Pokemon::Walrein, {Ability::IceBody, Ability::ThickFat}},
    {Pokemon::Wartortle, {Ability::Torrent}},
    {Pokemon::Weavile, {Ability::Pressure}},
    {Pokemon::Weedle, {Ability::ShieldDust}},
    {Pokemon::Weepinbell, {Ability::Chlorophyll}},
    {Pokemon::Weezing, {Ability::Levitate}},
    {Pokemon::Whiscash, {Ability::Anticipation, Ability::Oblivious}},
    {Pokemon::Whismur, {Ability::Soundproof}},
    {Pokemon::Wigglytuff, {Ability::CuteCharm}},
    {Pokemon::Wingull, {Ability::KeenEye}},
    {Pokemon::Wobbuffet, {Ability::ShadowTag}},
    {Pokemon::Wooper, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::WormadamP, {Ability::Anticipation}},
    {Pokemon::WormadamS, {Ability::Anticipation}},
    {Pokemon::WormadamT, {Ability::Anticipation}},
    {Pokemon::Wurmple, {Ability::ShieldDust}},
    {Pokemon::Wynaut, {Ability::ShadowTag}},
    {Pokemon::Xatu, {Ability::EarlyBird, Ability::Synchronize}},
    {Pokemon::Yanma, {Ability::Compoundeyes, Ability::SpeedBoost}},
    {Pokemon::Yanmega, {Ability::SpeedBoost, Ability::TintedLens}},
    {Pokemon::Zangoose, {Ability::Immunity}},
    {Pokemon::Zapdos, {Ability::Pressure}},
    {Pokemon::Zigzagoon, {Ability::Gluttony, Ability::Pickup}},
    {Pokemon::Zubat, {Ability::InnerFocus}},
};

#endif //ABILITIES_H
