#ifndef ABILITIES_H
#define ABILITIES_H

#include <string>
#include <unordered_map>
#include <debug/vector>

enum class Pokemon {
    Abomasnow,
    Abra,
    Absol,
    Aerodactyl,
    Aggron,
    Aipom,
    Alakazam,
    Altaria,
    Ambipom,
    Ampharos,
    Anorith,
    Arbok,
    Arcanine,
    Arceus,
    Ariados,
    Armaldo,
    Aron,
    Articuno,
    Azelf,
    Azumarill,
    Azurill,
    Bagon,
    Baltoy,
    Banette,
    Barboach,
    Bastiodon,
    Bayleef,
    Beautifly,
    Beedrill,
    Beldum,
    Bellossom,
    Bellsprout,
    Bibarel,
    Bidoof,
    Blastoise,
    Blaziken,
    Blissey,
    Bonsly,
    Breloom,
    Bronzong,
    Bronzor,
    Budew,
    Buizel,
    Bulbasaur,
    Buneary,
    Burmy,
    Butterfree,
    Cacnea,
    Cacturne,
    Camerupt,
    Carnivine,
    Carvanha,
    Cascoon,
    Castform,
    Caterpie,
    Celebi,
    Chansey,
    Charizard,
    Charmander,
    Charmeleon,
    Chatot,
    Cherrim,
    Cherubi,
    Chikorita,
    Chimchar,
    Chimecho,
    Chinchou,
    Chingling,
    Clamperl,
    Claydol,
    Clefable,
    Clefairy,
    Cleffa,
    Cloyster,
    Combee,
    Combusken,
    Corphish,
    Corsola,
    Cradily,
    Cranidos,
    Crawdaunt,
    Cresselia,
    Croagunk,
    Crobat,
    Croconaw,
    Cubone,
    Cyndaquil,
    Darkrai,
    Delcatty,
    Delibird,
    NormalDeoxys,
    AttackDeoxys,
    DefenseDeoxys,
    SpeedDeoxys,
    Dewgong,
    Dialga,
    Diglett,
    Ditto,
    Dodrio,
    Doduo,
    Donphan,
    Dragonair,
    Dragonite,
    Drapion,
    Dratini,
    Drifblim,
    Drifloon,
    Drowzee,
    Dugtrio,
    Dunsparce,
    Dusclops,
    Dusknoir,
    Duskull,
    Dustox,
    Eevee,
    Ekans,
    Electabuzz,
    Electivire,
    Electrike,
    Electrode,
    Elekid,
    Empoleon,
    Entei,
    Espeon,
    Exeggcute,
    Exeggutor,
    Exploud,
    Farfetchd,
    Fearow,
    Feebas,
    Feraligatr,
    Finneon,
    Flaaffy,
    Flareon,
    Floatzel,
    Flygon,
    Forretress,
    Froslass,
    Furret,
    Gabite,
    Gallade,
    Garchomp,
    Gardevoir,
    Gastly,
    Gastrodon,
    Gengar,
    Geodude,
    Gible,
    Girafarig,
    AlteredGiratina,
    OriginGiratina,
    Glaceon,
    Glalie,
    Glameow,
    Gligar,
    Gliscor,
    Gloom,
    Golbat,
    Goldeen,
    Golduck,
    Golem,
    Gorebyss,
    Granbull,
    Graveler,
    Grimer,
    Grotle,
    Groudon,
    Grovyle,
    Growlithe,
    Grumpig,
    Gulpin,
    Gyarados,
    Happiny,
    Hariyama,
    Haunter,
    Heatran,
    Heracross,
    Hippopotas,
    Hippowdon,
    Hitmonchan,
    Hitmonlee,
    Hitmontop,
    HoOh,
    Honchkrow,
    Hoothoot,
    Hoppip,
    Horsea,
    Houndoom,
    Houndour,
    Huntail,
    Hypno,
    Igglybuff,
    Illumise,
    Infernape,
    Ivysaur,
    Jigglypuff,
    Jirachi,
    Jolteon,
    Jumpluff,
    Jynx,
    Kabuto,
    Kabutops,
    Kadabra,
    Kakuna,
    Kangaskhan,
    Kecleon,
    Kingdra,
    Kingler,
    Kirlia,
    Koffing,
    Krabby,
    Kricketot,
    Kricketune,
    Kyogre,
    Lairon,
    Lanturn,
    Lapras,
    Larvitar,
    Latias,
    Latios,
    Leafeon,
    Ledian,
    Ledyba,
    Lickilicky,
    Lickitung,
    Lileep,
    Linoone,
    Lombre,
    Lopunny,
    Lotad,
    Loudred,
    Lucario,
    Ludicolo,
    Lugia,
    Lumineon,
    Lunatone,
    Luvdisc,
    Luxio,
    Luxray,
    Machamp,
    Machoke,
    Machop,
    Magby,
    Magcargo,
    Magikarp,
    Magmar,
    Magmortar,
    Magnemite,
    Magneton,
    Magnezone,
    Makuhita,
    Mamoswine,
    Manaphy,
    Manectric,
    Mankey,
    Mantine,
    Mantyke,
    Mareep,
    Marill,
    Marowak,
    Marshtomp,
    Masquerain,
    Mawile,
    Medicham,
    Meditite,
    Meganium,
    Meowth,
    Mesprit,
    Metagross,
    Metang,
    Metapod,
    Mew,
    Mewtwo,
    Mightyena,
    Milotic,
    Miltank,
    MimeJr,
    Minun,
    Misdreavus,
    Mismagius,
    Moltres,
    Monferno,
    Mothim,
    MrMime,
    Mudkip,
    Muk,
    Munchlax,
    Murkrow,
    Natu,
    Nidoking,
    Nidoqueen,
    NidoranF,
    NidoranM,
    Nidorina,
    Nidorino,
    Nincada,
    Ninetales,
    Ninjask,
    Noctowl,
    Nosepass,
    Numel,
    Nuzleaf,
    Octillery,
    Oddish,
    Omanyte,
    Omastar,
    Onix,
    Pachirisu,
    Palkia,
    Paras,
    Parasect,
    Pelipper,
    Persian,
    Phanpy,
    Phione,
    Pichu,
    Pidgeot,
    Pidgeotto,
    Pidgey,
    Pikachu,
    Piloswine,
    Pineco,
    Pinsir,
    Piplup,
    Plusle,
    Politoed,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Ponyta,
    Poochyena,
    Porygon,
    PorygonZ,
    Porygon2,
    Primeape,
    Prinplup,
    Probopass,
    Psyduck,
    Pupitar,
    Purugly,
    Quagsire,
    Quilava,
    Qwilfish,
    Raichu,
    Raikou,
    Ralts,
    Rampardos,
    Rapidash,
    Raticate,
    Rattata,
    Rayquaza,
    Regice,
    Regigigas,
    Regirock,
    Registeel,
    Relicanth,
    Remoraid,
    Rhydon,
    Rhyhorn,
    Rhyperior,
    Riolu,
    Roselia,
    Roserade,
    Rotom,
    HeatRotom,
    WashRotom,
    FrostRotom,
    FanRotom,
    MowRotom,
    Sableye,
    Salamence,
    Sandshrew,
    Sandslash,
    Sceptile,
    Scizor,
    Scyther,
    Seadra,
    Seaking,
    Sealeo,
    Seedot,
    Seel,
    Sentret,
    Seviper,
    Sharpedo,
    LandShaymin,
    SkyShaymin,
    Shedinja,
    Shelgon,
    Shellder,
    Shellos,
    Shieldon,
    Shiftry,
    Shinx,
    Shroomish,
    Shuckle,
    Shuppet,
    Silcoon,
    Skarmory,
    Skiploom,
    Skitty,
    Skorupi,
    Skuntank,
    Slaking,
    Slakoth,
    Slowbro,
    Slowking,
    Slowpoke,
    Slugma,
    Smeargle,
    Smoochum,
    Sneasel,
    Snorlax,
    Snorunt,
    Snover,
    Snubbull,
    Solrock,
    Spearow,
    Spheal,
    Spinarak,
    Spinda,
    Spiritomb,
    Spoink,
    Squirtle,
    Stantler,
    Staraptor,
    Staravia,
    Starly,
    Starmie,
    Staryu,
    Steelix,
    Stunky,
    Sudowoodo,
    Suicune,
    Sunflora,
    Sunkern,
    Surskit,
    Swablu,
    Swalot,
    Swampert,
    Swellow,
    Swinub,
    Taillow,
    Tangela,
    Tangrowth,
    Tauros,
    Teddiursa,
    Tentacool,
    Tentacruel,
    Togekiss,
    Togepi,
    Togetic,
    Torchic,
    Torkoal,
    Torterra,
    Totodile,
    Toxicroak,
    Trapinch,
    Treecko,
    Tropius,
    Turtwig,
    Typhlosion,
    Tyranitar,
    Tyrogue,
    Umbreon,
    Unown,
    Ursaring,
    Uxie,
    Vaporeon,
    Venomoth,
    Venonat,
    Venusaur,
    Vespiquen,
    Vibrava,
    Victreebel,
    Vigoroth,
    Vileplume,
    Volbeat,
    Voltorb,
    Vulpix,
    Wailmer,
    Wailord,
    Walrein,
    Wartortle,
    Weavile,
    Weedle,
    Weepinbell,
    Weezing,
    Whiscash,
    Whismur,
    Wigglytuff,
    Wingull,
    Wobbuffet,
    Wooper,
    WormadamP,
    WormadamS,
    WormadamT,
    Wurmple,
    Wynaut,
    Xatu,
    Yanma,
    Yanmega,
    Zangoose,
    Zapdos,
    Zigzagoon,
    Zubat
};

static const std::unordered_map<std::string, Pokemon> STRING_TO_POKEMON = {
    {"Abomasnow", Pokemon::Abomasnow},
    {"Abra", Pokemon::Abra},
    {"Absol", Pokemon::Absol},
    {"Aerodactyl", Pokemon::Aerodactyl},
    {"Aggron", Pokemon::Aggron},
    {"Aipom", Pokemon::Aipom},
    {"Alakazam", Pokemon::Alakazam},
    {"Altaria", Pokemon::Altaria},
    {"Ambipom", Pokemon::Ambipom},
    {"Ampharos", Pokemon::Ampharos},
    {"Anorith", Pokemon::Anorith},
    {"Arbok", Pokemon::Arbok},
    {"Arcanine", Pokemon::Arcanine},
    {"Arceus", Pokemon::Arceus},
    {"Ariados", Pokemon::Ariados},
    {"Armaldo", Pokemon::Armaldo},
    {"Aron", Pokemon::Aron},
    {"Articuno", Pokemon::Articuno},
    {"Azelf", Pokemon::Azelf},
    {"Azumarill", Pokemon::Azumarill},
    {"Azurill", Pokemon::Azurill},
    {"Bagon", Pokemon::Bagon},
    {"Baltoy", Pokemon::Baltoy},
    {"Banette", Pokemon::Banette},
    {"Barboach", Pokemon::Barboach},
    {"Bastiodon", Pokemon::Bastiodon},
    {"Bayleef", Pokemon::Bayleef},
    {"Beautifly", Pokemon::Beautifly},
    {"Beedrill", Pokemon::Beedrill},
    {"Beldum", Pokemon::Beldum},
    {"Bellossom", Pokemon::Bellossom},
    {"Bellsprout", Pokemon::Bellsprout},
    {"Bibarel", Pokemon::Bibarel},
    {"Bidoof", Pokemon::Bidoof},
    {"Blastoise", Pokemon::Blastoise},
    {"Blaziken", Pokemon::Blaziken},
    {"Blissey", Pokemon::Blissey},
    {"Bonsly", Pokemon::Bonsly},
    {"Breloom", Pokemon::Breloom},
    {"Bronzong", Pokemon::Bronzong},
    {"Bronzor", Pokemon::Bronzor},
    {"Budew", Pokemon::Budew},
    {"Buizel", Pokemon::Buizel},
    {"Bulbasaur", Pokemon::Bulbasaur},
    {"Buneary", Pokemon::Buneary},
    {"Burmy", Pokemon::Burmy},
    {"Butterfree", Pokemon::Butterfree},
    {"Cacnea", Pokemon::Cacnea},
    {"Cacturne", Pokemon::Cacturne},
    {"Camerupt", Pokemon::Camerupt},
    {"Carnivine", Pokemon::Carnivine},
    {"Carvanha", Pokemon::Carvanha},
    {"Cascoon", Pokemon::Cascoon},
    {"Castform", Pokemon::Castform},
    {"Caterpie", Pokemon::Caterpie},
    {"Celebi", Pokemon::Celebi},
    {"Chansey", Pokemon::Chansey},
    {"Charizard", Pokemon::Charizard},
    {"Charmander", Pokemon::Charmander},
    {"Charmeleon", Pokemon::Charmeleon},
    {"Chatot", Pokemon::Chatot},
    {"Cherrim", Pokemon::Cherrim},
    {"Cherubi", Pokemon::Cherubi},
    {"Chikorita", Pokemon::Chikorita},
    {"Chimchar", Pokemon::Chimchar},
    {"Chimecho", Pokemon::Chimecho},
    {"Chinchou", Pokemon::Chinchou},
    {"Chingling", Pokemon::Chingling},
    {"Clamperl", Pokemon::Clamperl},
    {"Claydol", Pokemon::Claydol},
    {"Clefable", Pokemon::Clefable},
    {"Clefairy", Pokemon::Clefairy},
    {"Cleffa", Pokemon::Cleffa},
    {"Cloyster", Pokemon::Cloyster},
    {"Combee", Pokemon::Combee},
    {"Combusken", Pokemon::Combusken},
    {"Corphish", Pokemon::Corphish},
    {"Corsola", Pokemon::Corsola},
    {"Cradily", Pokemon::Cradily},
    {"Cranidos", Pokemon::Cranidos},
    {"Crawdaunt", Pokemon::Crawdaunt},
    {"Cresselia", Pokemon::Cresselia},
    {"Croagunk", Pokemon::Croagunk},
    {"Crobat", Pokemon::Crobat},
    {"Croconaw", Pokemon::Croconaw},
    {"Cubone", Pokemon::Cubone},
    {"Cyndaquil", Pokemon::Cyndaquil},
    {"Darkrai", Pokemon::Darkrai},
    {"Delcatty", Pokemon::Delcatty},
    {"Delibird", Pokemon::Delibird},
    {"NormalDeoxys", Pokemon::NormalDeoxys},
    {"AttackDeoxys", Pokemon::AttackDeoxys},
    {"DefenseDeoxys", Pokemon::DefenseDeoxys},
    {"SpeedDeoxys", Pokemon::SpeedDeoxys},
    {"Dewgong", Pokemon::Dewgong},
    {"Dialga", Pokemon::Dialga},
    {"Diglett", Pokemon::Diglett},
    {"Ditto", Pokemon::Ditto},
    {"Dodrio", Pokemon::Dodrio},
    {"Doduo", Pokemon::Doduo},
    {"Donphan", Pokemon::Donphan},
    {"Dragonair", Pokemon::Dragonair},
    {"Dragonite", Pokemon::Dragonite},
    {"Drapion", Pokemon::Drapion},
    {"Dratini", Pokemon::Dratini},
    {"Drifblim", Pokemon::Drifblim},
    {"Drifloon", Pokemon::Drifloon},
    {"Drowzee", Pokemon::Drowzee},
    {"Dugtrio", Pokemon::Dugtrio},
    {"Dunsparce", Pokemon::Dunsparce},
    {"Dusclops", Pokemon::Dusclops},
    {"Dusknoir", Pokemon::Dusknoir},
    {"Duskull", Pokemon::Duskull},
    {"Dustox", Pokemon::Dustox},
    {"Eevee", Pokemon::Eevee},
    {"Ekans", Pokemon::Ekans},
    {"Electabuzz", Pokemon::Electabuzz},
    {"Electivire", Pokemon::Electivire},
    {"Electrike", Pokemon::Electrike},
    {"Electrode", Pokemon::Electrode},
    {"Elekid", Pokemon::Elekid},
    {"Empoleon", Pokemon::Empoleon},
    {"Entei", Pokemon::Entei},
    {"Espeon", Pokemon::Espeon},
    {"Exeggcute", Pokemon::Exeggcute},
    {"Exeggutor", Pokemon::Exeggutor},
    {"Exploud", Pokemon::Exploud},
    {"Farfetch'd", Pokemon::Farfetchd},
    {"Fearow", Pokemon::Fearow},
    {"Feebas", Pokemon::Feebas},
    {"Feraligatr", Pokemon::Feraligatr},
    {"Finneon", Pokemon::Finneon},
    {"Flaaffy", Pokemon::Flaaffy},
    {"Flareon", Pokemon::Flareon},
    {"Floatzel", Pokemon::Floatzel},
    {"Flygon", Pokemon::Flygon},
    {"Forretress", Pokemon::Forretress},
    {"Froslass", Pokemon::Froslass},
    {"Furret", Pokemon::Furret},
    {"Gabite", Pokemon::Gabite},
    {"Gallade", Pokemon::Gallade},
    {"Garchomp", Pokemon::Garchomp},
    {"Gardevoir", Pokemon::Gardevoir},
    {"Gastly", Pokemon::Gastly},
    {"Gastrodon", Pokemon::Gastrodon},
    {"Gengar", Pokemon::Gengar},
    {"Geodude", Pokemon::Geodude},
    {"Gible", Pokemon::Gible},
    {"Girafarig", Pokemon::Girafarig},
    {"AlteredGiratina", Pokemon::AlteredGiratina},
    {"OriginGiratina", Pokemon::OriginGiratina},
    {"Glaceon", Pokemon::Glaceon},
    {"Glalie", Pokemon::Glalie},
    {"Glameow", Pokemon::Glameow},
    {"Gligar", Pokemon::Gligar},
    {"Gliscor", Pokemon::Gliscor},
    {"Gloom", Pokemon::Gloom},
    {"Golbat", Pokemon::Golbat},
    {"Goldeen", Pokemon::Goldeen},
    {"Golduck", Pokemon::Golduck},
    {"Golem", Pokemon::Golem},
    {"Gorebyss", Pokemon::Gorebyss},
    {"Granbull", Pokemon::Granbull},
    {"Graveler", Pokemon::Graveler},
    {"Grimer", Pokemon::Grimer},
    {"Grotle", Pokemon::Grotle},
    {"Groudon", Pokemon::Groudon},
    {"Grovyle", Pokemon::Grovyle},
    {"Growlithe", Pokemon::Growlithe},
    {"Grumpig", Pokemon::Grumpig},
    {"Gulpin", Pokemon::Gulpin},
    {"Gyarados", Pokemon::Gyarados},
    {"Happiny", Pokemon::Happiny},
    {"Hariyama", Pokemon::Hariyama},
    {"Haunter", Pokemon::Haunter},
    {"Heatran", Pokemon::Heatran},
    {"Heracross", Pokemon::Heracross},
    {"Hippopotas", Pokemon::Hippopotas},
    {"Hippowdon", Pokemon::Hippowdon},
    {"Hitmonchan", Pokemon::Hitmonchan},
    {"Hitmonlee", Pokemon::Hitmonlee},
    {"Hitmontop", Pokemon::Hitmontop},
    {"Ho-oh", Pokemon::HoOh},
    {"Honchkrow", Pokemon::Honchkrow},
    {"Hoothoot", Pokemon::Hoothoot},
    {"Hoppip", Pokemon::Hoppip},
    {"Horsea", Pokemon::Horsea},
    {"Houndoom", Pokemon::Houndoom},
    {"Houndour", Pokemon::Houndour},
    {"Huntail", Pokemon::Huntail},
    {"Hypno", Pokemon::Hypno},
    {"Igglybuff", Pokemon::Igglybuff},
    {"Illumise", Pokemon::Illumise},
    {"Infernape", Pokemon::Infernape},
    {"Ivysaur", Pokemon::Ivysaur},
    {"Jigglypuff", Pokemon::Jigglypuff},
    {"Jirachi", Pokemon::Jirachi},
    {"Jolteon", Pokemon::Jolteon},
    {"Jumpluff", Pokemon::Jumpluff},
    {"Jynx", Pokemon::Jynx},
    {"Kabuto", Pokemon::Kabuto},
    {"Kabutops", Pokemon::Kabutops},
    {"Kadabra", Pokemon::Kadabra},
    {"Kakuna", Pokemon::Kakuna},
    {"Kangaskhan", Pokemon::Kangaskhan},
    {"Kecleon", Pokemon::Kecleon},
    {"Kingdra", Pokemon::Kingdra},
    {"Kingler", Pokemon::Kingler},
    {"Kirlia", Pokemon::Kirlia},
    {"Koffing", Pokemon::Koffing},
    {"Krabby", Pokemon::Krabby},
    {"Kricketot", Pokemon::Kricketot},
    {"Kricketune", Pokemon::Kricketune},
    {"Kyogre", Pokemon::Kyogre},
    {"Lairon", Pokemon::Lairon},
    {"Lanturn", Pokemon::Lanturn},
    {"Lapras", Pokemon::Lapras},
    {"Larvitar", Pokemon::Larvitar},
    {"Latias", Pokemon::Latias},
    {"Latios", Pokemon::Latios},
    {"Leafeon", Pokemon::Leafeon},
    {"Ledian", Pokemon::Ledian},
    {"Ledyba", Pokemon::Ledyba},
    {"Lickilicky", Pokemon::Lickilicky},
    {"Lickitung", Pokemon::Lickitung},
    {"Lileep", Pokemon::Lileep},
    {"Linoone", Pokemon::Linoone},
    {"Lombre", Pokemon::Lombre},
    {"Lopunny", Pokemon::Lopunny},
    {"Lotad", Pokemon::Lotad},
    {"Loudred", Pokemon::Loudred},
    {"Lucario", Pokemon::Lucario},
    {"Ludicolo", Pokemon::Ludicolo},
    {"Lugia", Pokemon::Lugia},
    {"Lumineon", Pokemon::Lumineon},
    {"Lunatone", Pokemon::Lunatone},
    {"Luvdisc", Pokemon::Luvdisc},
    {"Luxio", Pokemon::Luxio},
    {"Luxray", Pokemon::Luxray},
    {"Machamp", Pokemon::Machamp},
    {"Machoke", Pokemon::Machoke},
    {"Machop", Pokemon::Machop},
    {"Magby", Pokemon::Magby},
    {"Magcargo", Pokemon::Magcargo},
    {"Magikarp", Pokemon::Magikarp},
    {"Magmar", Pokemon::Magmar},
    {"Magmortar", Pokemon::Magmortar},
    {"Magnemite", Pokemon::Magnemite},
    {"Magneton", Pokemon::Magneton},
    {"Magnezone", Pokemon::Magnezone},
    {"Makuhita", Pokemon::Makuhita},
    {"Mamoswine", Pokemon::Mamoswine},
    {"Manaphy", Pokemon::Manaphy},
    {"Manectric", Pokemon::Manectric},
    {"Mankey", Pokemon::Mankey},
    {"Mantine", Pokemon::Mantine},
    {"Mantyke", Pokemon::Mantyke},
    {"Mareep", Pokemon::Mareep},
    {"Marill", Pokemon::Marill},
    {"Marowak", Pokemon::Marowak},
    {"Marshtomp", Pokemon::Marshtomp},
    {"Masquerain", Pokemon::Masquerain},
    {"Mawile", Pokemon::Mawile},
    {"Medicham", Pokemon::Medicham},
    {"Meditite", Pokemon::Meditite},
    {"Meganium", Pokemon::Meganium},
    {"Meowth", Pokemon::Meowth},
    {"Mesprit", Pokemon::Mesprit},
    {"Metagross", Pokemon::Metagross},
    {"Metang", Pokemon::Metang},
    {"Metapod", Pokemon::Metapod},
    {"Mew", Pokemon::Mew},
    {"Mewtwo", Pokemon::Mewtwo},
    {"Mightyena", Pokemon::Mightyena},
    {"Milotic", Pokemon::Milotic},
    {"Miltank", Pokemon::Miltank},
    {"Mime Jr.", Pokemon::MimeJr},
    {"Minun", Pokemon::Minun},
    {"Misdreavus", Pokemon::Misdreavus},
    {"Mismagius", Pokemon::Mismagius},
    {"Moltres", Pokemon::Moltres},
    {"Monferno", Pokemon::Monferno},
    {"Mothim", Pokemon::Mothim},
    {"Mr. Mime", Pokemon::MrMime},
    {"Mudkip", Pokemon::Mudkip},
    {"Muk", Pokemon::Muk},
    {"Munchlax", Pokemon::Munchlax},
    {"Murkrow", Pokemon::Murkrow},
    {"Natu", Pokemon::Natu},
    {"Nidoking", Pokemon::Nidoking},
    {"Nidoqueen", Pokemon::Nidoqueen},
    {"Nidoran(F)", Pokemon::NidoranF},
    {"Nidoran(M)", Pokemon::NidoranM},
    {"Nidorina", Pokemon::Nidorina},
    {"Nidorino", Pokemon::Nidorino},
    {"Nincada", Pokemon::Nincada},
    {"Ninetales", Pokemon::Ninetales},
    {"Ninjask", Pokemon::Ninjask},
    {"Noctowl", Pokemon::Noctowl},
    {"Nosepass", Pokemon::Nosepass},
    {"Numel", Pokemon::Numel},
    {"Nuzleaf", Pokemon::Nuzleaf},
    {"Octillery", Pokemon::Octillery},
    {"Oddish", Pokemon::Oddish},
    {"Omanyte", Pokemon::Omanyte},
    {"Omastar", Pokemon::Omastar},
    {"Onix", Pokemon::Onix},
    {"Pachirisu", Pokemon::Pachirisu},
    {"Palkia", Pokemon::Palkia},
    {"Paras", Pokemon::Paras},
    {"Parasect", Pokemon::Parasect},
    {"Pelipper", Pokemon::Pelipper},
    {"Persian", Pokemon::Persian},
    {"Phanpy", Pokemon::Phanpy},
    {"Phione", Pokemon::Phione},
    {"Pichu", Pokemon::Pichu},
    {"Pidgeot", Pokemon::Pidgeot},
    {"Pidgeotto", Pokemon::Pidgeotto},
    {"Pidgey", Pokemon::Pidgey},
    {"Pikachu", Pokemon::Pikachu},
    {"Piloswine", Pokemon::Piloswine},
    {"Pineco", Pokemon::Pineco},
    {"Pinsir", Pokemon::Pinsir},
    {"Piplup", Pokemon::Piplup},
    {"Plusle", Pokemon::Plusle},
    {"Politoed", Pokemon::Politoed},
    {"Poliwag", Pokemon::Poliwag},
    {"Poliwhirl", Pokemon::Poliwhirl},
    {"Poliwrath", Pokemon::Poliwrath},
    {"Ponyta", Pokemon::Ponyta},
    {"Poochyena", Pokemon::Poochyena},
    {"Porygon", Pokemon::Porygon},
    {"Porygon-Z", Pokemon::PorygonZ},
    {"Porygon2", Pokemon::Porygon2},
    {"Primeape", Pokemon::Primeape},
    {"Prinplup", Pokemon::Prinplup},
    {"Probopass", Pokemon::Probopass},
    {"Psyduck", Pokemon::Psyduck},
    {"Pupitar", Pokemon::Pupitar},
    {"Purugly", Pokemon::Purugly},
    {"Quagsire", Pokemon::Quagsire},
    {"Quilava", Pokemon::Quilava},
    {"Qwilfish", Pokemon::Qwilfish},
    {"Raichu", Pokemon::Raichu},
    {"Raikou", Pokemon::Raikou},
    {"Ralts", Pokemon::Ralts},
    {"Rampardos", Pokemon::Rampardos},
    {"Rapidash", Pokemon::Rapidash},
    {"Raticate", Pokemon::Raticate},
    {"Rattata", Pokemon::Rattata},
    {"Rayquaza", Pokemon::Rayquaza},
    {"Regice", Pokemon::Regice},
    {"Regigigas", Pokemon::Regigigas},
    {"Regirock", Pokemon::Regirock},
    {"Registeel", Pokemon::Registeel},
    {"Relicanth", Pokemon::Relicanth},
    {"Remoraid", Pokemon::Remoraid},
    {"Rhydon", Pokemon::Rhydon},
    {"Rhyhorn", Pokemon::Rhyhorn},
    {"Rhyperior", Pokemon::Rhyperior},
    {"Riolu", Pokemon::Riolu},
    {"Roselia", Pokemon::Roselia},
    {"Roserade", Pokemon::Roserade},
    {"Rotom", Pokemon::Rotom},
    {"HeatRotom", Pokemon::HeatRotom},
    {"WashRotom", Pokemon::WashRotom},
    {"FrostRotom", Pokemon::FrostRotom},
    {"FanRotom", Pokemon::FanRotom},
    {"MowRotom", Pokemon::MowRotom},
    {"Sableye", Pokemon::Sableye},
    {"Salamence", Pokemon::Salamence},
    {"Sandshrew", Pokemon::Sandshrew},
    {"Sandslash", Pokemon::Sandslash},
    {"Sceptile", Pokemon::Sceptile},
    {"Scizor", Pokemon::Scizor},
    {"Scyther", Pokemon::Scyther},
    {"Seadra", Pokemon::Seadra},
    {"Seaking", Pokemon::Seaking},
    {"Sealeo", Pokemon::Sealeo},
    {"Seedot", Pokemon::Seedot},
    {"Seel", Pokemon::Seel},
    {"Sentret", Pokemon::Sentret},
    {"Seviper", Pokemon::Seviper},
    {"Sharpedo", Pokemon::Sharpedo},
    {"SkyShaymin", Pokemon::SkyShaymin},
    {"LandShaymin", Pokemon::LandShaymin},
    {"Shedinja", Pokemon::Shedinja},
    {"Shelgon", Pokemon::Shelgon},
    {"Shellder", Pokemon::Shellder},
    {"Shellos", Pokemon::Shellos},
    {"Shieldon", Pokemon::Shieldon},
    {"Shiftry", Pokemon::Shiftry},
    {"Shinx", Pokemon::Shinx},
    {"Shroomish", Pokemon::Shroomish},
    {"Shuckle", Pokemon::Shuckle},
    {"Shuppet", Pokemon::Shuppet},
    {"Silcoon", Pokemon::Silcoon},
    {"Skarmory", Pokemon::Skarmory},
    {"Skiploom", Pokemon::Skiploom},
    {"Skitty", Pokemon::Skitty},
    {"Skorupi", Pokemon::Skorupi},
    {"Skuntank", Pokemon::Skuntank},
    {"Slaking", Pokemon::Slaking},
    {"Slakoth", Pokemon::Slakoth},
    {"Slowbro", Pokemon::Slowbro},
    {"Slowking", Pokemon::Slowking},
    {"Slowpoke", Pokemon::Slowpoke},
    {"Slugma", Pokemon::Slugma},
    {"Smeargle", Pokemon::Smeargle},
    {"Smoochum", Pokemon::Smoochum},
    {"Sneasel", Pokemon::Sneasel},
    {"Snorlax", Pokemon::Snorlax},
    {"Snorunt", Pokemon::Snorunt},
    {"Snover", Pokemon::Snover},
    {"Snubbull", Pokemon::Snubbull},
    {"Solrock", Pokemon::Solrock},
    {"Spearow", Pokemon::Spearow},
    {"Spheal", Pokemon::Spheal},
    {"Spinarak", Pokemon::Spinarak},
    {"Spinda", Pokemon::Spinda},
    {"Spiritomb", Pokemon::Spiritomb},
    {"Spoink", Pokemon::Spoink},
    {"Squirtle", Pokemon::Squirtle},
    {"Stantler", Pokemon::Stantler},
    {"Staraptor", Pokemon::Staraptor},
    {"Staravia", Pokemon::Staravia},
    {"Starly", Pokemon::Starly},
    {"Starmie", Pokemon::Starmie},
    {"Staryu", Pokemon::Staryu},
    {"Steelix", Pokemon::Steelix},
    {"Stunky", Pokemon::Stunky},
    {"Sudowoodo", Pokemon::Sudowoodo},
    {"Suicune", Pokemon::Suicune},
    {"Sunflora", Pokemon::Sunflora},
    {"Sunkern", Pokemon::Sunkern},
    {"Surskit", Pokemon::Surskit},
    {"Swablu", Pokemon::Swablu},
    {"Swalot", Pokemon::Swalot},
    {"Swampert", Pokemon::Swampert},
    {"Swellow", Pokemon::Swellow},
    {"Swinub", Pokemon::Swinub},
    {"Taillow", Pokemon::Taillow},
    {"Tangela", Pokemon::Tangela},
    {"Tangrowth", Pokemon::Tangrowth},
    {"Tauros", Pokemon::Tauros},
    {"Teddiursa", Pokemon::Teddiursa},
    {"Tentacool", Pokemon::Tentacool},
    {"Tentacruel", Pokemon::Tentacruel},
    {"Togekiss", Pokemon::Togekiss},
    {"Togepi", Pokemon::Togepi},
    {"Togetic", Pokemon::Togetic},
    {"Torchic", Pokemon::Torchic},
    {"Torkoal", Pokemon::Torkoal},
    {"Torterra", Pokemon::Torterra},
    {"Totodile", Pokemon::Totodile},
    {"Toxicroak", Pokemon::Toxicroak},
    {"Trapinch", Pokemon::Trapinch},
    {"Treecko", Pokemon::Treecko},
    {"Tropius", Pokemon::Tropius},
    {"Turtwig", Pokemon::Turtwig},
    {"Typhlosion", Pokemon::Typhlosion},
    {"Tyranitar", Pokemon::Tyranitar},
    {"Tyrogue", Pokemon::Tyrogue},
    {"Umbreon", Pokemon::Umbreon},
    {"Unown", Pokemon::Unown},
    {"Ursaring", Pokemon::Ursaring},
    {"Uxie", Pokemon::Uxie},
    {"Vaporeon", Pokemon::Vaporeon},
    {"Venomoth", Pokemon::Venomoth},
    {"Venonat", Pokemon::Venonat},
    {"Venusaur", Pokemon::Venusaur},
    {"Vespiquen", Pokemon::Vespiquen},
    {"Vibrava", Pokemon::Vibrava},
    {"Victreebel", Pokemon::Victreebel},
    {"Vigoroth", Pokemon::Vigoroth},
    {"Vileplume", Pokemon::Vileplume},
    {"Volbeat", Pokemon::Volbeat},
    {"Voltorb", Pokemon::Voltorb},
    {"Vulpix", Pokemon::Vulpix},
    {"Wailmer", Pokemon::Wailmer},
    {"Wailord", Pokemon::Wailord},
    {"Walrein", Pokemon::Walrein},
    {"Wartortle", Pokemon::Wartortle},
    {"Weavile", Pokemon::Weavile},
    {"Weedle", Pokemon::Weedle},
    {"Weepinbell", Pokemon::Weepinbell},
    {"Weezing", Pokemon::Weezing},
    {"Whiscash", Pokemon::Whiscash},
    {"Whismur", Pokemon::Whismur},
    {"Wigglytuff", Pokemon::Wigglytuff},
    {"Wingull", Pokemon::Wingull},
    {"Wobbuffet", Pokemon::Wobbuffet},
    {"Wooper", Pokemon::Wooper},
    {"WormadamP", Pokemon::WormadamP},
    {"WormadamS", Pokemon::WormadamS},
    {"WormadamT", Pokemon::WormadamT},
    {"Wurmple", Pokemon::Wurmple},
    {"Wynaut", Pokemon::Wynaut},
    {"Xatu", Pokemon::Xatu},
    {"Yanma", Pokemon::Yanma},
    {"Yanmega", Pokemon::Yanmega},
    {"Zangoose", Pokemon::Zangoose},
    {"Zapdos", Pokemon::Zapdos},
    {"Zigzagoon", Pokemon::Zigzagoon},
    {"Zubat", Pokemon::Zubat},
};

enum class Ability {
    Adaptability,
    Aftermath,
    AirLock,
    AngerPoint,
    Anticipation,
    ArenaTrap,
    BadDreams,
    BattleArmor,
    Blaze,
    Chlorophyll,
    ClearBody,
    CloudNine,
    ColorChange,
    Compoundeyes,
    CuteCharm,
    Damp,
    Download,
    Drizzle,
    Drought,
    DrySkin,
    EarlyBird,
    EffectSpore,
    Filter,
    FlameBody,
    FlashFire,
    FlowerGift,
    Forecast,
    Forewarn,
    Frisk,
    Gluttony,
    Guts,
    Heatproof,
    HoneyGather,
    HugePower,
    Hustle,
    Hydration,
    HyperCutter,
    IceBody,
    Illuminate,
    Immunity,
    InnerFocus,
    Insomnia,
    Intimidate,
    IronFist,
    KeenEye,
    Klutz,
    LeafGuard,
    Levitate,
    LightningRod,
    Limber,
    LiquidOoze,
    MagicGuard,
    MagmaArmor,
    MagnetPull,
    MarvelScale,
    Minus,
    MoldBreaker,
    MotorDrive,
    Multitype,
    NaturalCure,
    NoGuard,
    Normalize,
    Oblivious,
    Overgrow,
    OwnTempo,
    Pickup,
    Plus,
    PoisonHeal,
    PoisonPoint,
    Pressure,
    PurePower,
    QuickFeet,
    RainDish,
    Reckless,
    Rivalry,
    RockHead,
    RoughSkin,
    RunAway,
    SandStream,
    SandVeil,
    Scrappy,
    SereneGrace,
    ShadowTag,
    ShedSkin,
    ShellArmor,
    ShieldDust,
    Simple,
    SkillLink,
    SlowStart,
    Sniper,
    SnowCloak,
    SnowWarning,
    SolarPower,
    SolidRock,
    Soundproof,
    SpeedBoost,
    Stall,
    Static,
    Steadfast,
    Stench,
    StickyHold,
    StormDrain,
    Sturdy,
    SuctionCups,
    SuperLuck,
    Swarm,
    SwiftSwim,
    Synchronize,
    TangledFeet,
    Technician,
    ThickFat,
    TintedLens,
    Torrent,
    Trace,
    Truant,
    Unaware,
    Unburden,
    VitalSpirit,
    VoltAbsorb,
    WaterAbsorb,
    WaterVeil,
    WhiteSmoke,
    WonderGuard
};

static std::unordered_map<Pokemon, std::vector<Ability>> ABILITY_MAP = {
    {Pokemon::Abomasnow, {Ability::SnowWarning}},
    {Pokemon::Abra, {Ability::InnerFocus, Ability::Synchronize}},
    {Pokemon::Absol, {Ability::Pressure, Ability::SuperLuck}},
    {Pokemon::Aerodactyl, {Ability::Pressure, Ability::RockHead}},
    {Pokemon::Aggron, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Aipom, {Ability::Pickup, Ability::RunAway}},
    {Pokemon::Alakazam, {Ability::InnerFocus, Ability::Synchronize}},
    {Pokemon::Altaria, {Ability::NaturalCure}},
    {Pokemon::Ambipom, {Ability::Pickup, Ability::Technician}},
    {Pokemon::Ampharos, {Ability::Static}},
    {Pokemon::Anorith, {Ability::BattleArmor}},
    {Pokemon::Arbok, {Ability::Intimidate, Ability::ShedSkin}},
    {Pokemon::Arcanine, {Ability::FlashFire, Ability::Intimidate}},
    {Pokemon::Arceus, {Ability::Multitype}},
    {Pokemon::Ariados, {Ability::Insomnia, Ability::Swarm}},
    {Pokemon::Armaldo, {Ability::BattleArmor}},
    {Pokemon::Aron, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Articuno, {Ability::Pressure}},
    {Pokemon::Azelf, {Ability::Levitate}},
    {Pokemon::Azumarill, {Ability::HugePower, Ability::ThickFat}},
    {Pokemon::Azurill, {Ability::HugePower, Ability::ThickFat}},
    {Pokemon::Bagon, {Ability::RockHead}},
    {Pokemon::Baltoy, {Ability::Levitate}},
    {Pokemon::Banette, {Ability::Frisk, Ability::Insomnia}},
    {Pokemon::Barboach, {Ability::Anticipation, Ability::Oblivious}},
    {Pokemon::Bastiodon, {Ability::Sturdy}},
    {Pokemon::Bayleef, {Ability::Overgrow}},
    {Pokemon::Beautifly, {Ability::Swarm}},
    {Pokemon::Beedrill, {Ability::Swarm}},
    {Pokemon::Beldum, {Ability::ClearBody}},
    {Pokemon::Bellossom, {Ability::Chlorophyll}},
    {Pokemon::Bellsprout, {Ability::Chlorophyll}},
    {Pokemon::Bibarel, {Ability::Simple, Ability::Unaware}},
    {Pokemon::Bidoof, {Ability::Simple, Ability::Unaware}},
    {Pokemon::Blastoise, {Ability::Torrent}},
    {Pokemon::Blaziken, {Ability::Blaze}},
    {Pokemon::Blissey, {Ability::NaturalCure, Ability::SereneGrace}},
    {Pokemon::Bonsly, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Breloom, {Ability::EffectSpore, Ability::PoisonHeal}},
    {Pokemon::Bronzong, {Ability::Heatproof, Ability::Levitate}},
    {Pokemon::Bronzor, {Ability::Heatproof, Ability::Levitate}},
    {Pokemon::Budew, {Ability::NaturalCure, Ability::PoisonPoint}},
    {Pokemon::Buizel, {Ability::SwiftSwim}},
    {Pokemon::Bulbasaur, {Ability::Overgrow}},
    {Pokemon::Buneary, {Ability::Klutz, Ability::RunAway}},
    {Pokemon::Burmy, {Ability::ShedSkin}},
    {Pokemon::Butterfree, {Ability::Compoundeyes}},
    {Pokemon::Cacnea, {Ability::SandVeil}},
    {Pokemon::Cacturne, {Ability::SandVeil}},
    {Pokemon::Camerupt, {Ability::MagmaArmor, Ability::SolidRock}},
    {Pokemon::Carnivine, {Ability::Levitate}},
    {Pokemon::Carvanha, {Ability::RoughSkin}},
    {Pokemon::Cascoon, {Ability::ShedSkin}},
    {Pokemon::Castform, {Ability::Forecast}},
    {Pokemon::Caterpie, {Ability::ShieldDust}},
    {Pokemon::Celebi, {Ability::NaturalCure}},
    {Pokemon::Chansey, {Ability::NaturalCure, Ability::SereneGrace}},
    {Pokemon::Charizard, {Ability::Blaze}},
    {Pokemon::Charmander, {Ability::Blaze}},
    {Pokemon::Charmeleon, {Ability::Blaze}},
    {Pokemon::Chatot, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Cherrim, {Ability::FlowerGift}},
    {Pokemon::Cherubi, {Ability::Chlorophyll}},
    {Pokemon::Chikorita, {Ability::Overgrow}},
    {Pokemon::Chimchar, {Ability::Blaze}},
    {Pokemon::Chimecho, {Ability::Levitate}},
    {Pokemon::Chinchou, {Ability::Illuminate, Ability::VoltAbsorb}},
    {Pokemon::Chingling, {Ability::Levitate}},
    {Pokemon::Clamperl, {Ability::ShellArmor}},
    {Pokemon::Claydol, {Ability::Levitate}},
    {Pokemon::Clefable, {Ability::CuteCharm, Ability::MagicGuard}},
    {Pokemon::Clefairy, {Ability::CuteCharm, Ability::MagicGuard}},
    {Pokemon::Cleffa, {Ability::CuteCharm, Ability::MagicGuard}},
    {Pokemon::Cloyster, {Ability::ShellArmor, Ability::SkillLink}},
    {Pokemon::Combee, {Ability::HoneyGather}},
    {Pokemon::Combusken, {Ability::Blaze}},
    {Pokemon::Corphish, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Corsola, {Ability::Hustle, Ability::NaturalCure}},
    {Pokemon::Cradily, {Ability::SuctionCups}},
    {Pokemon::Cranidos, {Ability::MoldBreaker}},
    {Pokemon::Crawdaunt, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Cresselia, {Ability::Levitate}},
    {Pokemon::Croagunk, {Ability::Anticipation, Ability::DrySkin}},
    {Pokemon::Crobat, {Ability::InnerFocus}},
    {Pokemon::Croconaw, {Ability::Torrent}},
    {Pokemon::Cubone, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Cyndaquil, {Ability::Blaze}},
    {Pokemon::Darkrai, {Ability::BadDreams}},
    {Pokemon::Delcatty, {Ability::CuteCharm, Ability::Normalize}},
    {Pokemon::Delibird, {Ability::Hustle, Ability::VitalSpirit}},
    {Pokemon::NormalDeoxys, {Ability::Pressure}},
    {Pokemon::AttackDeoxys, {Ability::Pressure}},
    {Pokemon::DefenseDeoxys, {Ability::Pressure}},
    {Pokemon::SpeedDeoxys, {Ability::Pressure}},
    {Pokemon::Dewgong, {Ability::Hydration, Ability::ThickFat}},
    {Pokemon::Dialga, {Ability::Pressure}},
    {Pokemon::Diglett, {Ability::ArenaTrap, Ability::SandVeil}},
    {Pokemon::Ditto, {Ability::Limber}},
    {Pokemon::Dodrio, {Ability::EarlyBird, Ability::RunAway}},
    {Pokemon::Doduo, {Ability::EarlyBird, Ability::RunAway}},
    {Pokemon::Donphan, {Ability::Sturdy}},
    {Pokemon::Dragonair, {Ability::ShedSkin}},
    {Pokemon::Dragonite, {Ability::InnerFocus}},
    {Pokemon::Drapion, {Ability::BattleArmor, Ability::Sniper}},
    {Pokemon::Dratini, {Ability::ShedSkin}},
    {Pokemon::Drifblim, {Ability::Aftermath, Ability::Unburden}},
    {Pokemon::Drifloon, {Ability::Aftermath, Ability::Unburden}},
    {Pokemon::Drowzee, {Ability::Forewarn, Ability::Insomnia}},
    {Pokemon::Dugtrio, {Ability::ArenaTrap, Ability::SandVeil}},
    {Pokemon::Dunsparce, {Ability::RunAway, Ability::SereneGrace}},
    {Pokemon::Dusclops, {Ability::Pressure}},
    {Pokemon::Dusknoir, {Ability::Pressure}},
    {Pokemon::Duskull, {Ability::Levitate}},
    {Pokemon::Dustox, {Ability::ShieldDust}},
    {Pokemon::Eevee, {Ability::Adaptability, Ability::RunAway}},
    {Pokemon::Ekans, {Ability::Intimidate, Ability::ShedSkin}},
    {Pokemon::Electabuzz, {Ability::Static}},
    {Pokemon::Electivire, {Ability::MotorDrive}},
    {Pokemon::Electrike, {Ability::LightningRod, Ability::Static}},
    {Pokemon::Electrode, {Ability::Soundproof, Ability::Static}},
    {Pokemon::Elekid, {Ability::Static}},
    {Pokemon::Empoleon, {Ability::Torrent}},
    {Pokemon::Entei, {Ability::Pressure}},
    {Pokemon::Espeon, {Ability::Synchronize}},
    {Pokemon::Exeggcute, {Ability::Chlorophyll}},
    {Pokemon::Exeggutor, {Ability::Chlorophyll}},
    {Pokemon::Exploud, {Ability::Soundproof}},
    {Pokemon::Farfetchd, {Ability::InnerFocus, Ability::KeenEye}},
    {Pokemon::Fearow, {Ability::KeenEye}},
    {Pokemon::Feebas, {Ability::SwiftSwim}},
    {Pokemon::Feraligatr, {Ability::Torrent}},
    {Pokemon::Finneon, {Ability::StormDrain, Ability::SwiftSwim}},
    {Pokemon::Flaaffy, {Ability::Static}},
    {Pokemon::Flareon, {Ability::FlashFire}},
    {Pokemon::Floatzel, {Ability::SwiftSwim}},
    {Pokemon::Flygon, {Ability::Levitate}},
    {Pokemon::Forretress, {Ability::Sturdy}},
    {Pokemon::Froslass, {Ability::SnowCloak}},
    {Pokemon::Furret, {Ability::KeenEye, Ability::RunAway}},
    {Pokemon::Gabite, {Ability::SandVeil}},
    {Pokemon::Gallade, {Ability::Steadfast}},
    {Pokemon::Garchomp, {Ability::SandVeil}},
    {Pokemon::Gardevoir, {Ability::Synchronize, Ability::Trace}},
    {Pokemon::Gastly, {Ability::Levitate}},
    {Pokemon::Gastrodon, {Ability::StickyHold, Ability::StormDrain}},
    {Pokemon::Gengar, {Ability::Levitate}},
    {Pokemon::Geodude, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Gible, {Ability::SandVeil}},
    {Pokemon::Girafarig, {Ability::EarlyBird, Ability::InnerFocus}},
    {Pokemon::AlteredGiratina, {Ability::Pressure}},
    {Pokemon::OriginGiratina, {Ability::Levitate}},
    {Pokemon::Glaceon, {Ability::SnowCloak}},
    {Pokemon::Glalie, {Ability::IceBody, Ability::InnerFocus}},
    {Pokemon::Glameow, {Ability::Limber, Ability::OwnTempo}},
    {Pokemon::Gligar, {Ability::HyperCutter, Ability::SandVeil}},
    {Pokemon::Gliscor, {Ability::HyperCutter, Ability::SandVeil}},
    {Pokemon::Gloom, {Ability::Chlorophyll}},
    {Pokemon::Golbat, {Ability::InnerFocus}},
    {Pokemon::Goldeen, {Ability::SwiftSwim, Ability::WaterVeil}},
    {Pokemon::Golduck, {Ability::CloudNine, Ability::Damp}},
    {Pokemon::Golem, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Gorebyss, {Ability::SwiftSwim}},
    {Pokemon::Granbull, {Ability::Intimidate, Ability::QuickFeet}},
    {Pokemon::Graveler, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Grimer, {Ability::Stench, Ability::StickyHold}},
    {Pokemon::Grotle, {Ability::Overgrow}},
    {Pokemon::Groudon, {Ability::Drought}},
    {Pokemon::Grovyle, {Ability::Overgrow}},
    {Pokemon::Growlithe, {Ability::FlashFire, Ability::Intimidate}},
    {Pokemon::Grumpig, {Ability::OwnTempo, Ability::ThickFat}},
    {Pokemon::Gulpin, {Ability::LiquidOoze, Ability::StickyHold}},
    {Pokemon::Gyarados, {Ability::Intimidate}},
    {Pokemon::Happiny, {Ability::NaturalCure, Ability::SereneGrace}},
    {Pokemon::Hariyama, {Ability::Guts, Ability::ThickFat}},
    {Pokemon::Haunter, {Ability::Levitate}},
    {Pokemon::Heatran, {Ability::FlashFire}},
    {Pokemon::Heracross, {Ability::Guts, Ability::Swarm}},
    {Pokemon::Hippopotas, {Ability::SandStream}},
    {Pokemon::Hippowdon, {Ability::SandStream}},
    {Pokemon::Hitmonchan, {Ability::IronFist, Ability::KeenEye}},
    {Pokemon::Hitmonlee, {Ability::Limber, Ability::Reckless}},
    {Pokemon::Hitmontop, {Ability::Intimidate, Ability::Technician}},
    {Pokemon::HoOh, {Ability::Pressure}},
    {Pokemon::Honchkrow, {Ability::Insomnia, Ability::SuperLuck}},
    {Pokemon::Hoothoot, {Ability::Insomnia, Ability::KeenEye}},
    {Pokemon::Hoppip, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Horsea, {Ability::Sniper, Ability::SwiftSwim}},
    {Pokemon::Houndoom, {Ability::EarlyBird, Ability::FlashFire}},
    {Pokemon::Houndour, {Ability::EarlyBird, Ability::FlashFire}},
    {Pokemon::Huntail, {Ability::SwiftSwim}},
    {Pokemon::Hypno, {Ability::Forewarn, Ability::Insomnia}},
    {Pokemon::Igglybuff, {Ability::CuteCharm}},
    {Pokemon::Illumise, {Ability::Oblivious, Ability::TintedLens}},
    {Pokemon::Infernape, {Ability::Blaze}},
    {Pokemon::Ivysaur, {Ability::Overgrow}},
    {Pokemon::Jigglypuff, {Ability::CuteCharm}},
    {Pokemon::Jirachi, {Ability::SereneGrace}},
    {Pokemon::Jolteon, {Ability::VoltAbsorb}},
    {Pokemon::Jumpluff, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Jynx, {Ability::Forewarn, Ability::Oblivious}},
    {Pokemon::Kabuto, {Ability::BattleArmor, Ability::SwiftSwim}},
    {Pokemon::Kabutops, {Ability::BattleArmor, Ability::SwiftSwim}},
    {Pokemon::Kadabra, {Ability::InnerFocus, Ability::Synchronize}},
    {Pokemon::Kakuna, {Ability::ShedSkin}},
    {Pokemon::Kangaskhan, {Ability::EarlyBird, Ability::Scrappy}},
    {Pokemon::Kecleon, {Ability::ColorChange}},
    {Pokemon::Kingdra, {Ability::Sniper, Ability::SwiftSwim}},
    {Pokemon::Kingler, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Kirlia, {Ability::Synchronize, Ability::Trace}},
    {Pokemon::Koffing, {Ability::Levitate}},
    {Pokemon::Krabby, {Ability::HyperCutter, Ability::ShellArmor}},
    {Pokemon::Kricketot, {Ability::ShedSkin}},
    {Pokemon::Kricketune, {Ability::Swarm}},
    {Pokemon::Kyogre, {Ability::Drizzle}},
    {Pokemon::Lairon, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Lanturn, {Ability::Illuminate, Ability::VoltAbsorb}},
    {Pokemon::Lapras, {Ability::ShellArmor, Ability::WaterAbsorb}},
    {Pokemon::Larvitar, {Ability::Guts}},
    {Pokemon::Latias, {Ability::Levitate}},
    {Pokemon::Latios, {Ability::Levitate}},
    {Pokemon::Leafeon, {Ability::LeafGuard}},
    {Pokemon::Ledian, {Ability::EarlyBird, Ability::Swarm}},
    {Pokemon::Ledyba, {Ability::EarlyBird, Ability::Swarm}},
    {Pokemon::Lickilicky, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Lickitung, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Lileep, {Ability::SuctionCups}},
    {Pokemon::Linoone, {Ability::Gluttony, Ability::Pickup}},
    {Pokemon::Lombre, {Ability::RainDish, Ability::SwiftSwim}},
    {Pokemon::Lopunny, {Ability::CuteCharm, Ability::Klutz}},
    {Pokemon::Lotad, {Ability::RainDish, Ability::SwiftSwim}},
    {Pokemon::Loudred, {Ability::Soundproof}},
    {Pokemon::Lucario, {Ability::InnerFocus, Ability::Steadfast}},
    {Pokemon::Ludicolo, {Ability::RainDish, Ability::SwiftSwim}},
    {Pokemon::Lugia, {Ability::Pressure}},
    {Pokemon::Lumineon, {Ability::StormDrain, Ability::SwiftSwim}},
    {Pokemon::Lunatone, {Ability::Levitate}},
    {Pokemon::Luvdisc, {Ability::SwiftSwim}},
    {Pokemon::Luxio, {Ability::Intimidate, Ability::Rivalry}},
    {Pokemon::Luxray, {Ability::Intimidate, Ability::Rivalry}},
    {Pokemon::Machamp, {Ability::Guts, Ability::NoGuard}},
    {Pokemon::Machoke, {Ability::Guts, Ability::NoGuard}},
    {Pokemon::Machop, {Ability::Guts, Ability::NoGuard}},
    {Pokemon::Magby, {Ability::FlameBody}},
    {Pokemon::Magcargo, {Ability::FlameBody, Ability::MagmaArmor}},
    {Pokemon::Magikarp, {Ability::SwiftSwim}},
    {Pokemon::Magmar, {Ability::FlameBody}},
    {Pokemon::Magmortar, {Ability::FlameBody}},
    {Pokemon::Magnemite, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Magneton, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Magnezone, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Makuhita, {Ability::Guts, Ability::ThickFat}},
    {Pokemon::Mamoswine, {Ability::Oblivious, Ability::SnowCloak}},
    {Pokemon::Manaphy, {Ability::Hydration}},
    {Pokemon::Manectric, {Ability::LightningRod, Ability::Static}},
    {Pokemon::Mankey, {Ability::AngerPoint, Ability::VitalSpirit}},
    {Pokemon::Mantine, {Ability::SwiftSwim, Ability::WaterAbsorb}},
    {Pokemon::Mantyke, {Ability::SwiftSwim, Ability::WaterAbsorb}},
    {Pokemon::Mareep, {Ability::Static}},
    {Pokemon::Marill, {Ability::HugePower, Ability::ThickFat}},
    {Pokemon::Marowak, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Marshtomp, {Ability::Torrent}},
    {Pokemon::Masquerain, {Ability::Intimidate}},
    {Pokemon::Mawile, {Ability::HyperCutter, Ability::Intimidate}},
    {Pokemon::Medicham, {Ability::PurePower}},
    {Pokemon::Meditite, {Ability::PurePower}},
    {Pokemon::Meganium, {Ability::Overgrow}},
    {Pokemon::Meowth, {Ability::Pickup, Ability::Technician}},
    {Pokemon::Mesprit, {Ability::Levitate}},
    {Pokemon::Metagross, {Ability::ClearBody}},
    {Pokemon::Metang, {Ability::ClearBody}},
    {Pokemon::Metapod, {Ability::ShedSkin}},
    {Pokemon::Mew, {Ability::Synchronize}},
    {Pokemon::Mewtwo, {Ability::Pressure}},
    {Pokemon::Mightyena, {Ability::Intimidate, Ability::QuickFeet}},
    {Pokemon::Milotic, {Ability::MarvelScale}},
    {Pokemon::Miltank, {Ability::Scrappy, Ability::ThickFat}},
    {Pokemon::MimeJr, {Ability::Filter, Ability::Soundproof}},
    {Pokemon::Minun, {Ability::Minus}},
    {Pokemon::Misdreavus, {Ability::Levitate}},
    {Pokemon::Mismagius, {Ability::Levitate}},
    {Pokemon::Moltres, {Ability::Pressure}},
    {Pokemon::Monferno, {Ability::Blaze}},
    {Pokemon::Mothim, {Ability::Swarm}},
    {Pokemon::MrMime, {Ability::Filter, Ability::Soundproof}},
    {Pokemon::Mudkip, {Ability::Torrent}},
    {Pokemon::Muk, {Ability::Stench, Ability::StickyHold}},
    {Pokemon::Munchlax, {Ability::Pickup, Ability::ThickFat}},
    {Pokemon::Murkrow, {Ability::Insomnia, Ability::SuperLuck}},
    {Pokemon::Natu, {Ability::EarlyBird, Ability::Synchronize}},
    {Pokemon::Nidoking, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nidoqueen, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::NidoranF, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::NidoranM, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nidorina, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nidorino, {Ability::PoisonPoint, Ability::Rivalry}},
    {Pokemon::Nincada, {Ability::Compoundeyes}},
    {Pokemon::Ninetales, {Ability::FlashFire}},
    {Pokemon::Ninjask, {Ability::SpeedBoost}},
    {Pokemon::Noctowl, {Ability::Insomnia, Ability::KeenEye}},
    {Pokemon::Nosepass, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Numel, {Ability::Oblivious, Ability::Simple}},
    {Pokemon::Nuzleaf, {Ability::Chlorophyll, Ability::EarlyBird}},
    {Pokemon::Octillery, {Ability::Sniper, Ability::SuctionCups}},
    {Pokemon::Oddish, {Ability::Chlorophyll}},
    {Pokemon::Omanyte, {Ability::ShellArmor, Ability::SwiftSwim}},
    {Pokemon::Omastar, {Ability::ShellArmor, Ability::SwiftSwim}},
    {Pokemon::Onix, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Pachirisu, {Ability::Pickup, Ability::RunAway}},
    {Pokemon::Palkia, {Ability::Pressure}},
    {Pokemon::Paras, {Ability::DrySkin, Ability::EffectSpore}},
    {Pokemon::Parasect, {Ability::DrySkin, Ability::EffectSpore}},
    {Pokemon::Pelipper, {Ability::KeenEye}},
    {Pokemon::Persian, {Ability::Limber, Ability::Technician}},
    {Pokemon::Phanpy, {Ability::Pickup}},
    {Pokemon::Phione, {Ability::Hydration}},
    {Pokemon::Pichu, {Ability::Static}},
    {Pokemon::Pidgeot, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Pidgeotto, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Pidgey, {Ability::KeenEye, Ability::TangledFeet}},
    {Pokemon::Pikachu, {Ability::Static}},
    {Pokemon::Piloswine, {Ability::Oblivious, Ability::SnowCloak}},
    {Pokemon::Pineco, {Ability::Sturdy}},
    {Pokemon::Pinsir, {Ability::HyperCutter, Ability::MoldBreaker}},
    {Pokemon::Piplup, {Ability::Torrent}},
    {Pokemon::Plusle, {Ability::Plus}},
    {Pokemon::Politoed, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Poliwag, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Poliwhirl, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Poliwrath, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Ponyta, {Ability::FlashFire, Ability::RunAway}},
    {Pokemon::Poochyena, {Ability::QuickFeet, Ability::RunAway}},
    {Pokemon::Porygon, {Ability::Download, Ability::Trace}},
    {Pokemon::PorygonZ, {Ability::Adaptability, Ability::Download}},
    {Pokemon::Porygon2, {Ability::Download, Ability::Trace}},
    {Pokemon::Primeape, {Ability::AngerPoint, Ability::VitalSpirit}},
    {Pokemon::Prinplup, {Ability::Torrent}},
    {Pokemon::Probopass, {Ability::MagnetPull, Ability::Sturdy}},
    {Pokemon::Psyduck, {Ability::CloudNine, Ability::Damp}},
    {Pokemon::Pupitar, {Ability::ShedSkin}},
    {Pokemon::Purugly, {Ability::OwnTempo, Ability::ThickFat}},
    {Pokemon::Quagsire, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::Quilava, {Ability::Blaze}},
    {Pokemon::Qwilfish, {Ability::PoisonPoint, Ability::SwiftSwim}},
    {Pokemon::Raichu, {Ability::Static}},
    {Pokemon::Raikou, {Ability::Pressure}},
    {Pokemon::Ralts, {Ability::Synchronize, Ability::Trace}},
    {Pokemon::Rampardos, {Ability::MoldBreaker}},
    {Pokemon::Rapidash, {Ability::FlashFire, Ability::RunAway}},
    {Pokemon::Raticate, {Ability::Guts, Ability::RunAway}},
    {Pokemon::Rattata, {Ability::Guts, Ability::RunAway}},
    {Pokemon::Rayquaza, {Ability::AirLock}},
    {Pokemon::Regice, {Ability::ClearBody}},
    {Pokemon::Regigigas, {Ability::SlowStart}},
    {Pokemon::Regirock, {Ability::ClearBody}},
    {Pokemon::Registeel, {Ability::ClearBody}},
    {Pokemon::Relicanth, {Ability::RockHead, Ability::SwiftSwim}},
    {Pokemon::Remoraid, {Ability::Hustle, Ability::Sniper}},
    {Pokemon::Rhydon, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Rhyhorn, {Ability::LightningRod, Ability::RockHead}},
    {Pokemon::Rhyperior, {Ability::LightningRod, Ability::SolidRock}},
    {Pokemon::Riolu, {Ability::InnerFocus, Ability::Steadfast}},
    {Pokemon::Roselia, {Ability::NaturalCure, Ability::PoisonPoint}},
    {Pokemon::Roserade, {Ability::NaturalCure, Ability::PoisonPoint}},
    {Pokemon::Rotom, {Ability::Levitate}},
    {Pokemon::Sableye, {Ability::KeenEye, Ability::Stall}},
    {Pokemon::Salamence, {Ability::Intimidate}},
    {Pokemon::Sandshrew, {Ability::SandVeil}},
    {Pokemon::Sandslash, {Ability::SandVeil}},
    {Pokemon::Sceptile, {Ability::Overgrow}},
    {Pokemon::Scizor, {Ability::Swarm, Ability::Technician}},
    {Pokemon::Scyther, {Ability::Swarm, Ability::Technician}},
    {Pokemon::Seadra, {Ability::PoisonPoint, Ability::Sniper}},
    {Pokemon::Seaking, {Ability::SwiftSwim, Ability::WaterVeil}},
    {Pokemon::Sealeo, {Ability::IceBody, Ability::ThickFat}},
    {Pokemon::Seedot, {Ability::Chlorophyll, Ability::EarlyBird}},
    {Pokemon::Seel, {Ability::Hydration, Ability::ThickFat}},
    {Pokemon::Sentret, {Ability::KeenEye, Ability::RunAway}},
    {Pokemon::Seviper, {Ability::ShedSkin}},
    {Pokemon::Sharpedo, {Ability::RoughSkin}},
    {Pokemon::LandShaymin, {Ability::NaturalCure}},
    {Pokemon::SkyShaymin, {Ability::SereneGrace}},
    {Pokemon::Shedinja, {Ability::WonderGuard}},
    {Pokemon::Shelgon, {Ability::RockHead}},
    {Pokemon::Shellder, {Ability::ShellArmor, Ability::SkillLink}},
    {Pokemon::Shellos, {Ability::StickyHold, Ability::StormDrain}},
    {Pokemon::Shieldon, {Ability::Sturdy}},
    {Pokemon::Shiftry, {Ability::Chlorophyll, Ability::EarlyBird}},
    {Pokemon::Shinx, {Ability::Intimidate, Ability::Rivalry}},
    {Pokemon::Shroomish, {Ability::EffectSpore, Ability::PoisonHeal}},
    {Pokemon::Shuckle, {Ability::Gluttony, Ability::Sturdy}},
    {Pokemon::Shuppet, {Ability::Frisk, Ability::Insomnia}},
    {Pokemon::Silcoon, {Ability::ShedSkin}},
    {Pokemon::Skarmory, {Ability::KeenEye, Ability::Sturdy}},
    {Pokemon::Skiploom, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Skitty, {Ability::CuteCharm, Ability::Normalize}},
    {Pokemon::Skorupi, {Ability::BattleArmor, Ability::Sniper}},
    {Pokemon::Skuntank, {Ability::Aftermath, Ability::Stench}},
    {Pokemon::Slaking, {Ability::Truant}},
    {Pokemon::Slakoth, {Ability::Truant}},
    {Pokemon::Slowbro, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Slowking, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Slowpoke, {Ability::Oblivious, Ability::OwnTempo}},
    {Pokemon::Slugma, {Ability::FlameBody, Ability::MagmaArmor}},
    {Pokemon::Smeargle, {Ability::OwnTempo, Ability::Technician}},
    {Pokemon::Smoochum, {Ability::Forewarn, Ability::Oblivious}},
    {Pokemon::Sneasel, {Ability::InnerFocus, Ability::KeenEye}},
    {Pokemon::Snorlax, {Ability::Immunity, Ability::ThickFat}},
    {Pokemon::Snorunt, {Ability::IceBody, Ability::InnerFocus}},
    {Pokemon::Snover, {Ability::SnowWarning}},
    {Pokemon::Snubbull, {Ability::Intimidate, Ability::RunAway}},
    {Pokemon::Solrock, {Ability::Levitate}},
    {Pokemon::Spearow, {Ability::KeenEye}},
    {Pokemon::Spheal, {Ability::IceBody, Ability::ThickFat}},
    {Pokemon::Spinarak, {Ability::Insomnia, Ability::Swarm}},
    {Pokemon::Spinda, {Ability::OwnTempo, Ability::TangledFeet}},
    {Pokemon::Spiritomb, {Ability::Pressure}},
    {Pokemon::Spoink, {Ability::OwnTempo, Ability::ThickFat}},
    {Pokemon::Squirtle, {Ability::Torrent}},
    {Pokemon::Stantler, {Ability::Frisk, Ability::Intimidate}},
    {Pokemon::Staraptor, {Ability::Intimidate}},
    {Pokemon::Staravia, {Ability::Intimidate}},
    {Pokemon::Starly, {Ability::KeenEye}},
    {Pokemon::Starmie, {Ability::Illuminate, Ability::NaturalCure}},
    {Pokemon::Staryu, {Ability::Illuminate, Ability::NaturalCure}},
    {Pokemon::Steelix, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Stunky, {Ability::Aftermath, Ability::Stench}},
    {Pokemon::Sudowoodo, {Ability::RockHead, Ability::Sturdy}},
    {Pokemon::Suicune, {Ability::Pressure}},
    {Pokemon::Sunflora, {Ability::Chlorophyll, Ability::SolarPower}},
    {Pokemon::Sunkern, {Ability::Chlorophyll, Ability::SolarPower}},
    {Pokemon::Surskit, {Ability::SwiftSwim}},
    {Pokemon::Swablu, {Ability::NaturalCure}},
    {Pokemon::Swalot, {Ability::LiquidOoze, Ability::StickyHold}},
    {Pokemon::Swampert, {Ability::Torrent}},
    {Pokemon::Swellow, {Ability::Guts}},
    {Pokemon::Swinub, {Ability::Oblivious, Ability::SnowCloak}},
    {Pokemon::Taillow, {Ability::Guts}},
    {Pokemon::Tangela, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Tangrowth, {Ability::Chlorophyll, Ability::LeafGuard}},
    {Pokemon::Tauros, {Ability::AngerPoint, Ability::Intimidate}},
    {Pokemon::Teddiursa, {Ability::Pickup, Ability::QuickFeet}},
    {Pokemon::Tentacool, {Ability::ClearBody, Ability::LiquidOoze}},
    {Pokemon::Tentacruel, {Ability::ClearBody, Ability::LiquidOoze}},
    {Pokemon::Togekiss, {Ability::Hustle, Ability::SereneGrace}},
    {Pokemon::Togepi, {Ability::Hustle, Ability::SereneGrace}},
    {Pokemon::Togetic, {Ability::Hustle, Ability::SereneGrace}},
    {Pokemon::Torchic, {Ability::Blaze}},
    {Pokemon::Torkoal, {Ability::WhiteSmoke}},
    {Pokemon::Torterra, {Ability::Overgrow}},
    {Pokemon::Totodile, {Ability::Torrent}},
    {Pokemon::Toxicroak, {Ability::Anticipation, Ability::DrySkin}},
    {Pokemon::Trapinch, {Ability::ArenaTrap, Ability::HyperCutter}},
    {Pokemon::Treecko, {Ability::Overgrow}},
    {Pokemon::Tropius, {Ability::Chlorophyll, Ability::SolarPower}},
    {Pokemon::Turtwig, {Ability::Overgrow}},
    {Pokemon::Typhlosion, {Ability::Blaze}},
    {Pokemon::Tyranitar, {Ability::SandStream}},
    {Pokemon::Tyrogue, {Ability::Guts, Ability::Steadfast}},
    {Pokemon::Umbreon, {Ability::Synchronize}},
    {Pokemon::Unown, {Ability::Levitate}},
    {Pokemon::Ursaring, {Ability::Guts, Ability::QuickFeet}},
    {Pokemon::Uxie, {Ability::Levitate}},
    {Pokemon::Vaporeon, {Ability::WaterAbsorb}},
    {Pokemon::Venomoth, {Ability::ShieldDust, Ability::TintedLens}},
    {Pokemon::Venonat, {Ability::Compoundeyes, Ability::TintedLens}},
    {Pokemon::Venusaur, {Ability::Overgrow}},
    {Pokemon::Vespiquen, {Ability::Pressure}},
    {Pokemon::Vibrava, {Ability::Levitate}},
    {Pokemon::Victreebel, {Ability::Chlorophyll}},
    {Pokemon::Vigoroth, {Ability::VitalSpirit}},
    {Pokemon::Vileplume, {Ability::Chlorophyll}},
    {Pokemon::Volbeat, {Ability::Illuminate, Ability::Swarm}},
    {Pokemon::Voltorb, {Ability::Soundproof, Ability::Static}},
    {Pokemon::Vulpix, {Ability::FlashFire}},
    {Pokemon::Wailmer, {Ability::Oblivious, Ability::WaterVeil}},
    {Pokemon::Wailord, {Ability::Oblivious, Ability::WaterVeil}},
    {Pokemon::Walrein, {Ability::IceBody, Ability::ThickFat}},
    {Pokemon::Wartortle, {Ability::Torrent}},
    {Pokemon::Weavile, {Ability::Pressure}},
    {Pokemon::Weedle, {Ability::ShieldDust}},
    {Pokemon::Weepinbell, {Ability::Chlorophyll}},
    {Pokemon::Weezing, {Ability::Levitate}},
    {Pokemon::Whiscash, {Ability::Anticipation, Ability::Oblivious}},
    {Pokemon::Whismur, {Ability::Soundproof}},
    {Pokemon::Wigglytuff, {Ability::CuteCharm}},
    {Pokemon::Wingull, {Ability::KeenEye}},
    {Pokemon::Wobbuffet, {Ability::ShadowTag}},
    {Pokemon::Wooper, {Ability::Damp, Ability::WaterAbsorb}},
    {Pokemon::WormadamP, {Ability::Anticipation}},
    {Pokemon::WormadamS, {Ability::Anticipation}},
    {Pokemon::WormadamT, {Ability::Anticipation}},
    {Pokemon::Wurmple, {Ability::ShieldDust}},
    {Pokemon::Wynaut, {Ability::ShadowTag}},
    {Pokemon::Xatu, {Ability::EarlyBird, Ability::Synchronize}},
    {Pokemon::Yanma, {Ability::Compoundeyes, Ability::SpeedBoost}},
    {Pokemon::Yanmega, {Ability::SpeedBoost, Ability::TintedLens}},
    {Pokemon::Zangoose, {Ability::Immunity}},
    {Pokemon::Zapdos, {Ability::Pressure}},
    {Pokemon::Zigzagoon, {Ability::Gluttony, Ability::Pickup}},
    {Pokemon::Zubat, {Ability::InnerFocus}},
};

#endif //ABILITIES_H
