#ifndef ITEMS_H
#define ITEMS_H

#include <string>
#include <unordered_map>
#include <unordered_set>

enum class Item {
    ApicotBerry,
    BigRoot,
    BlackBelt,
    BlackGlasses,
    BlackSludge,
    BrightPowder,
    Charcoal,
    ChestoBerry,
    ChoiceBand,
    ChoiceScarf,
    ChoiceSpecs,
    DragonFang,
    ExpertBelt,
    FlameOrb,
    FocusBand,
    FocusSash,
    GanlonBerry,
    HardStone,
    HeatRock,
    IcyRock,
    IronBall,
    KingsRock,
    LaxIncense,
    Leftovers,
    LiechiBerry,
    LifeOrb,
    LightClay,
    LumBerry,
    Magnet,
    MetalCoat,
    Metronome,
    MiracleSeed,
    MuscleBand,
    MysticWater,
    NeverMeltIce,
    PersimBerry,
    PetayaBerry,
    PoisonBarb,
    PowerHerb,
    QuickClaw,
    QuickPowder,
    RazorClaw,
    RazorFang,
    RockyHelmet,
    SalacBerry,
    ScopeLens,
    SharpBeak,
    ShellBell,
    SilkScarf,
    SilverPowder,
    SitrusBerry,
    SmoothRock,
    SoftSand,
    SpellTag,
    Stick,
    StickyBarb,
    TwistedSpoon,
    WhiteHerb,
    WiseGlasses,
    ZoomLens,
    None
};

static const std::unordered_set BERRIES = {
    Item::ApicotBerry,
    Item::ChestoBerry,
    Item::GanlonBerry,
    Item::LiechiBerry,
    Item::LumBerry,
    Item::PersimBerry,
    Item::PetayaBerry,
    Item::SalacBerry,
    Item::SitrusBerry,
};

static const std::unordered_map<std::string, Item> STRING_TO_ITEM = {
    {"Apicot Berry", Item::ApicotBerry},
    {"Big Root", Item::BigRoot},
    {"Black Belt", Item::BlackBelt},
    {"BlackGlasses", Item::BlackGlasses},
    {"Black Sludge", Item::BlackSludge},
    {"BrightPowder", Item::BrightPowder},
    {"Charcoal", Item::Charcoal},
    {"Chesto Berry", Item::ChestoBerry},
    {"Choice Band", Item::ChoiceBand},
    {"Choice Scarf", Item::ChoiceScarf},
    {"Choice Specs", Item::ChoiceSpecs},
    {"Dragon Fang", Item::DragonFang},
    {"Expert Belt", Item::ExpertBelt},
    {"Flame Orb", Item::FlameOrb},
    {"Focus Band", Item::FocusBand},
    {"Focus Sash", Item::FocusSash},
    {"Ganlon Berry", Item::GanlonBerry},
    {"Hard Stone", Item::HardStone},
    {"Heat Rock", Item::HeatRock},
    {"Icy Rock", Item::IcyRock},
    {"Iron Ball", Item::IronBall},
    {"King's Rock", Item::KingsRock},
    {"Lax Incense", Item::LaxIncense},
    {"Leftovers", Item::Leftovers},
    {"Liechi Berry", Item::LiechiBerry},
    {"Life Orb", Item::LifeOrb},
    {"Light Clay", Item::LightClay},
    {"Lum Berry", Item::LumBerry},
    {"Magnet", Item::Magnet},
    {"Metal Coat", Item::MetalCoat},
    {"Metronome", Item::Metronome},
    {"Miracle Seed", Item::MiracleSeed},
    {"Muscle Band", Item::MuscleBand},
    {"Mystic Water", Item::MysticWater},
    {"NeverMeltIce", Item::NeverMeltIce},
    {"Persim Berry", Item::PersimBerry},
    {"Petaya Berry", Item::PetayaBerry},
    {"Poison Barb", Item::PoisonBarb},
    {"Power Herb", Item::PowerHerb},
    {"Quick Claw", Item::QuickClaw},
    {"Quick Powder", Item::QuickPowder},
    {"Razor Claw", Item::RazorClaw},
    {"Razor Fang", Item::RazorFang},
    {"Salac Berry", Item::SalacBerry},
    {"Scope Lens", Item::ScopeLens},
    {"Sharp Beak", Item::SharpBeak},
    {"Shell Bell", Item::ShellBell},
    {"Silk Scarf", Item::SilkScarf},
    {"SilverPowder", Item::SilverPowder},
    {"Sitrus Berry", Item::SitrusBerry},
    {"Smooth Rock", Item::SmoothRock},
    {"Soft Sand", Item::SoftSand},
    {"Spell Tag", Item::SpellTag},
    {"Stick", Item::Stick},
    {"Sticky Barb", Item::StickyBarb},
    {"TwistedSpoon", Item::TwistedSpoon},
    {"White Herb", Item::WhiteHerb},
    {"Wise Glasses", Item::WiseGlasses},
    {"Zoom Lens", Item::ZoomLens},
    {"", Item::None}
};

#endif //ITEMS_H
