#ifndef ATTACKS_H
#define ATTACKS_H

#include <bitset>
#include <ranges>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

enum class Move {
    Pound,
    KarateChop,
    DoubleSlap,
    CometPunch,
    MegaPunch,
    PayDay,
    FirePunch,
    IcePunch,
    ThunderPunch,
    Scratch,
    ViceGrip,
    Guillotine,
    RazorWind,
    SwordsDance,
    Cut,
    Gust,
    WingAttack,
    Whirlwind,
    Fly,
    Bind,
    Slam,
    VineWhip,
    Stomp,
    DoubleKick,
    MegaKick,
    JumpKick,
    RollingKick,
    SandAttack,
    Headbutt,
    HornAttack,
    FuryAttack,
    HornDrill,
    Tackle,
    BodySlam,
    Wrap,
    TakeDown,
    Thrash,
    DoubleEdge,
    TailWhip,
    PoisonSting,
    Twineedle,
    PinMissile,
    Leer,
    Bite,
    Growl,
    Roar,
    Sing,
    Supersonic,
    SonicBoom,
    Disable,
    Acid,
    Ember,
    Flamethrower,
    Mist,
    WaterGun,
    HydroPump,
    Surf,
    IceBeam,
    Blizzard,
    Psybeam,
    Bubblebeam,
    AuroraBeam,
    HyperBeam,
    Peck,
    DrillPeck,
    Submission,
    LowKick,
    Counter,
    SeismicToss,
    Strength,
    Absorb,
    MegaDrain,
    LeechSeed,
    Growth,
    RazorLeaf,
    SolarBeam,
    PoisonPowder,
    StunSpore,
    SleepPowder,
    PetalDance,
    StringShot,
    DragonRage,
    FireSpin,
    Thundershock,
    Thunderbolt,
    ThunderWave,
    Thunder,
    RockThrow,
    Earthquake,
    Fissure,
    Dig,
    Toxic,
    Confusion,
    Psychic,
    Hypnosis,
    Meditate,
    Agility,
    QuickAttack,
    Rage,
    Teleport,
    NightShade,
    Mimic,
    Screech,
    DoubleTeam,
    Recover,
    Harden,
    Minimize,
    Smokescreen,
    ConfuseRay,
    Withdraw,
    DefenseCurl,
    Barrier,
    LightScreen,
    Haze,
    Reflect,
    FocusEnergy,
    Bide,
    Metronome,
    MirrorMove,
    Selfdestruct,
    EggBomb,
    Lick,
    Smog,
    Sludge,
    BoneClub,
    FireBlast,
    Waterfall,
    Clamp,
    Swift,
    SkullBash,
    SpikeCannon,
    Constrict,
    Amnesia,
    Kinesis,
    Softboiled,
    HighJumpKick,
    Glare,
    DreamEater,
    PoisonGas,
    Barrage,
    LeechLife,
    LovelyKiss,
    SkyAttack,
    Transform,
    Bubble,
    DizzyPunch,
    Spore,
    Flash,
    Psywave,
    Splash,
    AcidArmor,
    Crabhammer,
    Explosion,
    FurySwipes,
    Bonemerang,
    Rest,
    RockSlide,
    HyperFang,
    Sharpen,
    Conversion,
    TriAttack,
    SuperFang,
    Slash,
    Substitute,
    Struggle,
    Sketch,
    TripleKick,
    Thief,
    SpiderWeb,
    MindReader,
    Nightmare,
    FlameWheel,
    Snore,
    Curse,
    Flail,
    Conversion2,
    Aeroblast,
    CottonSpore,
    Reversal,
    Spite,
    PowderSnow,
    Protect,
    MachPunch,
    ScaryFace,
    FaintAttack,
    SweetKiss,
    BellyDrum,
    SludgeBomb,
    MudSlap,
    Octazooka,
    Spikes,
    ZapCannon,
    Foresight,
    DestinyBond,
    PerishSong,
    IcyWind,
    Detect,
    BoneRush,
    LockOn,
    Outrage,
    Sandstorm,
    GigaDrain,
    Endure,
    Charm,
    Rollout,
    FalseSwipe,
    Swagger,
    MilkDrink,
    Spark,
    FuryCutter,
    SteelWing,
    MeanLook,
    Attract,
    SleepTalk,
    HealBell,
    Return,
    Present,
    Frustration,
    Safeguard,
    PainSplit,
    SacredFire,
    Magnitude,
    Dynamicpunch,
    Megahorn,
    DragonBreath,
    BatonPass,
    Encore,
    Pursuit,
    RapidSpin,
    SweetScent,
    IronTail,
    MetalClaw,
    VitalThrow,
    MorningSun,
    Synthesis,
    Moonlight,
    HiddenPower,
    CrossChop,
    Twister,
    RainDance,
    SunnyDay,
    Crunch,
    MirrorCoat,
    PsychUp,
    ExtremeSpeed,
    Ancientpower,
    ShadowBall,
    FutureSight,
    RockSmash,
    Whirlpool,
    BeatUp,
    FakeOut,
    Uproar,
    Stockpile,
    SpitUp,
    Swallow,
    HeatWave,
    Hail,
    Torment,
    Flatter,
    WillOWisp,
    Memento,
    Facade,
    FocusPunch,
    Smellingsalt,
    FollowMe,
    NaturePower,
    Charge,
    Taunt,
    HelpingHand,
    Trick,
    RolePlay,
    Wish,
    Assist,
    Ingrain,
    Superpower,
    MagicCoat,
    Recycle,
    Revenge,
    BrickBreak,
    Yawn,
    KnockOff,
    Endeavor,
    Eruption,
    SkillSwap,
    Imprison,
    Refresh,
    Grudge,
    Snatch,
    SecretPower,
    Dive,
    ArmThrust,
    Camouflage,
    TailGlow,
    LusterPurge,
    MistBall,
    Featherdance,
    TeeterDance,
    BlazeKick,
    MudSport,
    IceBall,
    NeedleArm,
    SlackOff,
    HyperVoice,
    PoisonFang,
    CrushClaw,
    BlastBurn,
    HydroCannon,
    MeteorMash,
    Astonish,
    WeatherBall,
    Aromatherapy,
    FakeTears,
    AirCutter,
    Overheat,
    OdorSleuth,
    RockTomb,
    SilverWind,
    MetalSound,
    Grasswhistle,
    Tickle,
    CosmicPower,
    WaterSpout,
    SignalBeam,
    ShadowPunch,
    Extrasensory,
    SkyUppercut,
    SandTomb,
    SheerCold,
    MuddyWater,
    BulletSeed,
    AerialAce,
    IcicleSpear,
    IronDefense,
    Block,
    Howl,
    DragonClaw,
    FrenzyPlant,
    BulkUp,
    Bounce,
    MudShot,
    PoisonTail,
    Covet,
    VoltTackle,
    MagicalLeaf,
    WaterSport,
    CalmMind,
    LeafBlade,
    DragonDance,
    RockBlast,
    ShockWave,
    WaterPulse,
    DoomDesire,
    PsychoBoost,
    Roost,
    Gravity,
    MiracleEye,
    WakeUpSlap,
    HammerArm,
    GyroBall,
    HealingWish,
    Brine,
    NaturalGift,
    Feint,
    Pluck,
    Tailwind,
    Acupressure,
    MetalBurst,
    UTurn,
    CloseCombat,
    Payback,
    Assurance,
    Embargo,
    Fling,
    PsychoShift,
    TrumpCard,
    HealBlock,
    WringOut,
    PowerTrick,
    GastroAcid,
    LuckyChant,
    MeFirst,
    Copycat,
    PowerSwap,
    GuardSwap,
    Punishment,
    LastResort,
    WorrySeed,
    SuckerPunch,
    ToxicSpikes,
    HeartSwap,
    AquaRing,
    MagnetRise,
    FlareBlitz,
    ForcePalm,
    AuraSphere,
    RockPolish,
    PoisonJab,
    DarkPulse,
    NightSlash,
    AquaTail,
    SeedBomb,
    AirSlash,
    XScissor,
    BugBuzz,
    DragonPulse,
    DragonRush,
    PowerGem,
    DrainPunch,
    VacuumWave,
    FocusBlast,
    EnergyBall,
    BraveBird,
    EarthPower,
    Switcheroo,
    GigaImpact,
    NastyPlot,
    BulletPunch,
    Avalanche,
    IceShard,
    ShadowClaw,
    ThunderFang,
    IceFang,
    FireFang,
    ShadowSneak,
    MudBomb,
    PsychoCut,
    ZenHeadbutt,
    MirrorShot,
    FlashCannon,
    RockClimb,
    Defog,
    TrickRoom,
    DracoMeteor,
    Discharge,
    LavaPlume,
    LeafStorm,
    PowerWhip,
    RockWrecker,
    CrossPoison,
    GunkShot,
    IronHead,
    MagnetBomb,
    StoneEdge,
    Captivate,
    StealthRock,
    GrassKnot,
    Chatter,
    Judgment,
    BugBite,
    ChargeBeam,
    WoodHammer,
    AquaJet,
    AttackOrder,
    DefendOrder,
    HealOrder,
    HeadSmash,
    DoubleHit,
    RoarOfTime,
    SpacialRend,
    LunarDance,
    CrushGrip,
    MagmaStorm,
    DarkVoid,
    SeedFlare,
    OminousWind,
    ShadowForce,
    Count
};

static std::unordered_set PRIORITY_MOVES_PLUS_5 = {
    Move::HelpingHand
};

static std::unordered_set PRIORITY_MOVES_PLUS_4 = {
    Move::MagicCoat,
    Move::Snatch
};

static std::unordered_set PRIORITY_MOVES_PLUS_3 = {
    Move::Detect,
    Move::Endure,
    Move::FollowMe,
    Move::Protect
};

static std::unordered_set PRIORITY_MOVES_PLUS_2 = {
    Move::Feint
};

static std::unordered_set PRIORITY_MOVES_PLUS_1 = {
    Move::AquaJet,
    Move::Bide,
    Move::BulletPunch,
    Move::ExtremeSpeed,
    Move::FakeOut,
    Move::IceShard,
    Move::MachPunch,
    Move::QuickAttack,
    Move::ShadowSneak,
    Move::SuckerPunch,
    Move::VacuumWave
};

static std::unordered_set PRIORITY_MOVES_MINUS_1 = {
    Move::VitalThrow
};

static std::unordered_set PRIORITY_MOVES_MINUS_3 = {
    Move::FocusPunch
};

static std::unordered_set PRIORITY_MOVES_MINUS_4 = {
    Move::Avalanche,
    Move::Revenge
};

static std::unordered_set PRIORITY_MOVES_MINUS_5 = {
    Move::Counter,
    Move::MirrorCoat
};

static std::unordered_set PRIORITY_MOVES_MINUS_6 = {
    Move::Roar,
    Move::Whirlwind
};


static std::unordered_set PRIORITY_MOVES_MINUS_7 = {
    Move::TrickRoom
};

static std::unordered_set POWER_MOVES = {
    Move::Pound,
    Move::DoubleSlap,
    Move::CometPunch,
    Move::MegaPunch,
    Move::PayDay,
    Move::FirePunch,
    Move::IcePunch,
    Move::ThunderPunch,
    Move::Scratch,
    Move::ViceGrip,
    Move::RazorWind,
    Move::Cut,
    Move::Gust,
    Move::WingAttack,
    Move::Fly,
    Move::Bind,
    Move::Slam,
    Move::VineWhip,
    Move::Stomp,
    Move::DoubleKick,
    Move::MegaKick,
    Move::JumpKick,
    Move::RollingKick,
    Move::Headbutt,
    Move::HornAttack,
    Move::FuryAttack,
    Move::Tackle,
    Move::BodySlam,
    Move::Wrap,
    Move::TakeDown,
    Move::Thrash,
    Move::DoubleEdge,
    Move::PoisonSting,
    Move::Twineedle,
    Move::PinMissile,
    Move::Bite,
    Move::Acid,
    Move::Ember,
    Move::Flamethrower,
    Move::WaterGun,
    Move::HydroPump,
    Move::Surf,
    Move::IceBeam,
    Move::Blizzard,
    Move::Psybeam,
    Move::Bubblebeam,
    Move::AuroraBeam,
    Move::HyperBeam,
    Move::Peck,
    Move::DrillPeck,
    Move::Submission,
    Move::Strength,
    Move::Absorb,
    Move::MegaDrain,
    Move::RazorLeaf,
    Move::SolarBeam,
    Move::PetalDance,
    Move::FireSpin,
    Move::Thundershock,
    Move::Thunderbolt,
    Move::RockThrow,
    Move::Earthquake,
    Move::Dig,
    Move::Confusion,
    Move::Psychic,
    Move::QuickAttack,
    Move::Selfdestruct,
    Move::EggBomb,
    Move::Lick,
    Move::Smog,
    Move::Sludge,
    Move::BoneClub,
    Move::FireBlast,
    Move::Waterfall,
    Move::Clamp,
    Move::Swift,
    Move::SkullBash,
    Move::SpikeCannon,
    Move::Constrict,
    Move::HighJumpKick,
    Move::Barrage,
    Move::LeechLife,
    Move::SkyAttack,
    Move::Bubble,
    Move::DizzyPunch,
    Move::Crabhammer,
    Move::Explosion,
    Move::FuryAttack,
    Move::Bonemerang,
    Move::RockSlide,
    Move::HyperFang,
    Move::TriAttack,
    Move::Slash,
    Move::FlameWheel,
    Move::Aeroblast,
    Move::PowderSnow,
    Move::MachPunch,
    Move::FaintAttack,
    Move::SludgeBomb,
    Move::MudSlap,
    Move::Octazooka,
    Move::ZapCannon,
    Move::IcyWind,
    Move::BoneRush,
    Move::Outrage,
    Move::GigaDrain,
    Move::Spark,
    Move::SteelWing,
    Move::Return,
    Move::Frustration,
    Move::SacredFire,
    Move::Dynamicpunch,
    Move::Megahorn,
    Move::DragonBreath,
    Move::IronTail,
    Move::MetalClaw,
    Move::VitalThrow,
    Move::CrossChop,
    Move::Twister,
    Move::Crunch,
    Move::ExtremeSpeed,
    Move::Ancientpower,
    Move::ShadowBall,
    Move::RockSmash,
    Move::Whirlpool,
    Move::HeatWave,
    Move::Superpower,
    Move::Dive,
    Move::ArmThrust,
    Move::LusterPurge,
    Move::MistBall,
    Move::BlazeKick,
    Move::NeedleArm,
    Move::HyperVoice,
    Move::PoisonFang,
    Move::CrushClaw,
    Move::BlastBurn,
    Move::HydroCannon,
    Move::MeteorMash,
    Move::Astonish,
    Move::AirCutter,
    Move::Overheat,
    Move::RockTomb,
    Move::SilverWind,
    Move::SignalBeam,
    Move::ShadowPunch,
    Move::Extrasensory,
    Move::SkyUppercut,
    Move::SandTomb,
    Move::MuddyWater,
    Move::BulletSeed,
    Move::AerialAce,
    Move::IcicleSpear,
    Move::DragonClaw,
    Move::FrenzyPlant,
    Move::Bounce,
    Move::MudShot,
    Move::PoisonTail,
    Move::VoltTackle,
    Move::MagicalLeaf,
    Move::LeafBlade,
    Move::RockBlast,
    Move::ShockWave,
    Move::WaterPulse,
    Move::PsychoBoost,
    Move::HammerArm,
    Move::CloseCombat,
    Move::FlareBlitz,
    Move::ForcePalm,
    Move::AuraSphere,
    Move::PoisonJab,
    Move::DarkPulse,
    Move::NightSlash,
    Move::AquaTail,
    Move::SeedBomb,
    Move::AirSlash,
    Move::XScissor,
    Move::BugBuzz,
    Move::DragonPulse,
    Move::DragonRush,
    Move::PowerGem,
    Move::DrainPunch,
    Move::VacuumWave,
    Move::FocusBlast,
    Move::EnergyBall,
    Move::BraveBird,
    Move::EarthPower,
    Move::GigaImpact,
    Move::BulletPunch,
    Move::IceShard,
    Move::ShadowClaw,
    Move::ThunderFang,
    Move::IceFang,
    Move::FireFang,
    Move::ShadowSneak,
    Move::MudBomb,
    Move::PsychoCut,
    Move::ZenHeadbutt,
    Move::MirrorShot,
    Move::FlashCannon,
    Move::RockClimb,
    Move::DracoMeteor,
    Move::Discharge,
    Move::LavaPlume,
    Move::LeafStorm,
    Move::PowerWhip,
    Move::RockWrecker,
    Move::CrossPoison,
    Move::GunkShot,
    Move::IronHead,
    Move::MagnetBomb,
    Move::StoneEdge,
    Move::ChargeBeam,
    Move::WoodHammer,
    Move::AquaJet,
    Move::AttackOrder,
    Move::HeadSmash,
    Move::DoubleHit,
    Move::RoarOfTime,
    Move::SpacialRend,
    Move::SeedFlare,
    Move::OminousWind,
    Move::ShadowForce
};

static std::unordered_set MOVES_THAT_HEAL_ATTACKER = {
    Move::Absorb,
    Move::MegaDrain,
    Move::Recover,
    Move::Softboiled,
    Move::LeechLife,
    Move::GigaDrain,
    Move::MilkDrink,
    Move::MorningSun,
    Move::Synthesis,
    Move::Moonlight,
    Move::SlackOff,
    Move::DrainPunch,
    Move::HealOrder
};

static std::unordered_set ATTACKER_STAT_BOOST_MOVES = {
    Move::SwordsDance,
    Move::Growth,
    Move::Meditate,
    Move::Agility,
    Move::DoubleTeam,
    Move::Harden,
    Move::Minimize,
    Move::Withdraw,
    Move::Amnesia,
    Move::AcidArmor,
    Move::Sharpen,
    Move::TailGlow,
    Move::CosmicPower,
    Move::IronDefense,
    Move::Howl,
    Move::BulkUp,
    Move::CalmMind,
    Move::DragonDance,
    Move::RockPolish,
    Move::NastyPlot,
    Move::DefendOrder
};

static std::unordered_set MOVES_THAT_BOOST_ATTACKERS_ATTACK = {
    Move::SwordsDance,
    Move::Meditate,
    Move::Sharpen,
    Move::BellyDrum,
    Move::MetalClaw,
    Move::MeteorMash,
    Move::Howl,
    Move::BulkUp,
    Move::DragonDance
};

static std::unordered_set MOVES_THAT_LOWER_ATTACKERS_ATTACK = {
    Move::Superpower
};

static std::unordered_set MOVES_THAT_BOOST_ATTACKERS_DEFENSE = {
    Move::Harden,
    Move::Withdraw,
    Move::SkullBash,
    Move::AcidArmor,
    Move::SteelWing,
    Move::CosmicPower,
    Move::IronDefense,
    Move::BulkUp,
    Move::DefendOrder
};

static std::unordered_set MOVES_THAT_LOWER_ATTACKERS_DEFENSE = {
    Move::Superpower,
    Move::CloseCombat
};

static std::unordered_set MOVES_THAT_LOWER_ATTACKERS_SPECIAL_ATTACK = {
    Move::Overheat,
    Move::PsychoBoost,
    Move::DracoMeteor,
    Move::LeafStorm
};

static std::unordered_set MOVES_THAT_BOOST_ATTACKERS_SPECIAL_ATTACK = {
    Move::Growth,
    Move::TailGlow,
    Move::CalmMind,
    Move::NastyPlot,
    Move::ChargeBeam
};

static std::unordered_set MOVES_THAT_BOOST_ATTACKERS_SPECIAL_DEFENSE = {
    Move::Amnesia,
    Move::CosmicPower,
    Move::CalmMind,
    Move::DefendOrder
};

static std::unordered_set MOVES_THAT_LOWER_ATTACKERS_SPECIAL_DEFENSE = {
    Move::CloseCombat
};

static std::unordered_set MOVES_THAT_BOOST_ATTACKERS_SPEED = {
    Move::Agility,
    Move::DragonDance,
    Move::RockPolish
};

static std::unordered_set MOVES_THAT_LOWER_ATTACKERS_SPEED = {
    Move::HammerArm
};

static std::unordered_set MOVES_THAT_BOOST_ATTACKERS_EVASION = {
    Move::DoubleTeam,
    Move::Minimize
};


static std::unordered_set MOVES_THAT_BOOST_ATTACKERS_CRIT_RATE = {
    Move::FocusEnergy
};

static std::unordered_set MOVES_THAT_OMNI_BOOST_ATTACKER = {
    Move::Ancientpower,
    Move::SilverWind,
    Move::OminousWind
};

static std::unordered_set MOVES_THAT_RAISE_DEFENDER_ATTACK = {
    Move::Swagger
};

static std::unordered_set MOVES_THAT_LOWER_DEFENDER_ATTACK = {
    Move::Growl,
    Move::AuroraBeam,
    Move::Charm,
    Move::Memento,
    Move::Featherdance,
    Move::Tickle
};

static std::unordered_set MOVES_THAT_RAISE_DEFENDER_SPECIAL_ATTACK = {
    Move::Flatter
};

static std::unordered_set MOVES_THAT_LOWER_DEFENDER_SPECIAL_ATTACK = {
    Move::Memento,
    Move::MistBall,
};

static std::unordered_set MOVES_THAT_LOWER_DEFENDER_DEFENSE = {
    Move::TailWhip,
    Move::Leer,
    Move::Screech,
    Move::IronTail,
    Move::Crunch,
    Move::RockSmash,
    Move::CrushClaw,
    Move::Tickle
};

static std::unordered_set MOVES_THAT_LOWER_DEFENDER_SPECIAL_DEFENSE = {
    Move::Acid,
    Move::Psychic,
    Move::ShadowBall,
    Move::LusterPurge,
    Move::FakeTears,
    Move::MetalSound,
    Move::BugBuzz,
    Move::FocusBlast,
    Move::EnergyBall,
    Move::EarthPower,
    Move::FlashCannon,
    Move::SeedFlare
};

static std::unordered_set MOVES_THAT_LOWER_DEFENDER_SPEED = {
    Move::Bubblebeam,
    Move::StringShot,
    Move::Constrict,
    Move::Bubble,
    Move::CottonSpore,
    Move::ScaryFace,
    Move::IcyWind,
    Move::RockTomb,
    Move::MudShot
};

static std::unordered_set MOVES_THAT_LOWER_DEFENDER_ACCURACY = {
    Move::SandAttack,
    Move::Smokescreen,
    Move::Kinesis,
    Move::Flash,
    Move::MudSlap,
    Move::Octazooka,
    Move::MuddyWater,
    Move::MudBomb,
    Move::MirrorShot
};

static std::unordered_set MOVES_THAT_LOWER_DEFENDER_EVASION = {
    Move::SweetScent
};

static std::unordered_set MOVES_THAT_MAY_BYPASS_ACCURACY = {
    Move::Blizzard,
    Move::Thunder,
    Move::Swift,
    Move::FaintAttack,
    Move::VitalThrow,
    Move::ShadowPunch,
    Move::AerialAce,
    Move::MagicalLeaf,
    Move::ShockWave,
    Move::AuraSphere,
    Move::MagnetBomb
};

static std::unordered_set UNUSABLE_MOVES_DURING_GRAVITY = {
    Move::Bounce,
    Move::Fly,
    Move::HighJumpKick,
    Move::JumpKick,
    Move::MagnetRise,
    Move::Splash
};

static std::unordered_set PROTECTION_MOVES = {
    Move::Detect,
    Move::Protect,
};

static std::unordered_set OTHER_MOVES = {
    Move::Disable,
    Move::Mist,
    Move::LowKick,
    Move::Counter,
    Move::LeechSeed,
    Move::Rage,
    Move::Teleport,
    Move::Mimic,
    Move::DefenseCurl,
    Move::Barrier,
    Move::LightScreen,
    Move::Haze,
    Move::Reflect,
    Move::Bide,
    Move::Metronome,
    Move::MirrorMove,
    Move::DreamEater,
    Move::Transform,
    Move::Psywave,
    Move::Splash,
    Move::Rest,
    Move::Conversion,
    Move::TriAttack,
    Move::SuperFang,
    Move::Substitute,
    Move::Struggle,
    Move::Sketch,
    Move::TripleKick,
    Move::Thief,
    Move::SpiderWeb,
    Move::MindReader,
    Move::Nightmare,
    Move::Snore,
    Move::Curse,
    Move::Flail,
    Move::Conversion2,
    Move::Reversal,
    Move::Spite,
    Move::Spikes,
    Move::Foresight,
    Move::DestinyBond,
    Move::PerishSong,
    Move::LockOn,
    Move::Rollout,
    Move::FalseSwipe,
    Move::FuryCutter,
    Move::MeanLook,
    Move::Attract,
    Move::SleepTalk,
    Move::HealBell,
    Move::Present,
    Move::Safeguard,
    Move::PainSplit,
    Move::Magnitude,
    Move::BatonPass,
    Move::Encore,
    Move::Pursuit,
    Move::RapidSpin,
    Move::HiddenPower,
    Move::MirrorCoat,
    Move::PsychUp,
    Move::FutureSight,
    Move::BeatUp,
    Move::FakeOut,
    Move::Uproar,
    Move::Stockpile,
    Move::SpitUp,
    Move::Swallow,
    Move::Torment,
    Move::Facade,
    Move::FocusPunch,
    Move::Smellingsalt,
    Move::FollowMe,
    Move::NaturePower,
    Move::Charge,
    Move::Taunt,
    Move::HelpingHand,
    Move::Trick,
    Move::RolePlay,
    Move::Wish,
    Move::Assist,
    Move::Ingrain,
    Move::MagicCoat,
    Move::Recycle,
    Move::Revenge,
    Move::BrickBreak,
    Move::Yawn,
    Move::KnockOff,
    Move::Endeavor,
    Move::Eruption,
    Move::SkillSwap,
    Move::Imprison,
    Move::Refresh,
    Move::Grudge,
    Move::Snatch,
    Move::SecretPower,
    Move::Camouflage,
    Move::MudSport,
    Move::IceBall,
    Move::WeatherBall,
    Move::Aromatherapy,
    Move::OdorSleuth,
    Move::WaterSpout,
    Move::Block,
    Move::Covet,
    Move::WaterSport,
    Move::DoomDesire,
    Move::Roost,
    Move::Gravity,
    Move::MiracleEye,
    Move::WakeUpSlap,
    Move::GyroBall,
    Move::HealingWish,
    Move::Brine,
    Move::NaturalGift,
    Move::Feint,
    Move::Pluck,
    Move::Tailwind,
    Move::Acupressure,
    Move::MetalBurst,
    Move::UTurn,
    Move::Payback,
    Move::Assurance,
    Move::Embargo,
    Move::Fling,
    Move::PsychoShift,
    Move::TrumpCard,
    Move::HealBlock,
    Move::WringOut,
    Move::PowerTrick,
    Move::GastroAcid,
    Move::LuckyChant,
    Move::MeFirst,
    Move::Copycat,
    Move::PowerSwap,
    Move::GuardSwap,
    Move::Punishment,
    Move::LastResort,
    Move::WorrySeed,
    Move::SuckerPunch,
    Move::ToxicSpikes,
    Move::HeartSwap,
    Move::AquaRing,
    Move::MagnetRise,
    Move::Switcheroo,
    Move::Avalanche,
    Move::Defog,
    Move::TrickRoom,
    Move::Captivate,
    Move::StealthRock,
    Move::GrassKnot,
    Move::Chatter,
    Move::Judgment,
    Move::BugBite,
    Move::LunarDance,
    Move::CrushGrip,
    Move::MagmaStorm
};

static std::unordered_set MOVES_THAT_CHANGE_WEATHER = {
    Move::Sandstorm,
    Move::RainDance,
    Move::SunnyDay,
    Move::Hail
};

static std::unordered_set MOVES_THAT_FORCE_USER_OUT = {
    Move::Whirlwind,
    Move::Roar,
};

static std::unordered_set ONE_HIT_KO_MOVES = {
    Move::Guillotine,
    Move::HornDrill,
    Move::Fissure,
    Move::SheerCold
};

static std::unordered_set MOVES_THAT_MAKE_ATTACKER_FAINT = {
    Move::Selfdestruct,
    Move::Explosion,
    Move::Memento
};

static std::unordered_set MOVES_WITH_INCREASED_CRIT_CHANCE = {
    Move::KarateChop,
    Move::RazorWind,
    Move::RazorLeaf,
    Move::SkyAttack,
    Move::Crabhammer,
    Move::Slash,
    Move::Aeroblast,
    Move::CrossChop,
    Move::BlazeKick,
    Move::AirCutter,
    Move::PoisonTail,
    Move::LeafBlade,
    Move::NightSlash,
    Move::ShadowClaw,
    Move::PsychoCut,
    Move::CrossPoison,
    Move::StoneEdge,
    Move::AttackOrder,
    Move::SpacialRend
};

static std::unordered_set MOVES_THAT_REQUIRE_CHARGING_TURN = {
    Move::RazorWind,
    Move::SolarBeam,
    Move::SkullBash,
    Move::SkyAttack,
};

static std::unordered_set MOVES_THAT_REQUIRE_RECHARGE_TURN = {
    Move::HyperBeam,
    Move::BlastBurn,
    Move::HydroCannon,
    Move::FrenzyPlant,
    Move::GigaImpact,
    Move::RockWrecker,
    Move::RoarOfTime
};

static std::unordered_set MOVES_THAT_DEAL_DOUBLE_AFTER_MINIMIZE = {
    Move::Stomp
};

static std::unordered_set MOVES_THAT_CONTINUE = {
    Move::Bind,
    Move::Wrap,
    Move::FireSpin,
    Move::Clamp,
    Move::Whirlpool,
    Move::SandTomb,
    Move::MagmaStorm
};

static std::unordered_set MOVES_THAT_BURN = {
    Move::FirePunch,
    Move::Ember,
    Move::Flamethrower,
    Move::FireBlast,
    Move::FlameWheel,
    Move::SacredFire,
    Move::HeatWave,
    Move::WillOWisp,
    Move::BlazeKick,
    Move::FlareBlitz,
    Move::FireFang,
    Move::LavaPlume
};

static std::unordered_set MOVES_THAT_FREEZE = {
    Move::IcePunch,
    Move::IceBeam,
    Move::Blizzard,
    Move::PowderSnow,
    Move::IceFang
};

static std::unordered_set MOVES_THAT_PARALYZE = {
    Move::ThunderPunch,
    Move::BodySlam,
    Move::StunSpore,
    Move::Thundershock,
    Move::Thunderbolt,
    Move::ThunderWave,
    Move::Thunder,
    Move::Lick,
    Move::Glare,
    Move::ZapCannon,
    Move::Spark,
    Move::DragonBreath,
    Move::Bounce,
    Move::VoltTackle,
    Move::ForcePalm,
    Move::ThunderFang,
    Move::Discharge
};

static std::unordered_set MOVES_THAT_POISON = {
    Move::PoisonSting,
    Move::Twineedle,
    Move::PoisonPowder,
    Move::Smog,
    Move::Sludge,
    Move::PoisonGas,
    Move::SludgeBomb,
    Move::PoisonTail,
    Move::PoisonJab,
    Move::CrossPoison,
    Move::GunkShot
};

static std::unordered_set MOVES_THAT_BADLY_POISON = {
    Move::Toxic,
    Move::PoisonFang
};

static std::unordered_set MOVES_THAT_MAKE_DEFENDER_SLEEP = {
    Move::Sing,
    Move::SleepPowder,
    Move::Hypnosis,
    Move::LovelyKiss,
    Move::Spore,
    Move::Grasswhistle,
    Move::DarkVoid
};

static std::unordered_set MOVES_THAT_CONFUSE_DEFENDER = {
    Move::Supersonic,
    Move::Psybeam,
    Move::Confusion,
    Move::ConfuseRay,
    Move::DizzyPunch,
    Move::SweetKiss,
    Move::Swagger,
    Move::Dynamicpunch,
    Move::Flatter,
    Move::TeeterDance,
    Move::SignalBeam,
    Move::WaterPulse,
    Move::RockClimb
};

static std::unordered_set MOVES_THAT_FLINCH = {
    Move::Stomp,
    Move::RollingKick,
    Move::Headbutt,
    Move::Bite,
    Move::BoneClub,
    Move::Waterfall,
    Move::SkyAttack,
    Move::HyperFang,
    Move::Twister,
    Move::NeedleArm,
    Move::Astonish,
    Move::Extrasensory,
    Move::DarkPulse,
    Move::AirSlash,
    Move::DragonRush,
    Move::ThunderFang,
    Move::IceFang,
    Move::FireFang,
    Move::ZenHeadbutt,
    Move::IronHead
};

static std::unordered_set MOVES_WITH_RECOIL = {
    Move::JumpKick,
    Move::TakeDown,
    Move::DoubleEdge,
    Move::Submission,
    Move::HighJumpKick,
    Move::BellyDrum,
    Move::VoltTackle,
    Move::FlareBlitz,
    Move::BraveBird,
    Move::WoodHammer,
    Move::HeadSmash
};


static std::unordered_set MULTI_HIT_MOVES = {
    Move::DoubleSlap,
    Move::CometPunch,
    Move::DoubleKick,
    Move::FuryAttack,
    Move::Twineedle,
    Move::PinMissile,
    Move::SpikeCannon,
    Move::Barrage,
    Move::FuryAttack,
    Move::Bonemerang,
    Move::BoneRush,
    Move::ArmThrust,
    Move::BulletSeed,
    Move::IcicleSpear,
    Move::RockBlast,
    Move::DoubleHit
};

static std::unordered_set MULTI_TURN_MOVES = {
    Move::Thrash,
    Move::PetalDance,
    Move::Outrage
};

static std::unordered_set MOVES_THAT_HAVE_FIXED_DAMAGE = {
    Move::SonicBoom,
    Move::SeismicToss,
    Move::DragonRage,
    Move::NightShade,

};

static std::unordered_set MOVES_THAT_GO_INTO_AIR = {
    Move::Bounce,
    Move::Fly
};

static std::unordered_set MOVES_THAT_HIT_DEFENDER_IN_AIR = {
    Move::Gust,
    Move::SkyUppercut,
    Move::Thunder,
    Move::Twister
};

static std::unordered_set MOVES_THAT_GO_UNDER_GROUND = {
    Move::Dig,
};

static std::unordered_set MOVES_THAT_HIT_DEFENDER_UNDER_GROUND = {
    Move::Earthquake,
    Move::Magnitude,
    Move::Fissure
};

static std::unordered_set MOVES_THAT_GO_UNDER_WATER = {
    Move::Dive,
};

static std::unordered_set MOVES_THAT_HIT_DEFENDER_UNDER_WATER = {
    Move::Surf,
    Move::Whirlpool
};

static std::unordered_set MOVES_THAT_VANISH_USER = {
    Move::ShadowForce,
};

static std::unordered_set MOVES_THAT_MAKE_CONTACT = {
    Move::Pound,
    Move::KarateChop,
    Move::DoubleSlap,
    Move::CometPunch,
    Move::MegaPunch,
    Move::FirePunch,
    Move::IcePunch,
    Move::ThunderPunch,
    Move::Scratch,
    Move::ViceGrip,
    Move::Guillotine,
    Move::Cut,
    Move::WingAttack,
    Move::Fly,
    Move::Bind,
    Move::Slam,
    Move::VineWhip,
    Move::Stomp,
    Move::DoubleKick,
    Move::MegaKick,
    Move::JumpKick,
    Move::RollingKick,
    Move::Headbutt,
    Move::HornAttack,
    Move::FuryAttack,
    Move::HornDrill,
    Move::Tackle,
    Move::BodySlam,
    Move::Wrap,
    Move::TakeDown,
    Move::Thrash,
    Move::DoubleEdge,
    Move::Bite,
    Move::Peck,
    Move::DrillPeck,
    Move::Submission,
    Move::LowKick,
    Move::Counter,
    Move::SeismicToss,
    Move::Strength,
    Move::PetalDance,
    Move::Dig,
    Move::QuickAttack,
    Move::Rage,
    Move::Bide,
    Move::Lick,
    Move::Waterfall,
    Move::Clamp,
    Move::SkullBash,
    Move::Constrict,
    Move::HighJumpKick,
    Move::LeechLife,
    Move::DizzyPunch,
    Move::Crabhammer,
    Move::FurySwipes,
    Move::HyperFang,
    Move::SuperFang,
    Move::Slash,
    Move::Struggle,
    Move::TripleKick,
    Move::Thief,
    Move::FlameWheel,
    Move::Flail,
    Move::Reversal,
    Move::MachPunch,
    Move::FaintAttack,
    Move::Outrage,
    Move::Rollout,
    Move::FalseSwipe,
    Move::Spark,
    Move::FuryCutter,
    Move::SteelWing,
    Move::Return,
    Move::Frustration,
    Move::Dynamicpunch,
    Move::Megahorn,
    Move::Pursuit,
    Move::RapidSpin,
    Move::IronTail,
    Move::MetalClaw,
    Move::VitalThrow,
    Move::CrossChop,
    Move::Crunch,
    Move::ExtremeSpeed,
    Move::RockSmash,
    Move::FakeOut,
    Move::Facade,
    Move::FocusPunch,
    Move::Smellingsalt,
    Move::Superpower,
    Move::Revenge,
    Move::BrickBreak,
    Move::KnockOff,
    Move::Endeavor,
    Move::Dive,
    Move::ArmThrust,
    Move::BlazeKick,
    Move::IceBall,
    Move::NeedleArm,
    Move::PoisonFang,
    Move::CrushClaw,
    Move::MeteorMash,
    Move::Astonish,
    Move::ShadowPunch,
    Move::SkyUppercut,
    Move::AerialAce,
    Move::DragonClaw,
    Move::Bounce,
    Move::PoisonTail,
    Move::Covet,
    Move::VoltTackle,
    Move::LeafBlade,
    Move::WakeUpSlap,
    Move::HammerArm,
    Move::GyroBall,
    Move::Pluck,
    Move::UTurn,
    Move::CloseCombat,
    Move::Payback,
    Move::Assurance,
    Move::Punishment,
    Move::LastResort,
    Move::SuckerPunch,
    Move::FlareBlitz,
    Move::ForcePalm,
    Move::PoisonJab,
    Move::NightSlash,
    Move::AquaTail,
    Move::XScissor,
    Move::DragonRush,
    Move::DrainPunch,
    Move::BraveBird,
    Move::GigaImpact,
    Move::BulletPunch,
    Move::Avalanche,
    Move::ShadowClaw,
    Move::ThunderFang,
    Move::IceFang,
    Move::FireFang,
    Move::ShadowSneak,
    Move::ZenHeadbutt,
    Move::RockClimb,
    Move::PowerWhip,
    Move::CrossPoison,
    Move::IronHead,
    Move::BugBite,
    Move::WoodHammer,
    Move::AquaJet,
    Move::HeadSmash,
    Move::DoubleHit,
    Move::CrushGrip,
    Move::ShadowForce,
};

static std::unordered_set MOVES_THAT_BYPASS_PROTECT = {
    Move::Acupressure,
    Move::Curse,
    Move::DoomDesire,
    Move::Feint,
    Move::FutureSight,
    Move::PerishSong,
    Move::PsychUp,
    Move::RolePlay,
    Move::ShadowForce,
    Move::Sketch,
    Move::Transform
};

static std::unordered_set MOVES_THAT_BREAK_PROTECT = {
    Move::Feint,
    Move::ShadowForce
};

static std::unordered_set MOVES_THAT_CAN_BE_REFLECTED_BY_MIRROR_COAT = {
    Move::Attract,
    Move::Block,
    Move::Captivate,
    Move::Charm,
    Move::ConfuseRay,
    Move::CottonSpore,
    Move::DarkVoid,
    Move::FakeTears,
    Move::Featherdance,
    Move::Flash,
    Move::Flatter,
    Move::GastroAcid,
    Move::Glare,
    Move::Grasswhistle,
    Move::Growl,
    Move::Hypnosis,
    Move::Kinesis,
    Move::LeechSeed,
    Move::Leer,
    Move::LovelyKiss,
    Move::MeanLook,
    Move::MetalSound,
    Move::PoisonGas,
    Move::PoisonPowder,
    Move::SandAttack,
    Move::ScaryFace,
    Move::Screech,
    Move::Sing,
    Move::SleepPowder,
    Move::Smokescreen,
    Move::SpiderWeb,
    Move::Spore,
    Move::StringShot,
    Move::StunSpore,
    Move::Supersonic,
    Move::Swagger,
    Move::SweetKiss,
    Move::SweetScent,
    Move::TailWhip,
    Move::ThunderWave,
    Move::Tickle,
    Move::Toxic,
    Move::WillOWisp,
    Move::WorrySeed,
    Move::Yawn
};

static std::unordered_set MOVES_THAT_CAN_BE_SNATCHED = {
    Move::AcidArmor,
    Move::Acupressure,
    Move::Agility,
    Move::Amnesia,
    Move::Aromatherapy,
    Move::Barrier,
    Move::BellyDrum,
    Move::BulkUp,
    Move::CalmMind,
    Move::Camouflage,
    Move::Charge,
    Move::CosmicPower,
    Move::DefendOrder,
    Move::DefenseCurl,
    Move::DoubleTeam,
    Move::DragonDance,
    Move::FocusEnergy,
    Move::Growth,
    Move::Harden,
    Move::HealBell,
    Move::HealOrder,
    Move::Howl,
    Move::Ingrain,
    Move::IronDefense,
    Move::LightScreen,
    Move::Meditate,
    Move::MilkDrink,
    Move::Minimize,
    Move::Mist,
    Move::Moonlight,
    Move::MorningSun,
    Move::NastyPlot,
    Move::PsychUp,
    Move::Recover,
    Move::Reflect,
    Move::Refresh,
    Move::Rest,
    Move::RockPolish,
    Move::Roost,
    Move::Safeguard,
    Move::Sharpen,
    Move::SlackOff,
    Move::Softboiled,
    Move::Stockpile,
    Move::Substitute,
    Move::Swallow,
    Move::SwordsDance,
    Move::Synthesis,
    Move::TailGlow,
    Move::Tailwind,
    Move::Withdraw,
};

static const std::unordered_set MOVES_AFFECTED_BY_KINGS_ROCK = {
    Move::AerialAce,
    Move::Aeroblast,
    Move::AirCutter,
    Move::AirSlash,
    Move::AquaJet,
    Move::AquaTail,
    Move::ArmThrust,
    Move::Assurance,
    Move::AttackOrder,
    Move::AuraSphere,
    Move::Avalanche,
    Move::Barrage,
    Move::BeatUp,
    Move::Bide,
    Move::Bind,
    Move::BlastBurn,
    Move::BoneRush,
    Move::Bonemerang,
    Move::Bounce,
    Move::BraveBird,
    Move::BrickBreak,
    Move::Brine,
    Move::BugBite,
    Move::BulletPunch,
    Move::BulletSeed,
    Move::ChargeBeam,
    Move::Clamp,
    Move::CloseCombat,
    Move::CometPunch,
    Move::Crabhammer,
    Move::CrossChop,
    Move::CrossPoison,
    Move::CrushGrip,
    Move::Cut,
    Move::DarkPulse,
    Move::Dig,
    Move::Discharge,
    Move::Dive,
    Move::DoubleHit,
    Move::DoubleKick,
    Move::DoubleSlap,
    Move::DoubleEdge,
    Move::DracoMeteor,
    Move::DragonBreath,
    Move::DragonClaw,
    Move::DragonPulse,
    Move::DragonRush,
    Move::DrainPunch,
    Move::DrillPeck,
    Move::EarthPower,
    Move::Earthquake,
    Move::EggBomb,
    Move::Endeavor,
    Move::Eruption,
    Move::Explosion,
    Move::ExtremeSpeed,
    Move::FalseSwipe,
    Move::FaintAttack,
    Move::FireFang,
    Move::FireSpin,
    Move::Flail,
    Move::FlashCannon,
    Move::Fly,
    Move::ForcePalm,
    Move::FrenzyPlant,
    Move::Frustration,
    Move::FuryAttack,
    Move::FuryCutter,
    Move::FurySwipes,
    Move::GigaImpact,
    Move::GrassKnot,
    Move::GunkShot,
    Move::GyroBall,
    Move::HammerArm,
    Move::HeadSmash,
    Move::HiddenPower,
    Move::HighJumpKick,
    Move::HornAttack,
    Move::HydroCannon,
    Move::HydroPump,
    Move::HyperBeam,
    Move::IceBall,
    Move::IceFang,
    Move::IceShard,
    Move::IcicleSpear,
    Move::IronHead,
    Move::Judgment,
    Move::JumpKick,
    Move::KarateChop,
    Move::LastResort,
    Move::LavaPlume,
    Move::LeafBlade,
    Move::LeafStorm,
    Move::LowKick,
    Move::MachPunch,
    Move::MagicalLeaf,
    Move::MagmaStorm,
    Move::MagnetBomb,
    Move::Magnitude,
    Move::MegaKick,
    Move::MegaPunch,
    Move::Megahorn,
    Move::MeteorMash,
    Move::MirrorCoat,
    Move::MirrorShot,
    Move::MudBomb,
    Move::MudShot,
    Move::MuddyWater,
    Move::NightShade,
    Move::NightSlash,
    Move::OminousWind,
    Move::Outrage,
    Move::Overheat,
    Move::PayDay,
    Move::Payback,
    Move::Peck,
    Move::PetalDance,
    Move::PinMissile,
    Move::Pluck,
    Move::PoisonJab,
    Move::PoisonTail,
    Move::PowerGem,
    Move::PowerWhip,
    Move::PsychoBoost,
    Move::PsychoCut,
    Move::Psywave,
    Move::Punishment,
    Move::QuickAttack,
    Move::Rage,
    Move::RapidSpin,
    Move::RazorLeaf,
    Move::RazorWind,
    Move::Return,
    Move::Revenge,
    Move::Reversal,
    Move::RoarOfTime,
    Move::RockBlast,
    Move::RockClimb,
    Move::RockThrow,
    Move::RockWrecker,
    Move::RollingKick,
    Move::Rollout,
    Move::SandTomb,
    Move::Scratch,
    Move::SeedBomb,
    Move::SeedFlare,
    Move::SeismicToss,
    Move::ShadowClaw,
    Move::ShadowForce,
    Move::ShadowPunch,
    Move::ShadowSneak,
    Move::ShockWave,
    Move::SignalBeam,
    Move::SilverWind,
    Move::SkullBash,
    Move::SkyAttack,
    Move::SkyUppercut,
    Move::Slam,
    Move::Slash,
    Move::Snore,
    Move::SolarBeam,
    Move::SonicBoom,
    Move::SpacialRend,
    Move::SpikeCannon,
    Move::SpitUp,
    Move::SteelWing,
    Move::StoneEdge,
    Move::Strength,
    Move::Struggle,
    Move::Submission,
    Move::SuckerPunch,
    Move::Surf,
    Move::Swift,
    Move::Tackle,
    Move::TakeDown,
    Move::Thrash,
    Move::ThunderFang,
    Move::TripleKick,
    Move::TrumpCard,
    Move::Twister,
    Move::UTurn,
    Move::Uproar,
    Move::VacuumWave,
    Move::ViceGrip,
    Move::VineWhip,
    Move::VitalThrow,
    Move::VoltTackle,
    Move::WakeUpSlap,
    Move::WaterGun,
    Move::WaterPulse,
    Move::Waterfall,
    Move::WeatherBall,
    Move::Whirlpool,
    Move::WingAttack,
    Move::WoodHammer,
    Move::Wrap,
    Move::WringOut,
    Move::XScissor,
};

static std::unordered_map<std::string, Move> MOVE_MAP = {
    {"Pound", Move::Pound},
    {"Karate Chop", Move::KarateChop},
    {"Doubleslap", Move::DoubleSlap},
    {"Comet Punch", Move::CometPunch},
    {"Mega Punch", Move::MegaPunch},
    {"Pay Day", Move::PayDay},
    {"Fire Punch", Move::FirePunch},
    {"Ice Punch", Move::IcePunch},
    {"Thunderpunch", Move::ThunderPunch},
    {"Thunder Punch", Move::ThunderPunch},
    {"Scratch", Move::Scratch},
    {"Vicegrip", Move::ViceGrip},
    {"Guillotine", Move::Guillotine},
    {"Razor Wind", Move::RazorWind},
    {"Swords Dance", Move::SwordsDance},
    {"Cut", Move::Cut},
    {"Gust", Move::Gust},
    {"Wing Attack", Move::WingAttack},
    {"Whirlwind", Move::Whirlwind},
    {"Fly", Move::Fly},
    {"Bind", Move::Bind},
    {"Slam", Move::Slam},
    {"Vine Whip", Move::VineWhip},
    {"Stomp", Move::Stomp},
    {"Double Kick", Move::DoubleKick},
    {"Mega Kick", Move::MegaKick},
    {"Jump Kick", Move::JumpKick},
    {"Rolling Kick", Move::RollingKick},
    {"Sand-attack", Move::SandAttack},
    {"Sand Attack", Move::SandAttack},
    {"Headbutt", Move::Headbutt},
    {"Horn Attack", Move::HornAttack},
    {"Fury Attack", Move::FuryAttack},
    {"Horn Drill", Move::HornDrill},
    {"Tackle", Move::Tackle},
    {"Body Slam", Move::BodySlam},
    {"Wrap", Move::Wrap},
    {"Take Down", Move::TakeDown},
    {"Thrash", Move::Thrash},
    {"Double-edge", Move::DoubleEdge},
    {"Double-Edge", Move::DoubleEdge},
    {"Tail Whip", Move::TailWhip},
    {"Poison Sting", Move::PoisonSting},
    {"Twineedle", Move::Twineedle},
    {"Pin Missile", Move::PinMissile},
    {"Leer", Move::Leer},
    {"Bite", Move::Bite},
    {"Growl", Move::Growl},
    {"Roar", Move::Roar},
    {"Sing", Move::Sing},
    {"Supersonic", Move::Supersonic},
    {"Sonicboom", Move::SonicBoom},
    {"Disable", Move::Disable},
    {"Acid", Move::Acid},
    {"Ember", Move::Ember},
    {"Flamethrower", Move::Flamethrower},
    {"Mist", Move::Mist},
    {"Water Gun", Move::WaterGun},
    {"Hydro Pump", Move::HydroPump},
    {"Surf", Move::Surf},
    {"Ice Beam", Move::IceBeam},
    {"Blizzard", Move::Blizzard},
    {"Psybeam", Move::Psybeam},
    {"Bubblebeam", Move::Bubblebeam},
    {"Bubble Beam", Move::Bubblebeam},
    {"Aurora Beam", Move::AuroraBeam},
    {"Hyper Beam", Move::HyperBeam},
    {"Peck", Move::Peck},
    {"Drill Peck", Move::DrillPeck},
    {"Submission", Move::Submission},
    {"Low Kick", Move::LowKick},
    {"Counter", Move::Counter},
    {"Seismic Toss", Move::SeismicToss},
    {"Strength", Move::Strength},
    {"Absorb", Move::Absorb},
    {"Mega Drain", Move::MegaDrain},
    {"Leech Seed", Move::LeechSeed},
    {"Growth", Move::Growth},
    {"Razor Leaf", Move::RazorLeaf},
    {"Solarbeam", Move::SolarBeam},
    {"Solar Beam", Move::SolarBeam},
    {"Poisonpowder", Move::PoisonPowder},
    {"Poison Powder", Move::PoisonPowder},
    {"Stun Spore", Move::StunSpore},
    {"Sleep Powder", Move::SleepPowder},
    {"Petal Dance", Move::PetalDance},
    {"String Shot", Move::StringShot},
    {"Dragon Rage", Move::DragonRage},
    {"Fire Spin", Move::FireSpin},
    {"Thundershock", Move::Thundershock},
    {"Thunderbolt", Move::Thunderbolt},
    {"Thunder Wave", Move::ThunderWave},
    {"Thunder", Move::Thunder},
    {"Rock Throw", Move::RockThrow},
    {"Earthquake", Move::Earthquake},
    {"Fissure", Move::Fissure},
    {"Dig", Move::Dig},
    {"Toxic", Move::Toxic},
    {"Confusion", Move::Confusion},
    {"Psychic", Move::Psychic},
    {"Hypnosis", Move::Hypnosis},
    {"Meditate", Move::Meditate},
    {"Agility", Move::Agility},
    {"Quick Attack", Move::QuickAttack},
    {"Rage", Move::Rage},
    {"Teleport", Move::Teleport},
    {"Night Shade", Move::NightShade},
    {"Mimic", Move::Mimic},
    {"Screech", Move::Screech},
    {"Double Team", Move::DoubleTeam},
    {"Recover", Move::Recover},
    {"Harden", Move::Harden},
    {"Minimize", Move::Minimize},
    {"Smokescreen", Move::Smokescreen},
    {"SmokeScreen", Move::Smokescreen},
    {"Confuse Ray", Move::ConfuseRay},
    {"Withdraw", Move::Withdraw},
    {"Defense Curl", Move::DefenseCurl},
    {"Barrier", Move::Barrier},
    {"Light Screen", Move::LightScreen},
    {"Haze", Move::Haze},
    {"Reflect", Move::Reflect},
    {"Focus Energy", Move::FocusEnergy},
    {"Bide", Move::Bide},
    {"Metronome", Move::Metronome},
    {"Mirror Move", Move::MirrorMove},
    {"Selfdestruct", Move::Selfdestruct},
    {"Egg Bomb", Move::EggBomb},
    {"Lick", Move::Lick},
    {"Smog", Move::Smog},
    {"Sludge", Move::Sludge},
    {"Bone Club", Move::BoneClub},
    {"Fire Blast", Move::FireBlast},
    {"Waterfall", Move::Waterfall},
    {"Clamp", Move::Clamp},
    {"Swift", Move::Swift},
    {"Skull Bash", Move::SkullBash},
    {"Spike Cannon", Move::SpikeCannon},
    {"Constrict", Move::Constrict},
    {"Amnesia", Move::Amnesia},
    {"Kinesis", Move::Kinesis},
    {"Softboiled", Move::Softboiled},
    {"Soft-Boiled", Move::Softboiled},
    {"Hi Jump Kick", Move::HighJumpKick},
    {"High Jump Kick", Move::HighJumpKick},
    {"Glare", Move::Glare},
    {"Dream Eater", Move::DreamEater},
    {"Poison Gas", Move::PoisonGas},
    {"Barrage", Move::Barrage},
    {"Leech Life", Move::LeechLife},
    {"Lovely Kiss", Move::LovelyKiss},
    {"Sky Attack", Move::SkyAttack},
    {"Transform", Move::Transform},
    {"Bubble", Move::Bubble},
    {"Dizzy Punch", Move::DizzyPunch},
    {"Spore", Move::Spore},
    {"Flash", Move::Flash},
    {"Psywave", Move::Psywave},
    {"Splash", Move::Splash},
    {"Acid Armor", Move::AcidArmor},
    {"Crabhammer", Move::Crabhammer},
    {"Explosion", Move::Explosion},
    {"Fury Swipes", Move::FurySwipes},
    {"Bonemerang", Move::Bonemerang},
    {"Rest", Move::Rest},
    {"Rock Slide", Move::RockSlide},
    {"Hyper Fang", Move::HyperFang},
    {"Sharpen", Move::Sharpen},
    {"Conversion", Move::Conversion},
    {"Tri Attack", Move::TriAttack},
    {"Super Fang", Move::SuperFang},
    {"Slash", Move::Slash},
    {"Substitute", Move::Substitute},
    {"Struggle", Move::Struggle},
    {"Sketch", Move::Sketch},
    {"Triple Kick", Move::TripleKick},
    {"Thief", Move::Thief},
    {"Spider Web", Move::SpiderWeb},
    {"Mind Reader", Move::MindReader},
    {"Nightmare", Move::Nightmare},
    {"Flame Wheel", Move::FlameWheel},
    {"Snore", Move::Snore},
    {"Curse", Move::Curse},
    {"Flail", Move::Flail},
    {"Conversion 2", Move::Conversion2},
    {"Aeroblast", Move::Aeroblast},
    {"Cotton Spore", Move::CottonSpore},
    {"Reversal", Move::Reversal},
    {"Spite", Move::Spite},
    {"Powder Snow", Move::PowderSnow},
    {"Protect", Move::Protect},
    {"Mach Punch", Move::MachPunch},
    {"Scary Face", Move::ScaryFace},
    {"Faint Attack", Move::FaintAttack},
    {"Feint Attack", Move::FaintAttack},
    {"Sweet Kiss", Move::SweetKiss},
    {"Belly Drum", Move::BellyDrum},
    {"Sludge Bomb", Move::SludgeBomb},
    {"Mud-slap", Move::MudSlap},
    {"Mud-Slap", Move::MudSlap},
    {"Octazooka", Move::Octazooka},
    {"Spikes", Move::Spikes},
    {"Zap Cannon", Move::ZapCannon},
    {"Foresight", Move::Foresight},
    {"Destiny Bond", Move::DestinyBond},
    {"Perish Song", Move::PerishSong},
    {"Icy Wind", Move::IcyWind},
    {"Detect", Move::Detect},
    {"Bone Rush", Move::BoneRush},
    {"Lock-on", Move::LockOn},
    {"Outrage", Move::Outrage},
    {"Sandstorm", Move::Sandstorm},
    {"Giga Drain", Move::GigaDrain},
    {"Endure", Move::Endure},
    {"Charm", Move::Charm},
    {"Rollout", Move::Rollout},
    {"False Swipe", Move::FalseSwipe},
    {"Swagger", Move::Swagger},
    {"Milk Drink", Move::MilkDrink},
    {"Spark", Move::Spark},
    {"Fury Cutter", Move::FuryCutter},
    {"Steel Wing", Move::SteelWing},
    {"Mean Look", Move::MeanLook},
    {"Attract", Move::Attract},
    {"Sleep Talk", Move::SleepTalk},
    {"Heal Bell", Move::HealBell},
    {"Return", Move::Return},
    {"Present", Move::Present},
    {"Frustration", Move::Frustration},
    {"Safeguard", Move::Safeguard},
    {"Pain Split", Move::PainSplit},
    {"Sacred Fire", Move::SacredFire},
    {"Magnitude", Move::Magnitude},
    {"Dynamicpunch", Move::Dynamicpunch},
    {"Dynamic Punch", Move::Dynamicpunch},
    {"Megahorn", Move::Megahorn},
    {"Dragonbreath", Move::DragonBreath},
    {"Baton Pass", Move::BatonPass},
    {"Encore", Move::Encore},
    {"Pursuit", Move::Pursuit},
    {"Rapid Spin", Move::RapidSpin},
    {"Sweet Scent", Move::SweetScent},
    {"Iron Tail", Move::IronTail},
    {"Metal Claw", Move::MetalClaw},
    {"Vital Throw", Move::VitalThrow},
    {"Morning Sun", Move::MorningSun},
    {"Synthesis", Move::Synthesis},
    {"Moonlight", Move::Moonlight},
    {"Hidden Power", Move::HiddenPower},
    {"Cross Chop", Move::CrossChop},
    {"Twister", Move::Twister},
    {"Rain Dance", Move::RainDance},
    {"Sunny Day", Move::SunnyDay},
    {"Crunch", Move::Crunch},
    {"Mirror Coat", Move::MirrorCoat},
    {"Psych Up", Move::PsychUp},
    {"Extremespeed", Move::ExtremeSpeed},
    {"Extreme Speed", Move::ExtremeSpeed},
    {"Ancientpower", Move::Ancientpower},
    {"Ancient Power", Move::Ancientpower},
    {"Shadow Ball", Move::ShadowBall},
    {"Future Sight", Move::FutureSight},
    {"Rock Smash", Move::RockSmash},
    {"Whirlpool", Move::Whirlpool},
    {"Beat Up", Move::BeatUp},
    {"Fake Out", Move::FakeOut},
    {"Uproar", Move::Uproar},
    {"Stockpile", Move::Stockpile},
    {"Spit Up", Move::SpitUp},
    {"Swallow", Move::Swallow},
    {"Heat Wave", Move::HeatWave},
    {"Hail", Move::Hail},
    {"Torment", Move::Torment},
    {"Flatter", Move::Flatter},
    {"Will-o-wisp", Move::WillOWisp},
    {"Will-O-Wisp", Move::WillOWisp},
    {"Memento", Move::Memento},
    {"Facade", Move::Facade},
    {"Focus Punch", Move::FocusPunch},
    {"Smellingsalt", Move::Smellingsalt},
    {"Follow Me", Move::FollowMe},
    {"Nature Power", Move::NaturePower},
    {"Charge", Move::Charge},
    {"Taunt", Move::Taunt},
    {"Helping Hand", Move::HelpingHand},
    {"Trick", Move::Trick},
    {"Role Play", Move::RolePlay},
    {"Wish", Move::Wish},
    {"Assist", Move::Assist},
    {"Ingrain", Move::Ingrain},
    {"Superpower", Move::Superpower},
    {"Magic Coat", Move::MagicCoat},
    {"Recycle", Move::Recycle},
    {"Revenge", Move::Revenge},
    {"Brick Break", Move::BrickBreak},
    {"Yawn", Move::Yawn},
    {"Knock Off", Move::KnockOff},
    {"Endeavor", Move::Endeavor},
    {"Eruption", Move::Eruption},
    {"Skill Swap", Move::SkillSwap},
    {"Imprison", Move::Imprison},
    {"Refresh", Move::Refresh},
    {"Grudge", Move::Grudge},
    {"Snatch", Move::Snatch},
    {"Secret Power", Move::SecretPower},
    {"Dive", Move::Dive},
    {"Arm Thrust", Move::ArmThrust},
    {"Camouflage", Move::Camouflage},
    {"Tail Glow", Move::TailGlow},
    {"Luster Purge", Move::LusterPurge},
    {"Mist Ball", Move::MistBall},
    {"Featherdance", Move::Featherdance},
    {"Feather Dance", Move::Featherdance},
    {"Teeter Dance", Move::TeeterDance},
    {"Blaze Kick", Move::BlazeKick},
    {"Mud Sport", Move::MudSport},
    {"Ice Ball", Move::IceBall},
    {"Needle Arm", Move::NeedleArm},
    {"Slack Off", Move::SlackOff},
    {"Hyper Voice", Move::HyperVoice},
    {"Poison Fang", Move::PoisonFang},
    {"Crush Claw", Move::CrushClaw},
    {"Blast Burn", Move::BlastBurn},
    {"Hydro Cannon", Move::HydroCannon},
    {"Meteor Mash", Move::MeteorMash},
    {"Astonish", Move::Astonish},
    {"Weather Ball", Move::WeatherBall},
    {"Aromatherapy", Move::Aromatherapy},
    {"Fake Tears", Move::FakeTears},
    {"Air Cutter", Move::AirCutter},
    {"Overheat", Move::Overheat},
    {"Odor Sleuth", Move::OdorSleuth},
    {"Rock Tomb", Move::RockTomb},
    {"Silver Wind", Move::SilverWind},
    {"Metal Sound", Move::MetalSound},
    {"Grasswhistle", Move::Grasswhistle},
    {"Tickle", Move::Tickle},
    {"Cosmic Power", Move::CosmicPower},
    {"Water Spout", Move::WaterSpout},
    {"Signal Beam", Move::SignalBeam},
    {"Shadow Punch", Move::ShadowPunch},
    {"Extrasensory", Move::Extrasensory},
    {"Sky Uppercut", Move::SkyUppercut},
    {"Sand Tomb", Move::SandTomb},
    {"Sheer Cold", Move::SheerCold},
    {"Muddy Water", Move::MuddyWater},
    {"Bullet Seed", Move::BulletSeed},
    {"Aerial Ace", Move::AerialAce},
    {"Icicle Spear", Move::IcicleSpear},
    {"Iron Defense", Move::IronDefense},
    {"Block", Move::Block},
    {"Howl", Move::Howl},
    {"Dragon Claw", Move::DragonClaw},
    {"Frenzy Plant", Move::FrenzyPlant},
    {"Bulk Up", Move::BulkUp},
    {"Bounce", Move::Bounce},
    {"Mud Shot", Move::MudShot},
    {"Poison Tail", Move::PoisonTail},
    {"Covet", Move::Covet},
    {"Volt Tackle", Move::VoltTackle},
    {"Magical Leaf", Move::MagicalLeaf},
    {"Water Sport", Move::WaterSport},
    {"Calm Mind", Move::CalmMind},
    {"Leaf Blade", Move::LeafBlade},
    {"Dragon Dance", Move::DragonDance},
    {"Rock Blast", Move::RockBlast},
    {"Shock Wave", Move::ShockWave},
    {"Water Pulse", Move::WaterPulse},
    {"Doom Desire", Move::DoomDesire},
    {"Psycho Boost", Move::PsychoBoost},
    {"Roost", Move::Roost},
    {"Gravity", Move::Gravity},
    {"Miracle Eye", Move::MiracleEye},
    {"Wake-up Slap", Move::WakeUpSlap},
    {"Hammer Arm", Move::HammerArm},
    {"Gyro Ball", Move::GyroBall},
    {"Healing Wish", Move::HealingWish},
    {"Brine", Move::Brine},
    {"Natural Gift", Move::NaturalGift},
    {"Feint", Move::Feint},
    {"Pluck", Move::Pluck},
    {"Tailwind", Move::Tailwind},
    {"Acupressure", Move::Acupressure},
    {"Metal Burst", Move::MetalBurst},
    {"U-turn", Move::UTurn},
    {"Close Combat", Move::CloseCombat},
    {"Payback", Move::Payback},
    {"Assurance", Move::Assurance},
    {"Embargo", Move::Embargo},
    {"Fling", Move::Fling},
    {"Psycho Shift", Move::PsychoShift},
    {"Trump Card", Move::TrumpCard},
    {"Heal Block", Move::HealBlock},
    {"Wring Out", Move::WringOut},
    {"Power Trick", Move::PowerTrick},
    {"Gastro Acid", Move::GastroAcid},
    {"Lucky Chant", Move::LuckyChant},
    {"Me First", Move::MeFirst},
    {"Copycat", Move::Copycat},
    {"Power Swap", Move::PowerSwap},
    {"Guard Swap", Move::GuardSwap},
    {"Punishment", Move::Punishment},
    {"Last Resort", Move::LastResort},
    {"Worry Seed", Move::WorrySeed},
    {"Sucker Punch", Move::SuckerPunch},
    {"Toxic Spikes", Move::ToxicSpikes},
    {"Heart Swap", Move::HeartSwap},
    {"Aqua Ring", Move::AquaRing},
    {"Magnet Rise", Move::MagnetRise},
    {"Flare Blitz", Move::FlareBlitz},
    {"Force Palm", Move::ForcePalm},
    {"Aura Sphere", Move::AuraSphere},
    {"Rock Polish", Move::RockPolish},
    {"Poison Jab", Move::PoisonJab},
    {"Dark Pulse", Move::DarkPulse},
    {"Night Slash", Move::NightSlash},
    {"Aqua Tail", Move::AquaTail},
    {"Seed Bomb", Move::SeedBomb},
    {"Air Slash", Move::AirSlash},
    {"X-scissor", Move::XScissor},
    {"X-Scissor", Move::XScissor},
    {"Bug Buzz", Move::BugBuzz},
    {"Dragon Pulse", Move::DragonPulse},
    {"Dragon Rush", Move::DragonRush},
    {"Power Gem", Move::PowerGem},
    {"Drain Punch", Move::DrainPunch},
    {"Vacuum Wave", Move::VacuumWave},
    {"Focus Blast", Move::FocusBlast},
    {"Energy Ball", Move::EnergyBall},
    {"Brave Bird", Move::BraveBird},
    {"Earth Power", Move::EarthPower},
    {"Switcheroo", Move::Switcheroo},
    {"Giga Impact", Move::GigaImpact},
    {"Nasty Plot", Move::NastyPlot},
    {"Bullet Punch", Move::BulletPunch},
    {"Avalanche", Move::Avalanche},
    {"Ice Shard", Move::IceShard},
    {"Shadow Claw", Move::ShadowClaw},
    {"Thunder Fang", Move::ThunderFang},
    {"Ice Fang", Move::IceFang},
    {"Fire Fang", Move::FireFang},
    {"Shadow Sneak", Move::ShadowSneak},
    {"Mud Bomb", Move::MudBomb},
    {"Psycho Cut", Move::PsychoCut},
    {"Zen Headbutt", Move::ZenHeadbutt},
    {"Mirror Shot", Move::MirrorShot},
    {"Flash Cannon", Move::FlashCannon},
    {"Rock Climb", Move::RockClimb},
    {"Defog", Move::Defog},
    {"Trick Room", Move::TrickRoom},
    {"Draco Meteor", Move::DracoMeteor},
    {"Discharge", Move::Discharge},
    {"Lava Plume", Move::LavaPlume},
    {"Leaf Storm", Move::LeafStorm},
    {"Power Whip", Move::PowerWhip},
    {"Rock Wrecker", Move::RockWrecker},
    {"Cross Poison", Move::CrossPoison},
    {"Gunk Shot", Move::GunkShot},
    {"Iron Head", Move::IronHead},
    {"Magnet Bomb", Move::MagnetBomb},
    {"Stone Edge", Move::StoneEdge},
    {"Captivate", Move::Captivate},
    {"Stealth Rock", Move::StealthRock},
    {"Grass Knot", Move::GrassKnot},
    {"Chatter", Move::Chatter},
    {"Judgment", Move::Judgment},
    {"Bug Bite", Move::BugBite},
    {"Charge Beam", Move::ChargeBeam},
    {"Wood Hammer", Move::WoodHammer},
    {"Aqua Jet", Move::AquaJet},
    {"Attack Order", Move::AttackOrder},
    {"Defend Order", Move::DefendOrder},
    {"Heal Order", Move::HealOrder},
    {"Head Smash", Move::HeadSmash},
    {"Double Hit", Move::DoubleHit},
    {"Roar Of Time", Move::RoarOfTime},
    {"Spacial Rend", Move::SpacialRend},
    {"Lunar Dance", Move::LunarDance},
    {"Crush Grip", Move::CrushGrip},
    {"Magma Storm", Move::MagmaStorm},
    {"Dark Void", Move::DarkVoid},
    {"Seed Flare", Move::SeedFlare},
    {"Ominous Wind", Move::OminousWind},
    {"Shadow Force", Move::ShadowForce}
};

inline void verify_map() {
    std::unordered_set<Move> moves;
    for (int i = 0; i < static_cast<int>(Move::Count); ++i) {
        moves.insert(static_cast<Move>(i));
    }
    for (Move value : MOVE_MAP | std::ranges::views::values) {
        moves.erase(value);
    }
    if (moves.size() != 0) {
        throw std::logic_error("Invalid move map");
    }
}


#endif //ATTACKS_H
