#ifndef POKEMON_H
#define POKEMON_H

#include <string>
#include <unordered_map>

enum class Pokemon {
    Abomasnow,
    Abra,
    Absol,
    Aerodactyl,
    Aggron,
    Aipom,
    Alakazam,
    Altaria,
    Ambipom,
    Ampharos,
    Anorith,
    Arbok,
    Arcanine,
    Arceus,
    Ariados,
    Armaldo,
    Aron,
    Articuno,
    Azelf,
    Azumarill,
    Azurill,
    Bagon,
    Baltoy,
    Banette,
    Barboach,
    Bastiodon,
    Bayleef,
    Beautifly,
    Beedrill,
    Beldum,
    Bellossom,
    Bellsprout,
    Bibarel,
    Bidoof,
    Blastoise,
    Blaziken,
    Blissey,
    Bonsly,
    Breloom,
    Bronzong,
    Bronzor,
    Budew,
    Buizel,
    Bulbasaur,
    Buneary,
    Burmy,
    Butterfree,
    Cacnea,
    Cacturne,
    Camerupt,
    Carnivine,
    Carvanha,
    Cascoon,
    Castform,
    Caterpie,
    Celebi,
    Chansey,
    Charizard,
    Charmander,
    Charmeleon,
    Chatot,
    Cherrim,
    Cherubi,
    Chikorita,
    Chimchar,
    Chimecho,
    Chinchou,
    Chingling,
    Clamperl,
    Claydol,
    Clefable,
    Clefairy,
    Cleffa,
    Cloyster,
    Combee,
    Combusken,
    Corphish,
    Corsola,
    Cradily,
    Cranidos,
    Crawdaunt,
    Cresselia,
    Croagunk,
    Crobat,
    Croconaw,
    Cubone,
    Cyndaquil,
    Darkrai,
    Delcatty,
    Delibird,
    NormalDeoxys,
    AttackDeoxys,
    DefenseDeoxys,
    SpeedDeoxys,
    Dewgong,
    Dialga,
    Diglett,
    Ditto,
    Dodrio,
    Doduo,
    Donphan,
    Dragonair,
    Dragonite,
    Drapion,
    Dratini,
    Drifblim,
    Drifloon,
    Drowzee,
    Dugtrio,
    Dunsparce,
    Dusclops,
    Dusknoir,
    Duskull,
    Dustox,
    Eevee,
    Ekans,
    Electabuzz,
    Electivire,
    Electrike,
    Electrode,
    Elekid,
    Empoleon,
    Entei,
    Espeon,
    Exeggcute,
    Exeggutor,
    Exploud,
    Farfetchd,
    Fearow,
    Feebas,
    Feraligatr,
    Finneon,
    Flaaffy,
    Flareon,
    Floatzel,
    Flygon,
    Forretress,
    Froslass,
    Furret,
    Gabite,
    Gallade,
    Garchomp,
    Gardevoir,
    Gastly,
    Gastrodon,
    Gengar,
    Geodude,
    Gible,
    Girafarig,
    AlteredGiratina,
    OriginGiratina,
    Glaceon,
    Glalie,
    Glameow,
    Gligar,
    Gliscor,
    Gloom,
    Golbat,
    Goldeen,
    Golduck,
    Golem,
    Gorebyss,
    Granbull,
    Graveler,
    Grimer,
    Grotle,
    Groudon,
    Grovyle,
    Growlithe,
    Grumpig,
    Gulpin,
    Gyarados,
    Happiny,
    Hariyama,
    Haunter,
    Heatran,
    Heracross,
    Hippopotas,
    Hippowdon,
    Hitmonchan,
    Hitmonlee,
    Hitmontop,
    HoOh,
    Honchkrow,
    Hoothoot,
    Hoppip,
    Horsea,
    Houndoom,
    Houndour,
    Huntail,
    Hypno,
    Igglybuff,
    Illumise,
    Infernape,
    Ivysaur,
    Jigglypuff,
    Jirachi,
    Jolteon,
    Jumpluff,
    Jynx,
    Kabuto,
    Kabutops,
    Kadabra,
    Kakuna,
    Kangaskhan,
    Kecleon,
    Kingdra,
    Kingler,
    Kirlia,
    Koffing,
    Krabby,
    Kricketot,
    Kricketune,
    Kyogre,
    Lairon,
    Lanturn,
    Lapras,
    Larvitar,
    Latias,
    Latios,
    Leafeon,
    Ledian,
    Ledyba,
    Lickilicky,
    Lickitung,
    Lileep,
    Linoone,
    Lombre,
    Lopunny,
    Lotad,
    Loudred,
    Lucario,
    Ludicolo,
    Lugia,
    Lumineon,
    Lunatone,
    Luvdisc,
    Luxio,
    Luxray,
    Machamp,
    Machoke,
    Machop,
    Magby,
    Magcargo,
    Magikarp,
    Magmar,
    Magmortar,
    Magnemite,
    Magneton,
    Magnezone,
    Makuhita,
    Mamoswine,
    Manaphy,
    Manectric,
    Mankey,
    Mantine,
    Mantyke,
    Mareep,
    Marill,
    Marowak,
    Marshtomp,
    Masquerain,
    Mawile,
    Medicham,
    Meditite,
    Meganium,
    Meowth,
    Mesprit,
    Metagross,
    Metang,
    Metapod,
    Mew,
    Mewtwo,
    Mightyena,
    Milotic,
    Miltank,
    MimeJr,
    Minun,
    Misdreavus,
    Mismagius,
    Moltres,
    Monferno,
    Mothim,
    MrMime,
    Mudkip,
    Muk,
    Munchlax,
    Murkrow,
    Natu,
    Nidoking,
    Nidoqueen,
    NidoranF,
    NidoranM,
    Nidorina,
    Nidorino,
    Nincada,
    Ninetales,
    Ninjask,
    Noctowl,
    Nosepass,
    Numel,
    Nuzleaf,
    Octillery,
    Oddish,
    Omanyte,
    Omastar,
    Onix,
    Pachirisu,
    Palkia,
    Paras,
    Parasect,
    Pelipper,
    Persian,
    Phanpy,
    Phione,
    Pichu,
    Pidgeot,
    Pidgeotto,
    Pidgey,
    Pikachu,
    Piloswine,
    Pineco,
    Pinsir,
    Piplup,
    Plusle,
    Politoed,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Ponyta,
    Poochyena,
    Porygon,
    PorygonZ,
    Porygon2,
    Primeape,
    Prinplup,
    Probopass,
    Psyduck,
    Pupitar,
    Purugly,
    Quagsire,
    Quilava,
    Qwilfish,
    Raichu,
    Raikou,
    Ralts,
    Rampardos,
    Rapidash,
    Raticate,
    Rattata,
    Rayquaza,
    Regice,
    Regigigas,
    Regirock,
    Registeel,
    Relicanth,
    Remoraid,
    Rhydon,
    Rhyhorn,
    Rhyperior,
    Riolu,
    Roselia,
    Roserade,
    Rotom,
    HeatRotom,
    WashRotom,
    FrostRotom,
    FanRotom,
    MowRotom,
    Sableye,
    Salamence,
    Sandshrew,
    Sandslash,
    Sceptile,
    Scizor,
    Scyther,
    Seadra,
    Seaking,
    Sealeo,
    Seedot,
    Seel,
    Sentret,
    Seviper,
    Sharpedo,
    LandShaymin,
    SkyShaymin,
    Shedinja,
    Shelgon,
    Shellder,
    Shellos,
    Shieldon,
    Shiftry,
    Shinx,
    Shroomish,
    Shuckle,
    Shuppet,
    Silcoon,
    Skarmory,
    Skiploom,
    Skitty,
    Skorupi,
    Skuntank,
    Slaking,
    Slakoth,
    Slowbro,
    Slowking,
    Slowpoke,
    Slugma,
    Smeargle,
    Smoochum,
    Sneasel,
    Snorlax,
    Snorunt,
    Snover,
    Snubbull,
    Solrock,
    Spearow,
    Spheal,
    Spinarak,
    Spinda,
    Spiritomb,
    Spoink,
    Squirtle,
    Stantler,
    Staraptor,
    Staravia,
    Starly,
    Starmie,
    Staryu,
    Steelix,
    Stunky,
    Sudowoodo,
    Suicune,
    Sunflora,
    Sunkern,
    Surskit,
    Swablu,
    Swalot,
    Swampert,
    Swellow,
    Swinub,
    Taillow,
    Tangela,
    Tangrowth,
    Tauros,
    Teddiursa,
    Tentacool,
    Tentacruel,
    Togekiss,
    Togepi,
    Togetic,
    Torchic,
    Torkoal,
    Torterra,
    Totodile,
    Toxicroak,
    Trapinch,
    Treecko,
    Tropius,
    Turtwig,
    Typhlosion,
    Tyranitar,
    Tyrogue,
    Umbreon,
    Unown,
    Ursaring,
    Uxie,
    Vaporeon,
    Venomoth,
    Venonat,
    Venusaur,
    Vespiquen,
    Vibrava,
    Victreebel,
    Vigoroth,
    Vileplume,
    Volbeat,
    Voltorb,
    Vulpix,
    Wailmer,
    Wailord,
    Walrein,
    Wartortle,
    Weavile,
    Weedle,
    Weepinbell,
    Weezing,
    Whiscash,
    Whismur,
    Wigglytuff,
    Wingull,
    Wobbuffet,
    Wooper,
    WormadamP,
    WormadamS,
    WormadamT,
    Wurmple,
    Wynaut,
    Xatu,
    Yanma,
    Yanmega,
    Zangoose,
    Zapdos,
    Zigzagoon,
    Zubat
};

static const std::unordered_map<std::string, Pokemon> STRING_TO_POKEMON = {
    {"Abomasnow", Pokemon::Abomasnow},
    {"Abra", Pokemon::Abra},
    {"Absol", Pokemon::Absol},
    {"Aerodactyl", Pokemon::Aerodactyl},
    {"Aggron", Pokemon::Aggron},
    {"Aipom", Pokemon::Aipom},
    {"Alakazam", Pokemon::Alakazam},
    {"Altaria", Pokemon::Altaria},
    {"Ambipom", Pokemon::Ambipom},
    {"Ampharos", Pokemon::Ampharos},
    {"Anorith", Pokemon::Anorith},
    {"Arbok", Pokemon::Arbok},
    {"Arcanine", Pokemon::Arcanine},
    {"Arceus", Pokemon::Arceus},
    {"Ariados", Pokemon::Ariados},
    {"Armaldo", Pokemon::Armaldo},
    {"Aron", Pokemon::Aron},
    {"Articuno", Pokemon::Articuno},
    {"Azelf", Pokemon::Azelf},
    {"Azumarill", Pokemon::Azumarill},
    {"Azurill", Pokemon::Azurill},
    {"Bagon", Pokemon::Bagon},
    {"Baltoy", Pokemon::Baltoy},
    {"Banette", Pokemon::Banette},
    {"Barboach", Pokemon::Barboach},
    {"Bastiodon", Pokemon::Bastiodon},
    {"Bayleef", Pokemon::Bayleef},
    {"Beautifly", Pokemon::Beautifly},
    {"Beedrill", Pokemon::Beedrill},
    {"Beldum", Pokemon::Beldum},
    {"Bellossom", Pokemon::Bellossom},
    {"Bellsprout", Pokemon::Bellsprout},
    {"Bibarel", Pokemon::Bibarel},
    {"Bidoof", Pokemon::Bidoof},
    {"Blastoise", Pokemon::Blastoise},
    {"Blaziken", Pokemon::Blaziken},
    {"Blissey", Pokemon::Blissey},
    {"Bonsly", Pokemon::Bonsly},
    {"Breloom", Pokemon::Breloom},
    {"Bronzong", Pokemon::Bronzong},
    {"Bronzor", Pokemon::Bronzor},
    {"Budew", Pokemon::Budew},
    {"Buizel", Pokemon::Buizel},
    {"Bulbasaur", Pokemon::Bulbasaur},
    {"Buneary", Pokemon::Buneary},
    {"Burmy", Pokemon::Burmy},
    {"Butterfree", Pokemon::Butterfree},
    {"Cacnea", Pokemon::Cacnea},
    {"Cacturne", Pokemon::Cacturne},
    {"Camerupt", Pokemon::Camerupt},
    {"Carnivine", Pokemon::Carnivine},
    {"Carvanha", Pokemon::Carvanha},
    {"Cascoon", Pokemon::Cascoon},
    {"Castform", Pokemon::Castform},
    {"Caterpie", Pokemon::Caterpie},
    {"Celebi", Pokemon::Celebi},
    {"Chansey", Pokemon::Chansey},
    {"Charizard", Pokemon::Charizard},
    {"Charmander", Pokemon::Charmander},
    {"Charmeleon", Pokemon::Charmeleon},
    {"Chatot", Pokemon::Chatot},
    {"Cherrim", Pokemon::Cherrim},
    {"Cherubi", Pokemon::Cherubi},
    {"Chikorita", Pokemon::Chikorita},
    {"Chimchar", Pokemon::Chimchar},
    {"Chimecho", Pokemon::Chimecho},
    {"Chinchou", Pokemon::Chinchou},
    {"Chingling", Pokemon::Chingling},
    {"Clamperl", Pokemon::Clamperl},
    {"Claydol", Pokemon::Claydol},
    {"Clefable", Pokemon::Clefable},
    {"Clefairy", Pokemon::Clefairy},
    {"Cleffa", Pokemon::Cleffa},
    {"Cloyster", Pokemon::Cloyster},
    {"Combee", Pokemon::Combee},
    {"Combusken", Pokemon::Combusken},
    {"Corphish", Pokemon::Corphish},
    {"Corsola", Pokemon::Corsola},
    {"Cradily", Pokemon::Cradily},
    {"Cranidos", Pokemon::Cranidos},
    {"Crawdaunt", Pokemon::Crawdaunt},
    {"Cresselia", Pokemon::Cresselia},
    {"Croagunk", Pokemon::Croagunk},
    {"Crobat", Pokemon::Crobat},
    {"Croconaw", Pokemon::Croconaw},
    {"Cubone", Pokemon::Cubone},
    {"Cyndaquil", Pokemon::Cyndaquil},
    {"Darkrai", Pokemon::Darkrai},
    {"Delcatty", Pokemon::Delcatty},
    {"Delibird", Pokemon::Delibird},
    {"NormalDeoxys", Pokemon::NormalDeoxys},
    {"AttackDeoxys", Pokemon::AttackDeoxys},
    {"DefenseDeoxys", Pokemon::DefenseDeoxys},
    {"SpeedDeoxys", Pokemon::SpeedDeoxys},
    {"Dewgong", Pokemon::Dewgong},
    {"Dialga", Pokemon::Dialga},
    {"Diglett", Pokemon::Diglett},
    {"Ditto", Pokemon::Ditto},
    {"Dodrio", Pokemon::Dodrio},
    {"Doduo", Pokemon::Doduo},
    {"Donphan", Pokemon::Donphan},
    {"Dragonair", Pokemon::Dragonair},
    {"Dragonite", Pokemon::Dragonite},
    {"Drapion", Pokemon::Drapion},
    {"Dratini", Pokemon::Dratini},
    {"Drifblim", Pokemon::Drifblim},
    {"Drifloon", Pokemon::Drifloon},
    {"Drowzee", Pokemon::Drowzee},
    {"Dugtrio", Pokemon::Dugtrio},
    {"Dunsparce", Pokemon::Dunsparce},
    {"Dusclops", Pokemon::Dusclops},
    {"Dusknoir", Pokemon::Dusknoir},
    {"Duskull", Pokemon::Duskull},
    {"Dustox", Pokemon::Dustox},
    {"Eevee", Pokemon::Eevee},
    {"Ekans", Pokemon::Ekans},
    {"Electabuzz", Pokemon::Electabuzz},
    {"Electivire", Pokemon::Electivire},
    {"Electrike", Pokemon::Electrike},
    {"Electrode", Pokemon::Electrode},
    {"Elekid", Pokemon::Elekid},
    {"Empoleon", Pokemon::Empoleon},
    {"Entei", Pokemon::Entei},
    {"Espeon", Pokemon::Espeon},
    {"Exeggcute", Pokemon::Exeggcute},
    {"Exeggutor", Pokemon::Exeggutor},
    {"Exploud", Pokemon::Exploud},
    {"Farfetch'd", Pokemon::Farfetchd},
    {"Fearow", Pokemon::Fearow},
    {"Feebas", Pokemon::Feebas},
    {"Feraligatr", Pokemon::Feraligatr},
    {"Finneon", Pokemon::Finneon},
    {"Flaaffy", Pokemon::Flaaffy},
    {"Flareon", Pokemon::Flareon},
    {"Floatzel", Pokemon::Floatzel},
    {"Flygon", Pokemon::Flygon},
    {"Forretress", Pokemon::Forretress},
    {"Froslass", Pokemon::Froslass},
    {"Furret", Pokemon::Furret},
    {"Gabite", Pokemon::Gabite},
    {"Gallade", Pokemon::Gallade},
    {"Garchomp", Pokemon::Garchomp},
    {"Gardevoir", Pokemon::Gardevoir},
    {"Gastly", Pokemon::Gastly},
    {"Gastrodon", Pokemon::Gastrodon},
    {"Gengar", Pokemon::Gengar},
    {"Geodude", Pokemon::Geodude},
    {"Gible", Pokemon::Gible},
    {"Girafarig", Pokemon::Girafarig},
    {"AlteredGiratina", Pokemon::AlteredGiratina},
    {"OriginGiratina", Pokemon::OriginGiratina},
    {"Glaceon", Pokemon::Glaceon},
    {"Glalie", Pokemon::Glalie},
    {"Glameow", Pokemon::Glameow},
    {"Gligar", Pokemon::Gligar},
    {"Gliscor", Pokemon::Gliscor},
    {"Gloom", Pokemon::Gloom},
    {"Golbat", Pokemon::Golbat},
    {"Goldeen", Pokemon::Goldeen},
    {"Golduck", Pokemon::Golduck},
    {"Golem", Pokemon::Golem},
    {"Gorebyss", Pokemon::Gorebyss},
    {"Granbull", Pokemon::Granbull},
    {"Graveler", Pokemon::Graveler},
    {"Grimer", Pokemon::Grimer},
    {"Grotle", Pokemon::Grotle},
    {"Groudon", Pokemon::Groudon},
    {"Grovyle", Pokemon::Grovyle},
    {"Growlithe", Pokemon::Growlithe},
    {"Grumpig", Pokemon::Grumpig},
    {"Gulpin", Pokemon::Gulpin},
    {"Gyarados", Pokemon::Gyarados},
    {"Happiny", Pokemon::Happiny},
    {"Hariyama", Pokemon::Hariyama},
    {"Haunter", Pokemon::Haunter},
    {"Heatran", Pokemon::Heatran},
    {"Heracross", Pokemon::Heracross},
    {"Hippopotas", Pokemon::Hippopotas},
    {"Hippowdon", Pokemon::Hippowdon},
    {"Hitmonchan", Pokemon::Hitmonchan},
    {"Hitmonlee", Pokemon::Hitmonlee},
    {"Hitmontop", Pokemon::Hitmontop},
    {"Ho-oh", Pokemon::HoOh},
    {"Honchkrow", Pokemon::Honchkrow},
    {"Hoothoot", Pokemon::Hoothoot},
    {"Hoppip", Pokemon::Hoppip},
    {"Horsea", Pokemon::Horsea},
    {"Houndoom", Pokemon::Houndoom},
    {"Houndour", Pokemon::Houndour},
    {"Huntail", Pokemon::Huntail},
    {"Hypno", Pokemon::Hypno},
    {"Igglybuff", Pokemon::Igglybuff},
    {"Illumise", Pokemon::Illumise},
    {"Infernape", Pokemon::Infernape},
    {"Ivysaur", Pokemon::Ivysaur},
    {"Jigglypuff", Pokemon::Jigglypuff},
    {"Jirachi", Pokemon::Jirachi},
    {"Jolteon", Pokemon::Jolteon},
    {"Jumpluff", Pokemon::Jumpluff},
    {"Jynx", Pokemon::Jynx},
    {"Kabuto", Pokemon::Kabuto},
    {"Kabutops", Pokemon::Kabutops},
    {"Kadabra", Pokemon::Kadabra},
    {"Kakuna", Pokemon::Kakuna},
    {"Kangaskhan", Pokemon::Kangaskhan},
    {"Kecleon", Pokemon::Kecleon},
    {"Kingdra", Pokemon::Kingdra},
    {"Kingler", Pokemon::Kingler},
    {"Kirlia", Pokemon::Kirlia},
    {"Koffing", Pokemon::Koffing},
    {"Krabby", Pokemon::Krabby},
    {"Kricketot", Pokemon::Kricketot},
    {"Kricketune", Pokemon::Kricketune},
    {"Kyogre", Pokemon::Kyogre},
    {"Lairon", Pokemon::Lairon},
    {"Lanturn", Pokemon::Lanturn},
    {"Lapras", Pokemon::Lapras},
    {"Larvitar", Pokemon::Larvitar},
    {"Latias", Pokemon::Latias},
    {"Latios", Pokemon::Latios},
    {"Leafeon", Pokemon::Leafeon},
    {"Ledian", Pokemon::Ledian},
    {"Ledyba", Pokemon::Ledyba},
    {"Lickilicky", Pokemon::Lickilicky},
    {"Lickitung", Pokemon::Lickitung},
    {"Lileep", Pokemon::Lileep},
    {"Linoone", Pokemon::Linoone},
    {"Lombre", Pokemon::Lombre},
    {"Lopunny", Pokemon::Lopunny},
    {"Lotad", Pokemon::Lotad},
    {"Loudred", Pokemon::Loudred},
    {"Lucario", Pokemon::Lucario},
    {"Ludicolo", Pokemon::Ludicolo},
    {"Lugia", Pokemon::Lugia},
    {"Lumineon", Pokemon::Lumineon},
    {"Lunatone", Pokemon::Lunatone},
    {"Luvdisc", Pokemon::Luvdisc},
    {"Luxio", Pokemon::Luxio},
    {"Luxray", Pokemon::Luxray},
    {"Machamp", Pokemon::Machamp},
    {"Machoke", Pokemon::Machoke},
    {"Machop", Pokemon::Machop},
    {"Magby", Pokemon::Magby},
    {"Magcargo", Pokemon::Magcargo},
    {"Magikarp", Pokemon::Magikarp},
    {"Magmar", Pokemon::Magmar},
    {"Magmortar", Pokemon::Magmortar},
    {"Magnemite", Pokemon::Magnemite},
    {"Magneton", Pokemon::Magneton},
    {"Magnezone", Pokemon::Magnezone},
    {"Makuhita", Pokemon::Makuhita},
    {"Mamoswine", Pokemon::Mamoswine},
    {"Manaphy", Pokemon::Manaphy},
    {"Manectric", Pokemon::Manectric},
    {"Mankey", Pokemon::Mankey},
    {"Mantine", Pokemon::Mantine},
    {"Mantyke", Pokemon::Mantyke},
    {"Mareep", Pokemon::Mareep},
    {"Marill", Pokemon::Marill},
    {"Marowak", Pokemon::Marowak},
    {"Marshtomp", Pokemon::Marshtomp},
    {"Masquerain", Pokemon::Masquerain},
    {"Mawile", Pokemon::Mawile},
    {"Medicham", Pokemon::Medicham},
    {"Meditite", Pokemon::Meditite},
    {"Meganium", Pokemon::Meganium},
    {"Meowth", Pokemon::Meowth},
    {"Mesprit", Pokemon::Mesprit},
    {"Metagross", Pokemon::Metagross},
    {"Metang", Pokemon::Metang},
    {"Metapod", Pokemon::Metapod},
    {"Mew", Pokemon::Mew},
    {"Mewtwo", Pokemon::Mewtwo},
    {"Mightyena", Pokemon::Mightyena},
    {"Milotic", Pokemon::Milotic},
    {"Miltank", Pokemon::Miltank},
    {"Mime Jr.", Pokemon::MimeJr},
    {"Minun", Pokemon::Minun},
    {"Misdreavus", Pokemon::Misdreavus},
    {"Mismagius", Pokemon::Mismagius},
    {"Moltres", Pokemon::Moltres},
    {"Monferno", Pokemon::Monferno},
    {"Mothim", Pokemon::Mothim},
    {"Mr. Mime", Pokemon::MrMime},
    {"Mudkip", Pokemon::Mudkip},
    {"Muk", Pokemon::Muk},
    {"Munchlax", Pokemon::Munchlax},
    {"Murkrow", Pokemon::Murkrow},
    {"Natu", Pokemon::Natu},
    {"Nidoking", Pokemon::Nidoking},
    {"Nidoqueen", Pokemon::Nidoqueen},
    {"Nidoran(F)", Pokemon::NidoranF},
    {"Nidoran(M)", Pokemon::NidoranM},
    {"Nidorina", Pokemon::Nidorina},
    {"Nidorino", Pokemon::Nidorino},
    {"Nincada", Pokemon::Nincada},
    {"Ninetales", Pokemon::Ninetales},
    {"Ninjask", Pokemon::Ninjask},
    {"Noctowl", Pokemon::Noctowl},
    {"Nosepass", Pokemon::Nosepass},
    {"Numel", Pokemon::Numel},
    {"Nuzleaf", Pokemon::Nuzleaf},
    {"Octillery", Pokemon::Octillery},
    {"Oddish", Pokemon::Oddish},
    {"Omanyte", Pokemon::Omanyte},
    {"Omastar", Pokemon::Omastar},
    {"Onix", Pokemon::Onix},
    {"Pachirisu", Pokemon::Pachirisu},
    {"Palkia", Pokemon::Palkia},
    {"Paras", Pokemon::Paras},
    {"Parasect", Pokemon::Parasect},
    {"Pelipper", Pokemon::Pelipper},
    {"Persian", Pokemon::Persian},
    {"Phanpy", Pokemon::Phanpy},
    {"Phione", Pokemon::Phione},
    {"Pichu", Pokemon::Pichu},
    {"Pidgeot", Pokemon::Pidgeot},
    {"Pidgeotto", Pokemon::Pidgeotto},
    {"Pidgey", Pokemon::Pidgey},
    {"Pikachu", Pokemon::Pikachu},
    {"Piloswine", Pokemon::Piloswine},
    {"Pineco", Pokemon::Pineco},
    {"Pinsir", Pokemon::Pinsir},
    {"Piplup", Pokemon::Piplup},
    {"Plusle", Pokemon::Plusle},
    {"Politoed", Pokemon::Politoed},
    {"Poliwag", Pokemon::Poliwag},
    {"Poliwhirl", Pokemon::Poliwhirl},
    {"Poliwrath", Pokemon::Poliwrath},
    {"Ponyta", Pokemon::Ponyta},
    {"Poochyena", Pokemon::Poochyena},
    {"Porygon", Pokemon::Porygon},
    {"Porygon-Z", Pokemon::PorygonZ},
    {"Porygon2", Pokemon::Porygon2},
    {"Primeape", Pokemon::Primeape},
    {"Prinplup", Pokemon::Prinplup},
    {"Probopass", Pokemon::Probopass},
    {"Psyduck", Pokemon::Psyduck},
    {"Pupitar", Pokemon::Pupitar},
    {"Purugly", Pokemon::Purugly},
    {"Quagsire", Pokemon::Quagsire},
    {"Quilava", Pokemon::Quilava},
    {"Qwilfish", Pokemon::Qwilfish},
    {"Raichu", Pokemon::Raichu},
    {"Raikou", Pokemon::Raikou},
    {"Ralts", Pokemon::Ralts},
    {"Rampardos", Pokemon::Rampardos},
    {"Rapidash", Pokemon::Rapidash},
    {"Raticate", Pokemon::Raticate},
    {"Rattata", Pokemon::Rattata},
    {"Rayquaza", Pokemon::Rayquaza},
    {"Regice", Pokemon::Regice},
    {"Regigigas", Pokemon::Regigigas},
    {"Regirock", Pokemon::Regirock},
    {"Registeel", Pokemon::Registeel},
    {"Relicanth", Pokemon::Relicanth},
    {"Remoraid", Pokemon::Remoraid},
    {"Rhydon", Pokemon::Rhydon},
    {"Rhyhorn", Pokemon::Rhyhorn},
    {"Rhyperior", Pokemon::Rhyperior},
    {"Riolu", Pokemon::Riolu},
    {"Roselia", Pokemon::Roselia},
    {"Roserade", Pokemon::Roserade},
    {"Rotom", Pokemon::Rotom},
    {"HeatRotom", Pokemon::HeatRotom},
    {"WashRotom", Pokemon::WashRotom},
    {"FrostRotom", Pokemon::FrostRotom},
    {"FanRotom", Pokemon::FanRotom},
    {"MowRotom", Pokemon::MowRotom},
    {"Sableye", Pokemon::Sableye},
    {"Salamence", Pokemon::Salamence},
    {"Sandshrew", Pokemon::Sandshrew},
    {"Sandslash", Pokemon::Sandslash},
    {"Sceptile", Pokemon::Sceptile},
    {"Scizor", Pokemon::Scizor},
    {"Scyther", Pokemon::Scyther},
    {"Seadra", Pokemon::Seadra},
    {"Seaking", Pokemon::Seaking},
    {"Sealeo", Pokemon::Sealeo},
    {"Seedot", Pokemon::Seedot},
    {"Seel", Pokemon::Seel},
    {"Sentret", Pokemon::Sentret},
    {"Seviper", Pokemon::Seviper},
    {"Sharpedo", Pokemon::Sharpedo},
    {"SkyShaymin", Pokemon::SkyShaymin},
    {"LandShaymin", Pokemon::LandShaymin},
    {"Shedinja", Pokemon::Shedinja},
    {"Shelgon", Pokemon::Shelgon},
    {"Shellder", Pokemon::Shellder},
    {"Shellos", Pokemon::Shellos},
    {"Shieldon", Pokemon::Shieldon},
    {"Shiftry", Pokemon::Shiftry},
    {"Shinx", Pokemon::Shinx},
    {"Shroomish", Pokemon::Shroomish},
    {"Shuckle", Pokemon::Shuckle},
    {"Shuppet", Pokemon::Shuppet},
    {"Silcoon", Pokemon::Silcoon},
    {"Skarmory", Pokemon::Skarmory},
    {"Skiploom", Pokemon::Skiploom},
    {"Skitty", Pokemon::Skitty},
    {"Skorupi", Pokemon::Skorupi},
    {"Skuntank", Pokemon::Skuntank},
    {"Slaking", Pokemon::Slaking},
    {"Slakoth", Pokemon::Slakoth},
    {"Slowbro", Pokemon::Slowbro},
    {"Slowking", Pokemon::Slowking},
    {"Slowpoke", Pokemon::Slowpoke},
    {"Slugma", Pokemon::Slugma},
    {"Smeargle", Pokemon::Smeargle},
    {"Smoochum", Pokemon::Smoochum},
    {"Sneasel", Pokemon::Sneasel},
    {"Snorlax", Pokemon::Snorlax},
    {"Snorunt", Pokemon::Snorunt},
    {"Snover", Pokemon::Snover},
    {"Snubbull", Pokemon::Snubbull},
    {"Solrock", Pokemon::Solrock},
    {"Spearow", Pokemon::Spearow},
    {"Spheal", Pokemon::Spheal},
    {"Spinarak", Pokemon::Spinarak},
    {"Spinda", Pokemon::Spinda},
    {"Spiritomb", Pokemon::Spiritomb},
    {"Spoink", Pokemon::Spoink},
    {"Squirtle", Pokemon::Squirtle},
    {"Stantler", Pokemon::Stantler},
    {"Staraptor", Pokemon::Staraptor},
    {"Staravia", Pokemon::Staravia},
    {"Starly", Pokemon::Starly},
    {"Starmie", Pokemon::Starmie},
    {"Staryu", Pokemon::Staryu},
    {"Steelix", Pokemon::Steelix},
    {"Stunky", Pokemon::Stunky},
    {"Sudowoodo", Pokemon::Sudowoodo},
    {"Suicune", Pokemon::Suicune},
    {"Sunflora", Pokemon::Sunflora},
    {"Sunkern", Pokemon::Sunkern},
    {"Surskit", Pokemon::Surskit},
    {"Swablu", Pokemon::Swablu},
    {"Swalot", Pokemon::Swalot},
    {"Swampert", Pokemon::Swampert},
    {"Swellow", Pokemon::Swellow},
    {"Swinub", Pokemon::Swinub},
    {"Taillow", Pokemon::Taillow},
    {"Tangela", Pokemon::Tangela},
    {"Tangrowth", Pokemon::Tangrowth},
    {"Tauros", Pokemon::Tauros},
    {"Teddiursa", Pokemon::Teddiursa},
    {"Tentacool", Pokemon::Tentacool},
    {"Tentacruel", Pokemon::Tentacruel},
    {"Togekiss", Pokemon::Togekiss},
    {"Togepi", Pokemon::Togepi},
    {"Togetic", Pokemon::Togetic},
    {"Torchic", Pokemon::Torchic},
    {"Torkoal", Pokemon::Torkoal},
    {"Torterra", Pokemon::Torterra},
    {"Totodile", Pokemon::Totodile},
    {"Toxicroak", Pokemon::Toxicroak},
    {"Trapinch", Pokemon::Trapinch},
    {"Treecko", Pokemon::Treecko},
    {"Tropius", Pokemon::Tropius},
    {"Turtwig", Pokemon::Turtwig},
    {"Typhlosion", Pokemon::Typhlosion},
    {"Tyranitar", Pokemon::Tyranitar},
    {"Tyrogue", Pokemon::Tyrogue},
    {"Umbreon", Pokemon::Umbreon},
    {"Unown", Pokemon::Unown},
    {"Ursaring", Pokemon::Ursaring},
    {"Uxie", Pokemon::Uxie},
    {"Vaporeon", Pokemon::Vaporeon},
    {"Venomoth", Pokemon::Venomoth},
    {"Venonat", Pokemon::Venonat},
    {"Venusaur", Pokemon::Venusaur},
    {"Vespiquen", Pokemon::Vespiquen},
    {"Vibrava", Pokemon::Vibrava},
    {"Victreebel", Pokemon::Victreebel},
    {"Vigoroth", Pokemon::Vigoroth},
    {"Vileplume", Pokemon::Vileplume},
    {"Volbeat", Pokemon::Volbeat},
    {"Voltorb", Pokemon::Voltorb},
    {"Vulpix", Pokemon::Vulpix},
    {"Wailmer", Pokemon::Wailmer},
    {"Wailord", Pokemon::Wailord},
    {"Walrein", Pokemon::Walrein},
    {"Wartortle", Pokemon::Wartortle},
    {"Weavile", Pokemon::Weavile},
    {"Weedle", Pokemon::Weedle},
    {"Weepinbell", Pokemon::Weepinbell},
    {"Weezing", Pokemon::Weezing},
    {"Whiscash", Pokemon::Whiscash},
    {"Whismur", Pokemon::Whismur},
    {"Wigglytuff", Pokemon::Wigglytuff},
    {"Wingull", Pokemon::Wingull},
    {"Wobbuffet", Pokemon::Wobbuffet},
    {"Wooper", Pokemon::Wooper},
    {"WormadamP", Pokemon::WormadamP},
    {"WormadamS", Pokemon::WormadamS},
    {"WormadamT", Pokemon::WormadamT},
    {"Wurmple", Pokemon::Wurmple},
    {"Wynaut", Pokemon::Wynaut},
    {"Xatu", Pokemon::Xatu},
    {"Yanma", Pokemon::Yanma},
    {"Yanmega", Pokemon::Yanmega},
    {"Zangoose", Pokemon::Zangoose},
    {"Zapdos", Pokemon::Zapdos},
    {"Zigzagoon", Pokemon::Zigzagoon},
    {"Zubat", Pokemon::Zubat},
};

static std::unordered_map<Pokemon, std::string> create_reverse_map() {
    std::unordered_map<Pokemon, std::string> reverse_map;
    for (const auto& [str, pokemon] : STRING_TO_POKEMON) {
        reverse_map[pokemon] = str;
    }
    return reverse_map;
}

static const auto POKEMON_TO_STRING =
    create_reverse_map();

static std::string get_pokemon_name(const Pokemon p) {
    const auto it = POKEMON_TO_STRING.find(p);
    return (it != POKEMON_TO_STRING.end()) ? it->second : "Unknown";
}

#endif //POKEMON_H
